// cdaCatalog.js — typed accessor for the JSON catalogs emitted by
// tools/cda-extractor. The JSON files are committed under
// tools/cda-extractor/out/ and re-generated by the extractor; this
// module only re-exports them as ESM so the rest of the SRT Lab can
// import them without learning the file layout.
//
// Provenance: the catalogs are mined from
// attached_assets/CDA_1776448059516.swf (CWS v11, 8,716,982-byte
// inflated body, sha256 d8b08bd85cf1a7f83ac560dab1fdbfc50ada701e767e290229e66d9cc5c6560f).
// See tools/cda-extractor/src/extract.mjs and the
// cdaOfflineFlash.test.js bench trace for the full audit chain.

import CDA_FLASH_CATALOG       from '../../../../tools/cda-extractor/out/cdaFlashSequences.generated.json';
import CDA_VIN_CATALOG         from '../../../../tools/cda-extractor/out/cdaVinWrite.generated.json';
import CDA_RESET_CATALOG       from '../../../../tools/cda-extractor/out/cdaResets.generated.json';
import CDA_HARVESTED           from '../../../../tools/cda-extractor/out/harvestedStrings.generated.json';
import CDA_SID_INDEX           from '../../../../tools/cda-extractor/out/cdaSidIndex.generated.json';
import CDA_DID_INDEX           from '../../../../tools/cda-extractor/out/cdaDidIndex.generated.json';
import CDA_ROUTINE_INDEX       from '../../../../tools/cda-extractor/out/cdaRoutineIndex.generated.json';
import CDA_BINARY_DATA         from '../../../../tools/cda-extractor/out/cdaBinaryData.generated.json';
import CDA_COMMANDS_CATALOG    from '../../../../tools/cda-extractor/out/cdaCommands.generated.json';
import CDA_EVENTS_CATALOG      from '../../../../tools/cda-extractor/out/cdaEvents.generated.json';
import CDA_ENDPOINTS_CATALOG   from '../../../../tools/cda-extractor/out/cdaEndpoints.generated.json';
import CDA_LOCALIZATION_KEYS   from '../../../../tools/cda-extractor/out/cdaLocalizationKeys.generated.json';

export {
  CDA_FLASH_CATALOG,
  CDA_VIN_CATALOG,
  CDA_RESET_CATALOG,
  CDA_HARVESTED,
  // Super-mine catalogs (added by the deep AS3 ABC mine):
  CDA_SID_INDEX,
  CDA_DID_INDEX,
  CDA_ROUTINE_INDEX,
  CDA_BINARY_DATA,
  CDA_COMMANDS_CATALOG,
  CDA_EVENTS_CATALOG,
  CDA_ENDPOINTS_CATALOG,
  CDA_LOCALIZATION_KEYS,
};

// Resolve the offline-flash UDS sequence for a module by its short code
// (ECM / BCM / RFHUB / SGW / etc.). Returns null for unknown modules so
// the flasher can fall back to its hand-coded sequence.
export function getOfflineFlashSequence(code) {
  const m = CDA_FLASH_CATALOG?.modules?.[code];
  return m ? m.sequence : null;
}

// Resolve the address pair (tx, rx) and preferred unlock algorithm for
// a module from the flash catalog. Returns null when the module is not
// in the catalog.
export function getOfflineFlashModule(code) {
  const m = CDA_FLASH_CATALOG?.modules?.[code];
  if (!m) return null;
  return {
    tx: parseInt(m.tx, 16),
    rx: parseInt(m.rx, 16),
    unlockAlgo: m.unlockAlgo,
    sequence: m.sequence,
  };
}

// VIN-write DID list for a module code, decoded from the catalog's hex
// strings into integers ready for encodeDid(). Falls back to default
// when the module isn't catalogued.
export function getOfflineVinDids(code) {
  const tbl = CDA_VIN_CATALOG?.didsByModule || {};
  const list = tbl[code] || tbl.default || [];
  return list.map(h => parseInt(h, 16));
}

// Reset variant lookup. Returns the UDS sub-function byte for
// 'hardReset' / 'softReset' / 'keyOffOnReset'; null on unknown.
export function getOfflineResetSub(variant) {
  const v = CDA_RESET_CATALOG?.variants?.[variant];
  return v ? v.sub : null;
}
