/**
 * DID dictionary — human-readable labels for raw UDS DID hex codes.
 *
 * Source: `unlock_catalog_extended.json` (uds.did_maps), generated by
 *   `pnpm sweep:assets` from the AlfaOBD DID dumps under attached_assets/.
 *
 * Re-running the sweep refreshes the underlying source — no manual sync.
 *
 * Usage (sync, after one-time load):
 *   await loadDidDescriptions();
 *   getDidDescription(0x04C8);    // "Left/Right Hand Drive"
 *   getDidDescription("F190");    // "VIN" (from the curated fallback)
 *
 * The catalog file ships with multiple AlfaOBD source dumps that contain
 * duplicate DID rows (e.g. 0x04C9 → "Emode Present" AND "Auto Highbeam").
 * We collapse duplicates by keeping the first non-empty description per
 * DID and accumulate all distinct descriptions as `getDidDescriptions()`
 * for callers that want to show the full set.
 */

import {CRITICAL_DIDS} from "./backups.js";
import {DID_CATALOG} from "@workspace/uds";

const lookup = new Map();      // did(number) → first description
const allDescriptions = new Map(); // did(number) → string[]
const operations = new Map();  // did(number) → [{ protocol, group, id, label, service, value, notes }]
let loaded = false;
let loadingPromise = null;

/** Build the curated baseline from the BackupsTab CRITICAL_DIDS table. */
function seedFromCritical() {
  for (const list of Object.values(CRITICAL_DIDS || {})) {
    for (const row of list || []) {
      if (typeof row?.did !== "number" || !row.name) continue;
      if (!lookup.has(row.did)) lookup.set(row.did, row.name);
      if (!allDescriptions.has(row.did)) allDescriptions.set(row.did, []);
      const arr = allDescriptions.get(row.did);
      if (!arr.includes(row.name)) arr.push(row.name);
    }
  }
}

/**
 * Seed from the shared @workspace/uds DID catalog. Runs after
 * seedFromCritical() so that the FCA-flavoured CRITICAL_DIDS labels
 * (e.g. "Software Version" for 0xF189) win over the strict ISO names
 * from the shared catalog. The shared catalog still contributes every
 * DID it knows that is not already covered locally — including the
 * 24-bit FCA scoped block (0x6E2025, 0x6E9EB0, 0x6EF190, …), the BCM
 * 0xDExx configuration window, and the 32-bit SCI-B flag 0xF79EB045.
 */
function seedFromSharedCatalog() {
  for (const e of DID_CATALOG) {
    if (typeof e?.did !== "number" || !e.name) continue;
    if (!lookup.has(e.did)) lookup.set(e.did, e.name);
    if (!allDescriptions.has(e.did)) allDescriptions.set(e.did, []);
    const arr = allDescriptions.get(e.did);
    if (!arr.includes(e.name)) arr.push(e.name);
  }
}

function ingestEntry(didNum, value) {
  if (!Number.isFinite(didNum)) return;
  const desc = typeof value === "string" ? value.trim() : "";
  if (!desc) return;
  if (!lookup.has(didNum)) lookup.set(didNum, desc);
  if (!allDescriptions.has(didNum)) allDescriptions.set(didNum, []);
  const arr = allDescriptions.get(didNum);
  if (!arr.includes(desc)) arr.push(desc);
}

/**
 * Load the DID dictionary from the public extended unlock catalog.
 * Idempotent — concurrent calls share the same promise. Resolves to the
 * total number of distinct DIDs known to the lookup.
 */
export function loadDidDescriptions() {
  if (loaded) return Promise.resolve(lookup.size);
  if (loadingPromise) return loadingPromise;
  seedFromCritical();
  seedFromSharedCatalog();
  const base =
    (typeof import.meta !== "undefined" && import.meta.env && import.meta.env.BASE_URL) || "/";
  const url = `${base}unlock_catalog_extended.json`;
  loadingPromise = fetch(url)
    .then((r) => (r.ok ? r.json() : null))
    .then((cat) => {
      const maps = cat && cat.uds && Array.isArray(cat.uds.did_maps) ? cat.uds.did_maps : [];
      for (const m of maps) {
        const entries = Array.isArray(m.entries) ? m.entries : Array.isArray(m.sample) ? m.sample : [];
        for (const e of entries) {
          if (!e || typeof e.did === "undefined") continue;
          const n = typeof e.did === "number"
            ? e.did
            : parseInt(String(e.did).replace(/^0x/i, ""), 16);
          ingestEntry(n, e.value);
        }
      }
      const villain = cat && cat.villain_operations;
      if (villain && Array.isArray(villain.groups)) {
        for (const g of villain.groups) {
          const groupName = g?.name || "";
          const protocol = g?.protocol || "";
          for (const op of (g?.operations || [])) {
            if (!op || typeof op.did === "undefined") continue;
            const n = typeof op.did === "number"
              ? op.did
              : parseInt(String(op.did).replace(/^0x/i, ""), 16);
            if (!Number.isFinite(n)) continue;
            // Use the operation label minus the leading verb ("Read", "Write",
            // "Enable", "Disable") as a fallback DID description so the bench
            // log can render "Bus-Transmitted VIN" instead of raw hex.
            const label = (op.label || "").replace(
              /^(Read|Write|Get|Enable|Disable)\s+/i, ""
            ).trim();
            if (label) ingestEntry(n, label);
            if (!operations.has(n)) operations.set(n, []);
            operations.get(n).push({
              protocol, group: groupName,
              id: op.id, label: op.label,
              service: op.service, value: op.value, notes: op.notes,
            });
          }
        }
      }
      loaded = true;
      return lookup.size;
    })
    .catch(() => {
      // Fail soft — the lookup still has the curated baseline.
      loaded = true;
      return lookup.size;
    });
  return loadingPromise;
}

/** Normalise a DID argument (number, "0x04C8", "04C8", "F190") to a number. */
function normalise(did) {
  if (typeof did === "number" && Number.isFinite(did)) return did;
  if (typeof did === "string") {
    const t = did.trim().replace(/^0x/i, "");
    const n = parseInt(t, 16);
    if (Number.isFinite(n)) return n;
  }
  return NaN;
}

/**
 * Return the canonical description for a DID, or `""` if unknown.
 * Synchronous — call `loadDidDescriptions()` once at app start so the
 * dictionary is populated before render. Falls back to the curated
 * BackupsTab baseline when the JSON has not yet been fetched.
 */
export function getDidDescription(did) {
  if (!loaded && lookup.size === 0) { seedFromCritical(); seedFromSharedCatalog(); }
  const n = normalise(did);
  if (!Number.isFinite(n)) return "";
  return lookup.get(n) || "";
}

/**
 * Return every distinct description seen for a DID across the source
 * dumps. Useful for tooltips that want to expose the per-vendor variants
 * (e.g. 0x04C9 = ["Emode Present", "Auto Highbeam"]).
 */
export function getDidDescriptions(did) {
  if (!loaded && lookup.size === 0) { seedFromCritical(); seedFromSharedCatalog(); }
  const n = normalise(did);
  if (!Number.isFinite(n)) return [];
  return allDescriptions.get(n) ? [...allDescriptions.get(n)] : [];
}

/**
 * Return the VILLAIN operation metadata for a DID — protocol scope, group
 * name, service byte, optional value/notes. Returns `[]` if no operation
 * was indexed for the DID. Useful for tooltips and protocol-scope chips.
 */
export function getDidOperations(did) {
  if (!loaded && lookup.size === 0) { seedFromCritical(); seedFromSharedCatalog(); }
  const n = normalise(did);
  if (!Number.isFinite(n)) return [];
  return operations.get(n) ? [...operations.get(n)] : [];
}

/** Test/diagnostic helper — reset the in-memory cache. */
export function _resetDidDescriptionsForTests() {
  lookup.clear();
  allDescriptions.clear();
  operations.clear();
  loaded = false;
  loadingPromise = null;
}

/** Expose count for diagnostics tabs that want a live size readout. */
export function getDidDescriptionCount() {
  return lookup.size;
}
