/**
 * Canonical schema for unlock_catalog.json.
 *
 * The JSON file is generated by
 *   tools/python-bridge/tools/srtlab_unlock_catalog_gen.py
 * and copied into public/unlock_catalog.json as a build step
 * (scripts/copy-unlock-catalog.mjs). Both the python-bridge dispatcher and
 * the SRT Lab UI validate against THIS schema so the two consumers cannot
 * drift apart.
 *
 * See task-499.md (Generate Unlock Coverage Catalog).
 */
import { z } from "zod";

export const CATALOG_SCHEMA_VERSION = 1;

export const EcuInfoSchema = z.object({
  raw_hex: z.string().nullable(),
  name: z.string().nullable(),
  tx_can_id: z.number().int().min(0).max(0x7FF).nullable(),
  rx_can_id: z.number().int().min(0).max(0x7FF).nullable(),
  type: z.number().int().min(0).max(0xFFFF).nullable(),
  extra: z.number().int().min(0).max(0xFFFF).nullable(),
  decode_failed: z.boolean(),
  error: z.string().nullable().optional(),
  ordinals: z.record(z.string(), z.string()).optional(),
});

export const UnlockCatalogEntrySchema = z.object({
  file: z.string().regex(/\.dll$/i, "must end in .dll"),
  module: z.string().min(1),
  display_name: z.string().min(1),
  size_bytes: z.number().int().min(0),
  ecu_info: EcuInfoSchema,
  tx_can_id: z.number().int().min(0).max(0x7FF).nullable(),
  rx_can_id: z.number().int().min(0).max(0x7FF).nullable(),
  family: z.string().min(1),
  status: z.enum(["reversed", "dll_only"]),
  python_function: z.string().nullable(),
  reason: z.string().nullable(),
}).superRefine((entry, ctx) => {
  if (entry.status === "reversed") {
    if (!entry.python_function) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `reversed entry ${entry.module} must have python_function`,
        path: ["python_function"],
      });
    }
  } else {
    if (!entry.reason || entry.reason.trim() === "") {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `dll_only entry ${entry.module} must have a non-empty reason`,
        path: ["reason"],
      });
    }
  }
});

export const UnlockCatalogSchema = z.object({
  schema_version: z.literal(CATALOG_SCHEMA_VERSION),
  generated_by: z.string().optional(),
  dll_dir: z.string().optional(),
  entry_count: z.number().int().min(0),
  reversed_count: z.number().int().min(0),
  dll_only_count: z.number().int().min(0),
  entries: z.array(UnlockCatalogEntrySchema),
}).superRefine((cat, ctx) => {
  if (cat.entries.length !== cat.entry_count) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: `entry_count ${cat.entry_count} != entries.length ${cat.entries.length}`,
      path: ["entry_count"],
    });
  }
  const seen = new Set();
  for (const e of cat.entries) {
    if (seen.has(e.module)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: `duplicate module: ${e.module}`,
        path: ["entries"],
      });
    }
    seen.add(e.module);
  }
});

export function parseCatalog(raw) {
  return UnlockCatalogSchema.parse(raw);
}
