"""Harvester — emit pinned (seed, expected_key) vectors for canflash_seedkey
ports as a Python source block.  Used to regenerate the VECTORS dict in
``test_canflash_seedkey_ports.py`` whenever a new ``unlock_<dll>`` is added.

Usage::

    cd tools/python-bridge/tools
    python3 _canflash_validate/harvest_seedkey_vectors.py > /tmp/vectors_block.py

Then splice the printed dict into ``test_canflash_seedkey_ports.py``,
replacing the existing ``VECTORS = {...}`` block.

Requires Unicorn + pefile (``pip install unicorn pefile``).
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PARENT = os.path.dirname(HERE)
sys.path.insert(0, PARENT)

from srtlab_unlock_catalog import _emulate  # noqa: E402
import canflash_seedkey  # noqa: E402


SEEDS = [
    0x00000000, 0x00000001, 0x12345678, 0xA1B2C3D4,
    0xDEADBEEF, 0xFFFFFFFF, 0xCAFEBABE, 0x55555555,
    0xAAAAAAAA, 0x80000000, 0x7FFFFFFF, 0xF00DBABE,
]

# Modules whose canflash_seedkey port is dead code; production routes them
# through srtlab_canflash_algos via the dispatcher.  Vectors for those live
# in ``srtlab_canflash_algos._VECTORS``.
SKIP = {'alpine_radio', 'dcx_ptcm'}


def main():
    catalog_path = os.path.join(PARENT, 'unlock_catalog.json')
    with open(catalog_path, 'r', encoding='utf-8') as f:
        cat = json.load(f)

    entries = []
    for e in cat['entries']:
        if e['status'] != 'reversed':
            continue
        pyfn = e['python_function']
        fn = getattr(canflash_seedkey, pyfn, None)
        if fn is None or e['module'] in SKIP:
            continue
        entries.append((e['module'], e['file'][:-4], fn))
    entries.sort()

    print(f'# Generated by harvest_seedkey_vectors.py — {len(entries)} modules,'
          f' {len(SEEDS)} seeds each.', file=sys.stderr)
    print('VECTORS = {')
    for module, dll, fn in entries:
        arity = fn.__code__.co_argcount
        pairs = []
        for seed in SEEDS:
            try:
                if arity >= 2:
                    emu = _emulate(dll, seed, 0) & 0xFFFFFFFF
                    py = fn(seed, 0) & 0xFFFFFFFF
                else:
                    emu = _emulate(dll, seed, 0) & 0xFFFFFFFF
                    py = fn(seed) & 0xFFFFFFFF
            except Exception as ex:  # noqa: BLE001
                print(f'  # {module}: seed={hex(seed)} -> EXC {ex!r}', file=sys.stderr)
                continue
            if (py >> 16) == 0 and (emu & 0xFFFF) == py:
                pairs.append((seed, py))
            elif py == emu:
                pairs.append((seed, py))
            else:
                print(f'  # {module}: seed={hex(seed)} mismatch '
                      f'py={hex(py)} emu={hex(emu)}', file=sys.stderr)
        if len(pairs) < 8:
            print(f'## SKIP {module}: only {len(pairs)} vectors '
                  f'survive py-vs-DLL agreement', file=sys.stderr)
            continue
        print(f'    {module!r}: {{')
        for i in range(0, len(pairs), 4):
            chunk = pairs[i:i + 4]
            line = ', '.join(f'0x{s:08X}: 0x{k:08X}' for s, k in chunk)
            print(f'        {line},')
        print('    },')
    print('}')


if __name__ == '__main__':
    main()
