// AlfaOBD seed-key tests.
//
// Pinned vectors were generated by running the reference JS impl from
// `attached_assets/alfaobd_seedkey_1776573875649.js` (which is itself a
// 1:1 port of `alfaobd_seedkey_1776573875649.py`) against the seed list
// shared with the SGW XTEA tests. Re-generate by running:
//
//   node --input-type=module -e "import('./attached_assets/...js').then(...)"
//
// (the one-shot generator script lives in this PR's commit message).
//
// All assertions are byte-for-byte against those pinned outputs. Any
// drift here means the JS port in `src/lib/algos.js` no longer matches
// the reference, which is a regression.
import test from "node:test";
import assert from "node:assert/strict";
import {
  alfaHt, alfaF, alfaAo, alfaW6, alfaW6By,
  unlockKey, unlockKeyBytes,
  ALFA_XTEA_DELTA, ALFA_XTEA_ROUNDS, ALFA_XTEA_KEY,
  SGW_XTEA_KEY,
  ALGOS, UNLOCK_FALLBACK, pickUnlockChain,
} from "../lib/algos.js";
import { AOBD_W6, AOBD_W7, AOBD_W7_UNVERIFIED, AOBD_DISPATCH, AOBD_META }
  from "../lib/alfaobdAlgorithms.generated.js";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const SEEDS = [
  "00000000","12345678","DEADBEEF","FFFFFFFF",
  "CAFEBABE","A1B2C3D4","00112233",
];
const hex = (u8) => Array.from(u8).map(b => b.toString(16).padStart(2,"0")).join("").toUpperCase();
const bytes = (s) => {
  const r = [];
  for (let i = 0; i < 8; i += 2) r.push(parseInt(s.slice(i,i+2), 16));
  return new Uint8Array(r);
};

// ─── Pinned vectors (generated against the reference impl) ────────────
const HT_VECTORS = {
  "00000000":"41AA42BB","12345678":"D058E05B","DEADBEEF":"B47F2A2D",
  "FFFFFFFF":"9CEF2375","CAFEBABE":"16E50B70","A1B2C3D4":"6FBEDA61",
  "00112233":"402350CE",
};
const F_VECTORS = {
  "00000000":"36592FB8","12345678":"7C3B4D9E","DEADBEEF":"EC25493B",
  "FFFFFFFF":"7E81FC8F","CAFEBABE":"2B43F0CA","A1B2C3D4":"8AA96A74",
  "00112233":"4C725E6C",
};
const AO_VECTORS = {
  "00000000":"36592FB8","12345678":"FD7588E2","DEADBEEF":"594384D9",
  "FFFFFFFF":"7E81FC8F","CAFEBABE":"D20D998E","A1B2C3D4":"9CDC9663",
  "00112233":"C38FB1EE",
};
// w6 wrappers — these are the four dispatcher-mapped entries that the
// AOBD_DISPATCH table resolves directly to a w6 row (families 27 + 66).
const W6_VECTORS = {
  tt: { // r=0x234521F9 s=0x19390673
    "00000000":"234521F9","12345678":"A0B79759","DEADBEEF":"CC11D52D",
    "FFFFFFFF":"C583DC75","CAFEBABE":"7E88F030","A1B2C3D4":"2CD33963",
    "00112233":"22CD338E",
  },
  tu: { // r=0xCB92D93C s=0xE7E329BA
    "00000000":"CB92D93C","12345678":"5A7069D4","DEADBEEF":"FA4E0321",
    "FFFFFFFF":"D38E0B79","CAFEBABE":"5C85227D","A1B2C3D4":"6496C266",
    "00112233":"CA0AE94A",
  },
  tv: { // r=0x1248BB60 s=0x1047A3BE
    "00000000":"1248BB60","12345678":"918E0988","DEADBEEF":"F530EB79",
    "FFFFFFFF":"FDF0E321","CAFEBABE":"47FBCA25","A1B2C3D4":"1CEC223E",
    "00112233":"13D08916",
  },
  ez: { // r=0xB79448AC s=0xCD8B91FE
    "00000000":"B79448AC","12345678":"2456E804","DEADBEEF":"8C602AF5",
    "FFFFFFFF":"85E022AD","CAFEBABE":"2AEB0BE9","A1B2C3D4":"38B0D3B2",
    "00112233":"B60C58DA",
  },
};

// ─── Constants sanity ─────────────────────────────────────────────────
test("AlfaOBD XTEA constants are distinct from SGW XTEA", () => {
  // The user has explicitly directed: do NOT collapse the two XTEAs.
  assert.equal(ALFA_XTEA_DELTA, 0x8F750A1D);
  assert.equal(ALFA_XTEA_ROUNDS, 64);
  assert.deepEqual(ALFA_XTEA_KEY, [0x9B127D51,0x5BA41903,0x4FE87269,0x6BC361D8]);
  // Cross-check: AlfaOBD's key MUST NOT match the SGW key element-for-element.
  let same = true;
  for (let i = 0; i < 4; i++) if (ALFA_XTEA_KEY[i] !== SGW_XTEA_KEY[i]) { same = false; break; }
  assert.ok(!same, "AlfaOBD XTEA key collapsed into SGW XTEA key — REGRESSION");
});

test("catalog parses and matches expected entry counts", () => {
  assert.equal(Object.keys(AOBD_W6).length, 380);
  assert.equal(Object.keys(AOBD_W7).length, 360);
  assert.equal(Object.keys(AOBD_W7_UNVERIFIED).length, 360);
  // AOBD_W7 must remain a back-compat alias for the unverified table —
  // a regression here would mean the SeedTab UI silently started rendering
  // a different dataset. Identity check, not a deepEqual.
  assert.equal(AOBD_W7, AOBD_W7_UNVERIFIED);
  assert.equal(AOBD_META.w6_count, 380);
  assert.equal(AOBD_META.w7_count, 360);
  // Sanity: dispatcher exposes both family_* and at least one ecu_* entry.
  const keys = Object.keys(AOBD_DISPATCH);
  assert.ok(keys.some(k => k.startsWith("family_")));
  assert.ok(keys.some(k => k.startsWith("ecu_")));
});

// ─── Falsification of the "w7 ≡ w6 with p=0xFFFFFFFF" hypothesis ─────
// Task #424 asked us to verify the v2 paste's claim that the w7 cipher
// collapses to w6 when its third parameter `p` is forced to 0xFFFFFFFF.
// This test documents WHY we rejected the claim and locks the falsification
// in place so a future agent that re-encounters the same paste can see the
// reasoning without re-deriving it from scratch.
//
// Two independent failure modes:
//   (1) Zero seed→key fixtures exist (per alfaobd_seedkey_README), so the
//       claim cannot be confirmed against any real ECU transaction.
//   (2) The v2 paste's own unified table is internally inconsistent: even
//       restricted to the 110 catalog w7 entries that already carry
//       p=0xFFFFFFFF — the only subset for which the substitution is
//       trivially well-defined — only 87/110 of the paste's (r,s) pairs
//       match the catalog's (n,o). 23 entries diverge with no documented
//       derivation. A clean substitution would have produced 110/110.
//
// If we ever obtain a real seed→key capture for any w7 wrapper, the
// correct next step is NOT to re-litigate this claim; it is to translate
// the w7 cipher core from AlfaOBD's IL and verify against the capture.
// The complete list of 23 wrapper names where the v2 paste's (r,s) for an
// entry with catalog p=0xFFFFFFFF disagrees with the catalog's (n,o). Locked
// here so the forensic record is searchable in CI logs and so any future
// drift in either source surfaces as a precise diff rather than a count.
const W7_DIVERGENT_FROM_PASTE_AT_PFF = Object.freeze([
  "ap","c8","g1","gp","gs","gt","gu","gv","gw","gx","gy",
  "j8","j9","ja","jj","jm","ka","m5","m7","m8","p7","v1","v3",
]);

test("w7≡w6(p=FFFFFFFF) hypothesis is rejected — paste data contradicts catalog", (t) => {
  // Locate the v2 paste in attached_assets. If it's been removed from the
  // drop, skip explicitly with a reason — the hypothesis is still rejected
  // on grounds of (1) above (no fixtures), but the cross-check evidence
  // recorded by this test only holds while the paste is present.
  const here = dirname(fileURLToPath(import.meta.url));
  const repoRoot = resolve(here, "../../../..");
  const pastePath = resolve(repoRoot, "attached_assets/SRTLabJailbreakEdition_1776703301341.jsx");
  let paste;
  try { paste = readFileSync(pastePath, "utf8"); }
  catch {
    t.skip(`v2 paste not present at ${pastePath}; falsification still holds on grounds of zero seed/key fixtures, but the (r,s) vs (n,o) cross-check is unverifiable in this run`);
    return;
  }

  const m = paste.match(/const AOBD_W6=\{([\s\S]*?)\};/);
  assert.ok(m, "v2 paste no longer ships an inline AOBD_W6 table — re-evaluate");
  const pasteW6 = {};
  const re = /(\w+):\[(0x[0-9A-Fa-f]+),(0x[0-9A-Fa-f]+)\]/g;
  let mm;
  while ((mm = re.exec(m[1])) !== null) {
    pasteW6[mm[1]] = [parseInt(mm[2],16) >>> 0, parseInt(mm[3],16) >>> 0];
  }

  // Restrict to the trivially-well-defined subset: catalog w7 entries
  // where p=0xFFFFFFFF. The hypothesis would predict the paste's (r,s)
  // for these names equals the catalog's (n,o) byte-for-byte.
  let pFF = 0, matched = 0, diverged = 0;
  const sampleDivergent = [];
  for (const [name, trip] of Object.entries(AOBD_W7_UNVERIFIED)) {
    const [n, o, p] = trip;
    if (p !== 0xFFFFFFFF) continue;
    pFF++;
    const inPaste = pasteW6[name];
    if (!inPaste) continue;
    if (inPaste[0] === n && inPaste[1] === o) matched++;
    else {
      diverged++;
      if (sampleDivergent.length < 3) sampleDivergent.push(name);
    }
  }
  // Lock the actual numbers we measured so this test's evidence stays
  // crisp. If the catalog or the paste shifts, this assertion forces a
  // re-evaluation rather than silently passing on different data.
  assert.equal(pFF, 110, `expected 110 w7 entries with p=0xFFFFFFFF, got ${pFF}`);
  assert.equal(matched, 87, `expected 87 matches, got ${matched}`);
  assert.equal(diverged, 23, `expected 23 divergent entries, got ${diverged}`);
  // Recompute the actual divergent set and lock it against the enumerated
  // forensic list above. If the paste ever ships a corrected entry, this
  // diff will name exactly which wrapper changed instead of just shifting
  // a count.
  const measuredDivergent = [];
  for (const [name, trip] of Object.entries(AOBD_W7_UNVERIFIED)) {
    if (trip[2] !== 0xFFFFFFFF) continue;
    const ip = pasteW6[name];
    if (!ip) continue;
    if (ip[0] !== trip[0] || ip[1] !== trip[1]) measuredDivergent.push(name);
  }
  assert.deepEqual(measuredDivergent.sort(), [...W7_DIVERGENT_FROM_PASTE_AT_PFF].sort(),
    "divergent w7-at-pFF set drifted from the recorded forensic list");
});

test("AOBD_W7_UNVERIFIED entries are NOT silently exposed as alfaW6 ALGOS rows", () => {
  // The whole point of keeping the table separate is that we do not call
  // alfaW6 with these (n, o) pairs as if they were verified (r, s) pairs.
  // The four dispatcher-mapped w6 wrappers (tt/tu/tv/ez) are the only
  // alfa_w6_* entries in ALGOS today; if a future change starts auto-
  // generating alfa_w6_<w7name> rows from the unverified table, this
  // test fails so the regression is caught before users hit it.
  const allowedAlfaW6 = new Set(["alfa_w6_tt","alfa_w6_tu","alfa_w6_tv","alfa_w6_ez","alfa_w6_custom"]);
  for (const a of ALGOS) {
    if (!a.id.startsWith("alfa_w6_")) continue;
    assert.ok(allowedAlfaW6.has(a.id),
      `ALGOS entry ${a.id} appears to expose an unverified w7 wrapper as a w6 row`);
    // Verified entries must resolve to a name that exists in AOBD_W6.
    if (a.id !== "alfa_w6_custom") {
      const wrapperName = a.id.slice("alfa_w6_".length);
      assert.ok(wrapperName in AOBD_W6, `ALGOS entry ${a.id} points at non-w6 wrapper`);
      assert.ok(!(wrapperName in AOBD_W7_UNVERIFIED) || wrapperName in AOBD_W6,
        `ALGOS entry ${a.id} points at an unverified w7 wrapper`);
    }
  }
});

// PARITY: derive the dispatcher-mapped w6 wrappers from the catalog
// JSON itself (no hardcoded count) and assert ALGOS exposes a first-
// class entry for every one of them. This rules out the "we shipped a
// subset" failure mode the reviewer flagged: today the catalog has 4
// dispatcher-mapped w6 wrappers (tt/tu/tv/ez per families 27 & 66);
// if a future RE pass moves a w7 wrapper down into w6 (or adds a new
// family_/ecu_ row that points at a w6 wrapper), this test fails and
// forces ALGOS + UNLOCK_FALLBACK to be updated. The 19 w7-resolving
// dispatcher rows are explicitly NOT covered here — they're tracked
// by follow-up #145 ("translate the AlfaOBD w7 cipher").
test("ALGOS covers EVERY dispatcher-mapped w6 wrapper from the catalog", () => {
  const dispatchedW6 = new Set();
  for (const fam of Object.keys(AOBD_DISPATCH)) {
    for (const lvl of Object.keys(AOBD_DISPATCH[fam])) {
      const wrapper = AOBD_DISPATCH[fam][lvl];
      if (typeof wrapper === "string" && wrapper in AOBD_W6) {
        dispatchedW6.add(wrapper);
      }
    }
  }
  // Documented snapshot — the count must match the catalog's truth.
  // If this changes, update the comment AND ALGOS to match.
  assert.ok(dispatchedW6.size >= 1, "catalog has no dispatcher-mapped w6 wrappers");
  for (const wrapper of dispatchedW6) {
    const id = `alfa_w6_${wrapper}`;
    const entry = ALGOS.find(a => a.id === id);
    assert.ok(entry, `ALGOS missing dispatcher-mapped w6 wrapper '${wrapper}' (id ${id})`);
    assert.ok(UNLOCK_FALLBACK.includes(id), `UNLOCK_FALLBACK missing ${id}`);
  }
});

// ─── Pinned vectors ───────────────────────────────────────────────────
test("alfaHt matches pinned reference vectors", () => {
  for (const [seed, want] of Object.entries(HT_VECTORS)) {
    assert.equal(hex(alfaHt(bytes(seed))), want, `ht(${seed})`);
  }
});

test("alfaHt is literally w6(0x41AA42BB, 0x22BA9A31)", () => {
  for (const seed of SEEDS) {
    const a = hex(alfaHt(bytes(seed)));
    const b = hex(alfaW6(bytes(seed), 0x41AA42BB, 0x22BA9A31));
    assert.equal(a, b, `equivalence at seed ${seed}`);
  }
});

test("alfaF (XTEA, LE seed) matches pinned reference vectors", () => {
  for (const [seed, want] of Object.entries(F_VECTORS)) {
    assert.equal(hex(alfaF(bytes(seed))), want, `f(${seed})`);
  }
});

test("alfaAo (XTEA, BE seed) matches pinned reference vectors", () => {
  for (const [seed, want] of Object.entries(AO_VECTORS)) {
    assert.equal(hex(alfaAo(bytes(seed))), want, `ao(${seed})`);
  }
});

test("alfaW6By matches pinned vectors for the four dispatcher-mapped wrappers", () => {
  for (const [name, vec] of Object.entries(W6_VECTORS)) {
    assert.ok(name in AOBD_W6, `wrapper ${name} present in AOBD_W6`);
    for (const [seed, want] of Object.entries(vec)) {
      assert.equal(hex(alfaW6By(bytes(seed), name)), want, `w6/${name}(${seed})`);
    }
  }
});

test("alfaW6By returns null for unknown wrapper names", () => {
  assert.equal(alfaW6By(bytes("DEADBEEF"), "this_does_not_exist"), null);
});

// ─── Avalanche ────────────────────────────────────────────────────────
function avalanche(fn, bytewise=true) {
  const baseSeed = new Uint8Array([0xA1,0xB2,0xC3,0xD4]);
  const base = fn(baseSeed);
  let total = 0, n = 0;
  for (let bit = 0; bit < 32; bit++) {
    const flipped = new Uint8Array(baseSeed);
    flipped[bit >>> 3] ^= 1 << (7 - (bit & 7));
    const out = fn(flipped);
    let d = 0;
    for (let i = 0; i < 4; i++) {
      let x = (out[i] ^ base[i]) & 0xFF;
      while (x) { d += x & 1; x >>>= 1; }
    }
    total += d; n++;
  }
  return total / n;
}

test("alfaF avalanche is in [14.5, 17.5] bits", () => {
  const a = avalanche(alfaF);
  assert.ok(a >= 14.5 && a <= 17.5, `alfaF avalanche=${a.toFixed(2)} out of range`);
});

test("alfaAo avalanche is in [14.5, 17.5] bits", () => {
  const a = avalanche(alfaAo);
  assert.ok(a >= 14.5 && a <= 17.5, `alfaAo avalanche=${a.toFixed(2)} out of range`);
});

test("alfaW6 avalanche stays ≤ 4 bits (linear cipher signature)", () => {
  // Per the README: ~1.41 bits flipped per single-bit input perturbation.
  // We give a generous ceiling (4 bits) so the test isn't fragile across
  // different (r, s) pairs but still trips if w6 silently turns into XTEA.
  for (const name of ["tt","tu","tv","ez"]) {
    const a = avalanche((sb) => alfaW6By(sb, name));
    assert.ok(a <= 4.0, `w6/${name} avalanche=${a.toFixed(2)} too high — likely no longer linear`);
  }
});

// ─── Wiring ───────────────────────────────────────────────────────────
test("ALGOS registry exposes the AlfaOBD entries", () => {
  const ids = ALGOS.map(a => a.id);
  for (const id of ["alfa_ht","alfa_f","alfa_ao","alfa_w6_tt","alfa_w6_tu","alfa_w6_tv","alfa_w6_ez"]) {
    assert.ok(ids.includes(id), `missing ALGOS id ${id}`);
  }
  // None of the new entries may carry a demo flag.
  for (const a of ALGOS.filter(x => x.id.startsWith("alfa_"))) {
    assert.equal(a.demo, undefined, `${a.id} must not carry demo flag`);
    assert.ok(!/demo/i.test(a.n), `${a.id} label contains DEMO`);
  }
});

test("UNLOCK_FALLBACK puts alfa_ao directly after CDA6 and lists w6 wrappers at the tail", () => {
  // Order matters: CDA6 first (default for body-bus), then alfa_ao so
  // UCONNECT/RADIO_FGA at access level 5 resolves before we burn an
  // attempt on the GPEC XOR family. The four dispatcher-mapped w6
  // wrappers come last so a body-bus ECU that turns out to be one of
  // them still gets covered without a per-module override.
  assert.equal(UNLOCK_FALLBACK[0], "cda6");
  assert.equal(UNLOCK_FALLBACK[1], "alfa_ao");
  for (const w of ["alfa_w6_tt","alfa_w6_tu","alfa_w6_tv","alfa_w6_ez"]) {
    assert.ok(UNLOCK_FALLBACK.includes(w), `UNLOCK_FALLBACK missing ${w}`);
  }
  // GPEC family still present and ordered after alfa_ao.
  const aoIdx = UNLOCK_FALLBACK.indexOf("alfa_ao");
  const gpec2Idx = UNLOCK_FALLBACK.indexOf("gpec2");
  assert.ok(aoIdx < gpec2Idx, "alfa_ao must come before gpec2");
});

test("pickUnlockChain composes the body-bus chain with alfa_ao + w6 wrappers", () => {
  // Body-bus example: BCM at 0x742 with code 'BCM' (cda6 preferred).
  const chain = pickUnlockChain(0x742, "BCM");
  // Preferred algorithm (cda6) leads, then alfa_ao, then GPEC, then w6 tail.
  assert.equal(chain[0], "cda6");
  assert.equal(chain[1], "alfa_ao");
  assert.ok(chain.includes("gpec2"));
  for (const w of ["alfa_w6_tt","alfa_w6_tu","alfa_w6_tv","alfa_w6_ez"]) {
    assert.ok(chain.includes(w), `chain missing ${w}`);
  }
  // No duplicates.
  assert.equal(new Set(chain).size, chain.length);
});

test("pickUnlockChain on the SGW gateway stays XTEA-only — no alfa_* fallback", () => {
  const chain = pickUnlockChain(0x74F, "SGW");
  assert.deepEqual(chain, ["xtea_sgw"]);
});

test("ALGOS exposes a single AlfaOBD w6 (custom) entry", () => {
  // The reviewer-required "wrapper-or-(r,s)" entry. The fn intentionally
  // returns 0 — SeedTab is the source of truth for the actual compute,
  // because the (r, s) pair lives in UI state, not the registry.
  const custom = ALGOS.find(a => a.id === "alfa_w6_custom");
  assert.ok(custom, "alfa_w6_custom missing from ALGOS");
  assert.equal(custom.custom, "alfa_w6", "custom marker missing");
  assert.equal(custom.fn(0xDEADBEEF), 0, "bare fn must return 0 (UI handles params)");
  assert.ok(!/demo/i.test(custom.n));
});

test("unlockKey routes alfa_* ids byte-natively (and matches pinned vectors)", () => {
  const seedU32 = 0x12345678 >>> 0;
  // Round-tripping ht/ao through u32 is safe (BE pack + BE unpack).
  assert.equal(
    unlockKey("alfa_ht", seedU32).toString(16).toUpperCase().padStart(8,"0"),
    HT_VECTORS["12345678"]
  );
  assert.equal(
    unlockKey("alfa_ao", seedU32).toString(16).toUpperCase().padStart(8,"0"),
    AO_VECTORS["12345678"]
  );
});

test("unlockKeyBytes preserves alfa_f LE byte ordering", () => {
  // The whole reason unlockKeyBytes exists: alfa_f packs LE, so feeding
  // raw bytes through here must NOT mirror what unlockKey(u32) does for
  // alfa_f when the seed has any byte asymmetry.
  const sb = bytes("12345678");
  const out = unlockKeyBytes("alfa_f", sb);
  const got = out.map(b => b.toString(16).padStart(2,"0")).join("").toUpperCase();
  assert.equal(got, F_VECTORS["12345678"]);
});

test("unlockKeyBytes resolves alfa_w6/<name> wrappers from the catalog", () => {
  const out = unlockKeyBytes("alfa_w6/tt", bytes("DEADBEEF"));
  const got = out.map(b => b.toString(16).padStart(2,"0")).join("").toUpperCase();
  assert.equal(got, W6_VECTORS.tt["DEADBEEF"]);
  // Unknown wrapper → null.
  assert.equal(unlockKeyBytes("alfa_w6/zzz_unknown", bytes("00000000")), null);
});
