// AlfaOBD seed-key tests.
//
// Pinned vectors were generated by running the reference JS impl from
// `attached_assets/alfaobd_seedkey_1776573875649.js` (which is itself a
// 1:1 port of `alfaobd_seedkey_1776573875649.py`) against the seed list
// shared with the SGW XTEA tests. Re-generate by running:
//
//   node --input-type=module -e "import('./attached_assets/...js').then(...)"
//
// (the one-shot generator script lives in this PR's commit message).
//
// All assertions are byte-for-byte against those pinned outputs. Any
// drift here means the JS port in `src/lib/algos.js` no longer matches
// the reference, which is a regression.
import test from "node:test";
import assert from "node:assert/strict";
import {
  alfaHt, alfaF, alfaAo, alfaW6, alfaW6By,
  unlockKey, unlockKeyBytes,
  ALFA_XTEA_DELTA, ALFA_XTEA_ROUNDS, ALFA_XTEA_KEY,
  SGW_XTEA_KEY,
  ALGOS, UNLOCK_FALLBACK, pickUnlockChain,
} from "../lib/algos.js";
import { AOBD_W6, AOBD_W7, AOBD_DISPATCH, AOBD_META }
  from "../lib/alfaobdAlgorithms.generated.js";

const SEEDS = [
  "00000000","12345678","DEADBEEF","FFFFFFFF",
  "CAFEBABE","A1B2C3D4","00112233",
];
const hex = (u8) => Array.from(u8).map(b => b.toString(16).padStart(2,"0")).join("").toUpperCase();
const bytes = (s) => {
  const r = [];
  for (let i = 0; i < 8; i += 2) r.push(parseInt(s.slice(i,i+2), 16));
  return new Uint8Array(r);
};

// ─── Pinned vectors (generated against the reference impl) ────────────
const HT_VECTORS = {
  "00000000":"41AA42BB","12345678":"D058E05B","DEADBEEF":"B47F2A2D",
  "FFFFFFFF":"9CEF2375","CAFEBABE":"16E50B70","A1B2C3D4":"6FBEDA61",
  "00112233":"402350CE",
};
const F_VECTORS = {
  "00000000":"36592FB8","12345678":"7C3B4D9E","DEADBEEF":"EC25493B",
  "FFFFFFFF":"7E81FC8F","CAFEBABE":"2B43F0CA","A1B2C3D4":"8AA96A74",
  "00112233":"4C725E6C",
};
const AO_VECTORS = {
  "00000000":"36592FB8","12345678":"FD7588E2","DEADBEEF":"594384D9",
  "FFFFFFFF":"7E81FC8F","CAFEBABE":"D20D998E","A1B2C3D4":"9CDC9663",
  "00112233":"C38FB1EE",
};
// w6 wrappers — these are the four dispatcher-mapped entries that the
// AOBD_DISPATCH table resolves directly to a w6 row (families 27 + 66).
const W6_VECTORS = {
  tt: { // r=0x234521F9 s=0x19390673
    "00000000":"234521F9","12345678":"A0B79759","DEADBEEF":"CC11D52D",
    "FFFFFFFF":"C583DC75","CAFEBABE":"7E88F030","A1B2C3D4":"2CD33963",
    "00112233":"22CD338E",
  },
  tu: { // r=0xCB92D93C s=0xE7E329BA
    "00000000":"CB92D93C","12345678":"5A7069D4","DEADBEEF":"FA4E0321",
    "FFFFFFFF":"D38E0B79","CAFEBABE":"5C85227D","A1B2C3D4":"6496C266",
    "00112233":"CA0AE94A",
  },
  tv: { // r=0x1248BB60 s=0x1047A3BE
    "00000000":"1248BB60","12345678":"918E0988","DEADBEEF":"F530EB79",
    "FFFFFFFF":"FDF0E321","CAFEBABE":"47FBCA25","A1B2C3D4":"1CEC223E",
    "00112233":"13D08916",
  },
  ez: { // r=0xB79448AC s=0xCD8B91FE
    "00000000":"B79448AC","12345678":"2456E804","DEADBEEF":"8C602AF5",
    "FFFFFFFF":"85E022AD","CAFEBABE":"2AEB0BE9","A1B2C3D4":"38B0D3B2",
    "00112233":"B60C58DA",
  },
};

// ─── Constants sanity ─────────────────────────────────────────────────
test("AlfaOBD XTEA constants are distinct from SGW XTEA", () => {
  // The user has explicitly directed: do NOT collapse the two XTEAs.
  assert.equal(ALFA_XTEA_DELTA, 0x8F750A1D);
  assert.equal(ALFA_XTEA_ROUNDS, 64);
  assert.deepEqual(ALFA_XTEA_KEY, [0x9B127D51,0x5BA41903,0x4FE87269,0x6BC361D8]);
  // Cross-check: AlfaOBD's key MUST NOT match the SGW key element-for-element.
  let same = true;
  for (let i = 0; i < 4; i++) if (ALFA_XTEA_KEY[i] !== SGW_XTEA_KEY[i]) { same = false; break; }
  assert.ok(!same, "AlfaOBD XTEA key collapsed into SGW XTEA key — REGRESSION");
});

test("catalog parses and matches expected entry counts", () => {
  assert.equal(Object.keys(AOBD_W6).length, 380);
  assert.equal(Object.keys(AOBD_W7).length, 360);
  assert.equal(AOBD_META.w6_count, 380);
  assert.equal(AOBD_META.w7_count, 360);
  // Sanity: dispatcher exposes both family_* and at least one ecu_* entry.
  const keys = Object.keys(AOBD_DISPATCH);
  assert.ok(keys.some(k => k.startsWith("family_")));
  assert.ok(keys.some(k => k.startsWith("ecu_")));
});

// ─── Pinned vectors ───────────────────────────────────────────────────
test("alfaHt matches pinned reference vectors", () => {
  for (const [seed, want] of Object.entries(HT_VECTORS)) {
    assert.equal(hex(alfaHt(bytes(seed))), want, `ht(${seed})`);
  }
});

test("alfaHt is literally w6(0x41AA42BB, 0x22BA9A31)", () => {
  for (const seed of SEEDS) {
    const a = hex(alfaHt(bytes(seed)));
    const b = hex(alfaW6(bytes(seed), 0x41AA42BB, 0x22BA9A31));
    assert.equal(a, b, `equivalence at seed ${seed}`);
  }
});

test("alfaF (XTEA, LE seed) matches pinned reference vectors", () => {
  for (const [seed, want] of Object.entries(F_VECTORS)) {
    assert.equal(hex(alfaF(bytes(seed))), want, `f(${seed})`);
  }
});

test("alfaAo (XTEA, BE seed) matches pinned reference vectors", () => {
  for (const [seed, want] of Object.entries(AO_VECTORS)) {
    assert.equal(hex(alfaAo(bytes(seed))), want, `ao(${seed})`);
  }
});

test("alfaW6By matches pinned vectors for the four dispatcher-mapped wrappers", () => {
  for (const [name, vec] of Object.entries(W6_VECTORS)) {
    assert.ok(name in AOBD_W6, `wrapper ${name} present in AOBD_W6`);
    for (const [seed, want] of Object.entries(vec)) {
      assert.equal(hex(alfaW6By(bytes(seed), name)), want, `w6/${name}(${seed})`);
    }
  }
});

test("alfaW6By returns null for unknown wrapper names", () => {
  assert.equal(alfaW6By(bytes("DEADBEEF"), "this_does_not_exist"), null);
});

// ─── Avalanche ────────────────────────────────────────────────────────
function avalanche(fn, bytewise=true) {
  const baseSeed = new Uint8Array([0xA1,0xB2,0xC3,0xD4]);
  const base = fn(baseSeed);
  let total = 0, n = 0;
  for (let bit = 0; bit < 32; bit++) {
    const flipped = new Uint8Array(baseSeed);
    flipped[bit >>> 3] ^= 1 << (7 - (bit & 7));
    const out = fn(flipped);
    let d = 0;
    for (let i = 0; i < 4; i++) {
      let x = (out[i] ^ base[i]) & 0xFF;
      while (x) { d += x & 1; x >>>= 1; }
    }
    total += d; n++;
  }
  return total / n;
}

test("alfaF avalanche is in [14.5, 17.5] bits", () => {
  const a = avalanche(alfaF);
  assert.ok(a >= 14.5 && a <= 17.5, `alfaF avalanche=${a.toFixed(2)} out of range`);
});

test("alfaAo avalanche is in [14.5, 17.5] bits", () => {
  const a = avalanche(alfaAo);
  assert.ok(a >= 14.5 && a <= 17.5, `alfaAo avalanche=${a.toFixed(2)} out of range`);
});

test("alfaW6 avalanche stays ≤ 4 bits (linear cipher signature)", () => {
  // Per the README: ~1.41 bits flipped per single-bit input perturbation.
  // We give a generous ceiling (4 bits) so the test isn't fragile across
  // different (r, s) pairs but still trips if w6 silently turns into XTEA.
  for (const name of ["tt","tu","tv","ez"]) {
    const a = avalanche((sb) => alfaW6By(sb, name));
    assert.ok(a <= 4.0, `w6/${name} avalanche=${a.toFixed(2)} too high — likely no longer linear`);
  }
});

// ─── Wiring ───────────────────────────────────────────────────────────
test("ALGOS registry exposes the AlfaOBD entries", () => {
  const ids = ALGOS.map(a => a.id);
  for (const id of ["alfa_ht","alfa_f","alfa_ao","alfa_w6_tt","alfa_w6_tu","alfa_w6_tv","alfa_w6_ez"]) {
    assert.ok(ids.includes(id), `missing ALGOS id ${id}`);
  }
  // None of the new entries may carry a demo flag.
  for (const a of ALGOS.filter(x => x.id.startsWith("alfa_"))) {
    assert.equal(a.demo, undefined, `${a.id} must not carry demo flag`);
    assert.ok(!/demo/i.test(a.n), `${a.id} label contains DEMO`);
  }
});

test("UNLOCK_FALLBACK puts alfa_ao directly after CDA6 and lists w6 wrappers at the tail", () => {
  // Order matters: CDA6 first (default for body-bus), then alfa_ao so
  // UCONNECT/RADIO_FGA at access level 5 resolves before we burn an
  // attempt on the GPEC XOR family. The four dispatcher-mapped w6
  // wrappers come last so a body-bus ECU that turns out to be one of
  // them still gets covered without a per-module override.
  assert.equal(UNLOCK_FALLBACK[0], "cda6");
  assert.equal(UNLOCK_FALLBACK[1], "alfa_ao");
  for (const w of ["alfa_w6_tt","alfa_w6_tu","alfa_w6_tv","alfa_w6_ez"]) {
    assert.ok(UNLOCK_FALLBACK.includes(w), `UNLOCK_FALLBACK missing ${w}`);
  }
  // GPEC family still present and ordered after alfa_ao.
  const aoIdx = UNLOCK_FALLBACK.indexOf("alfa_ao");
  const gpec2Idx = UNLOCK_FALLBACK.indexOf("gpec2");
  assert.ok(aoIdx < gpec2Idx, "alfa_ao must come before gpec2");
});

test("pickUnlockChain composes the body-bus chain with alfa_ao + w6 wrappers", () => {
  // Body-bus example: BCM at 0x742 with code 'BCM' (cda6 preferred).
  const chain = pickUnlockChain(0x742, "BCM");
  // Preferred algorithm (cda6) leads, then alfa_ao, then GPEC, then w6 tail.
  assert.equal(chain[0], "cda6");
  assert.equal(chain[1], "alfa_ao");
  assert.ok(chain.includes("gpec2"));
  for (const w of ["alfa_w6_tt","alfa_w6_tu","alfa_w6_tv","alfa_w6_ez"]) {
    assert.ok(chain.includes(w), `chain missing ${w}`);
  }
  // No duplicates.
  assert.equal(new Set(chain).size, chain.length);
});

test("pickUnlockChain on the SGW gateway stays XTEA-only — no alfa_* fallback", () => {
  const chain = pickUnlockChain(0x74F, "SGW");
  assert.deepEqual(chain, ["xtea_sgw"]);
});

test("ALGOS exposes a single AlfaOBD w6 (custom) entry", () => {
  // The reviewer-required "wrapper-or-(r,s)" entry. The fn intentionally
  // returns 0 — SeedTab is the source of truth for the actual compute,
  // because the (r, s) pair lives in UI state, not the registry.
  const custom = ALGOS.find(a => a.id === "alfa_w6_custom");
  assert.ok(custom, "alfa_w6_custom missing from ALGOS");
  assert.equal(custom.custom, "alfa_w6", "custom marker missing");
  assert.equal(custom.fn(0xDEADBEEF), 0, "bare fn must return 0 (UI handles params)");
  assert.ok(!/demo/i.test(custom.n));
});

test("unlockKey routes alfa_* ids byte-natively (and matches pinned vectors)", () => {
  const seedU32 = 0x12345678 >>> 0;
  // Round-tripping ht/ao through u32 is safe (BE pack + BE unpack).
  assert.equal(
    unlockKey("alfa_ht", seedU32).toString(16).toUpperCase().padStart(8,"0"),
    HT_VECTORS["12345678"]
  );
  assert.equal(
    unlockKey("alfa_ao", seedU32).toString(16).toUpperCase().padStart(8,"0"),
    AO_VECTORS["12345678"]
  );
});

test("unlockKeyBytes preserves alfa_f LE byte ordering", () => {
  // The whole reason unlockKeyBytes exists: alfa_f packs LE, so feeding
  // raw bytes through here must NOT mirror what unlockKey(u32) does for
  // alfa_f when the seed has any byte asymmetry.
  const sb = bytes("12345678");
  const out = unlockKeyBytes("alfa_f", sb);
  const got = out.map(b => b.toString(16).padStart(2,"0")).join("").toUpperCase();
  assert.equal(got, F_VECTORS["12345678"]);
});

test("unlockKeyBytes resolves alfa_w6/<name> wrappers from the catalog", () => {
  const out = unlockKeyBytes("alfa_w6/tt", bytes("DEADBEEF"));
  const got = out.map(b => b.toString(16).padStart(2,"0")).join("").toUpperCase();
  assert.equal(got, W6_VECTORS.tt["DEADBEEF"]);
  // Unknown wrapper → null.
  assert.equal(unlockKeyBytes("alfa_w6/zzz_unknown", bytes("00000000")), null);
});
