import React, {useEffect, useMemo, useState} from "react";
import {C} from "../lib/constants.js";
import {Card, Btn} from "../lib/ui.jsx";
import {parseCatalog} from "../lib/unlockCatalogSchema.js";

/**
 * Unlock Coverage tab — Task #499.
 *
 * Renders the contents of /unlock_catalog.json (generated by
 * tools/python-bridge/tools/srtlab_unlock_catalog_gen.py and copied at
 * build time by scripts/copy-unlock-catalog.mjs).
 *
 * For every one of the 81 FCA seed→key DLLs we show:
 *   • file name + module key + display name + DLL size
 *   • decoded ecu_info (CAN tx/rx, ECU name, raw 12-byte hex)
 *   • status badge — "REVERSED" (Python port available) or "DLL ONLY"
 *     (must be emulated under Unicorn — reason text included)
 *   • Python function name when reversed
 *   • family tag for grouping
 *
 * Includes a search box, status filter, family filter, and a small
 * coverage banner with the rolled-up reversed/dll_only counts.
 */
function fmtCanId(n) {
  if (n === null || n === undefined) return "—";
  return "0x" + n.toString(16).toUpperCase().padStart(3, "0");
}

function fmtBytes(n) {
  if (!n) return "—";
  if (n < 1024) return `${n} B`;
  return `${(n / 1024).toFixed(1)} KB`;
}

const STATUS_STYLES = {
  reversed: {bg: "#1B5E2010", color: "#1B5E20", label: "NATIVE"},
  dll_only: {bg: "#E65100" + "10", color: "#E65100", label: "DLL ONLY"},
};

function StatusBadge({status}) {
  const s = STATUS_STYLES[status] || {bg: "#9E9E9E20", color: "#616161", label: String(status).toUpperCase()};
  return (
    <span style={{
      display: "inline-block", padding: "3px 9px", borderRadius: 6,
      background: s.bg, color: s.color, fontFamily: "'Nunito'",
      fontWeight: 900, fontSize: 10, letterSpacing: 1,
    }}>{s.label}</span>
  );
}

// Map raw algorithm-family tags from COVERAGE → friendly, mechanic-readable
// labels. Anything not in this map is shown verbatim (still useful for bug
// reports). Keep this conservative; the tag itself is the source of truth.
const ALGO_FRIENDLY = {
  t8_xor: "8-bit XOR table",
  "t8_xor (32-bit)": "8-bit XOR table (32-bit)",
  "t8_xor+bitpack": "8-bit XOR + bit-pack",
  "t8_xor+rotate": "8-bit XOR + rotate",
  "t8_add+bitpack": "8-bit add + bit-pack",
  "t8_add+imul": "8-bit add + IMUL",
  t8_chain: "8-bit chain",
  "t8_chain+crc": "8-bit chain + CRC",
  "t8_chain+rot": "8-bit chain + rotate",
  t8_mul_seed: "8-bit MUL seed",
  "t8_5tap_chain_xor": "8-bit 5-tap chain XOR",
  t16_mul: "16-bit MUL",
  t16_gf2: "16-bit GF(2)",
  t16x32_mixed_mul_xor: "16×32 mixed MUL/XOR",
  t32_8row_substitution: "32-bit 8-row substitution",
  lcg_pair: "LCG pair (Park-Miller)",
  lcg_halves: "LCG halves",
  rol16_chain_2pass: "ROL16 2-pass chain",
  gf2_4x4_substitution: "GF(2) 4×4 substitution",
  hitag2_lfsr48: "Hitag2 LFSR-48",
  crc32_feistel_8round: "CRC32 Feistel (8 rounds)",
  "tea-feistel": "TEA Feistel",
  cummins_t16: "Cummins 16-bit table",
  "cummins-style?": "Cummins-style",
  bit_driven_accum: "Bit-driven accumulator",
  imul_xor: "IMUL + XOR",
  "imul+t8": "IMUL + 8-bit table",
  "~s*K": "~seed × K",
  bitpack: "Bit-pack",
  inline: "Inline",
  simple: "Simple XOR",
  unfit: "Bespoke",
};

function friendlyAlgo(tag) {
  if (!tag) return null;
  return ALGO_FRIENDLY[tag] || tag;
}

function AlgoBadge({algorithm}) {
  if (!algorithm) {
    return <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "#9E9E9E"}}>—</span>;
  }
  return (
    <span
      title={`algorithm tag: ${algorithm}`}
      style={{
        display: "inline-block", padding: "2px 7px", borderRadius: 4,
        background: "#0D47A110", color: "#0D47A1",
        fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 700,
      }}
    >{friendlyAlgo(algorithm)}</span>
  );
}

// Algorithm-family chip used in the row above the table. Active chips are
// filled; inactive ones are outlined. The "All" chip clears the filter.
function AlgoChip({label, count, active, onClick, testId, title}) {
  return (
    <button
      type="button"
      data-testid={testId}
      data-active={active ? "true" : "false"}
      title={title}
      onClick={onClick}
      style={{
        display: "inline-flex", alignItems: "center", gap: 6,
        padding: "5px 10px", borderRadius: 999, cursor: "pointer",
        border: `1.5px solid ${active ? "#0D47A1" : "#0D47A140"}`,
        background: active ? "#0D47A1" : "#fff",
        color: active ? "#fff" : "#0D47A1",
        fontFamily: "'Nunito'", fontWeight: 800, fontSize: 11, letterSpacing: 0.3,
        transition: "background 0.15s, color 0.15s, border-color 0.15s",
      }}
    >
      <span>{label}</span>
      <span
        data-testid={testId ? `${testId}-count` : undefined}
        style={{
          fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 800,
          padding: "1px 6px", borderRadius: 999,
          background: active ? "#ffffff22" : "#0D47A114",
          color: active ? "#fff" : "#0D47A1",
        }}
      >{count}</span>
    </button>
  );
}

// Convert a URL ?algo=… value back into the canonical algorithm tag used
// in component state. Encoding/decoding is handled by URLSearchParams
// natively — we don't manually encodeURIComponent on the way out, since
// URLSearchParams.set() already does that and stacking the two produces
// double-encoded URLs (e.g. "+" → "%252B") for tags with reserved chars.
function slugToAlgo(slug) {
  if (slug === null || slug === undefined || slug === "") return "all";
  return slug;
}

export default function UnlockCoverageTab() {
  const [catalog, setCatalog] = useState(null);
  // dispatcherStats holds the runtime view from /api/unlock-coverage/stats
  // (the Python dispatcher's *live* native_count / emulated_count). When
  // available, it is the authoritative source for the milestone banner so
  // the UI reflects "what actually resolves right now", not just the cached
  // counts in the on-disk catalog. Falls back to catalog values if the
  // endpoint is offline or returns an error (logged via console.warn).
  const [dispatcherStats, setDispatcherStats] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);
  const [q, setQ] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [familyFilter, setFamilyFilter] = useState("all");
  // algoFilter is the active algorithm-family chip (or "all" when none).
  // It's seeded once from the URL so a shared link like
  //   /?algo=hitag2_lfsr48
  // re-opens with that chip pre-selected. We intentionally read URL state
  // lazily inside the initializer (not via useEffect) so the very first
  // render is already filtered, avoiding a brief flash of the full table.
  const [algoFilter, setAlgoFilter] = useState(() => {
    if (typeof window === "undefined") return "all";
    try {
      const sp = new URLSearchParams(window.location.search);
      return slugToAlgo(sp.get("algo"));
    } catch {
      return "all";
    }
  });
  const [expanded, setExpanded] = useState(() => new Set());

  useEffect(() => {
    let cancelled = false;
    const url = `${import.meta.env.BASE_URL || "/"}unlock_catalog.json`;
    fetch(url, {cache: "no-cache"})
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} loading ${url}`);
        return r.json();
      })
      .then((raw) => {
        if (cancelled) return;
        try {
          const parsed = parseCatalog(raw);
          setCatalog(parsed);
        } catch (e) {
          setError(`Catalog failed schema validation: ${e.message}`);
        }
      })
      .catch((e) => !cancelled && setError(e.message))
      .finally(() => !cancelled && setLoading(false));
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/unlock-coverage/stats", {cache: "no-cache"})
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} from /api/unlock-coverage/stats`);
        return r.json();
      })
      .then((data) => {
        if (cancelled) return;
        // Light validation; full validation is enforced server-side by Zod.
        if (
          data && typeof data === "object"
          && typeof data.native_count === "number"
          && typeof data.emulated_count === "number"
          && typeof data.entry_count === "number"
        ) {
          setDispatcherStats(data);
        }
      })
      .catch((e) => {
        if (!cancelled) {
          console.warn(
            "unlock-coverage stats endpoint unavailable; falling back to catalog counts:",
            e.message,
          );
        }
      });
    return () => { cancelled = true; };
  }, []);

  const families = useMemo(() => {
    if (!catalog) return [];
    const set = new Set(catalog.entries.map((e) => e.family));
    return Array.from(set).sort();
  }, [catalog]);

  // algoCounts is the data behind the chip row: one entry per distinct
  // non-empty algorithm tag, with its module count. Sorted by count desc
  // so the high-volume families (t8_xor, lcg_pair, t8_chain) come first.
  // Ties broken alphabetically by tag for a stable order across renders.
  const algoCounts = useMemo(() => {
    if (!catalog) return [];
    const m = new Map();
    for (const e of catalog.entries) {
      if (!e.algorithm) continue;
      m.set(e.algorithm, (m.get(e.algorithm) || 0) + 1);
    }
    return Array.from(m.entries())
      .map(([algorithm, count]) => ({algorithm, count}))
      .sort((a, b) => b.count - a.count || a.algorithm.localeCompare(b.algorithm));
  }, [catalog]);

  // Keep the URL in sync with the active chip so the filter is shareable.
  // Uses replaceState (not pushState) so chip clicks don't pollute browser
  // history. Skipped on the server / when there is no window.
  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const sp = new URLSearchParams(window.location.search);
      const current = sp.get("algo") || "";
      const next = algoFilter === "all" ? "" : algoFilter;
      if (current === next) return;
      if (next) sp.set("algo", next); else sp.delete("algo");
      const qs = sp.toString();
      const newUrl = window.location.pathname
        + (qs ? `?${qs}` : "")
        + (window.location.hash || "");
      window.history.replaceState(null, "", newUrl);
    } catch {
      // URL bookkeeping is best-effort; never break the UI over it.
    }
  }, [algoFilter]);

  const filtered = useMemo(() => {
    if (!catalog) return [];
    const term = q.trim().toLowerCase();
    return catalog.entries.filter((e) => {
      if (statusFilter !== "all" && e.status !== statusFilter) return false;
      if (familyFilter !== "all" && e.family !== familyFilter) return false;
      if (algoFilter !== "all" && e.algorithm !== algoFilter) return false;
      if (!term) return true;
      const blob = `${e.file} ${e.module} ${e.display_name} ${e.family} ${e.python_function || ""} ${e.algorithm || ""} ${e.ecu_info?.name || ""}`.toLowerCase();
      return blob.includes(term);
    });
  }, [catalog, q, statusFilter, familyFilter, algoFilter]);

  function toggle(module) {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(module)) next.delete(module); else next.add(module);
      return next;
    });
  }

  if (loading) {
    return <Card><div style={{color: C.tm, fontFamily: "'Nunito'", padding: 12}}>Loading unlock catalog…</div></Card>;
  }
  if (error) {
    return (
      <Card>
        <div style={{color: C.sr, fontFamily: "'Nunito'", fontWeight: 800, marginBottom: 6}}>
          Unable to load unlock_catalog.json
        </div>
        <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tm, whiteSpace: "pre-wrap"}}>{error}</div>
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginTop: 10}}>
          Regenerate with: <code style={{background: "#0001", padding: "1px 4px", borderRadius: 3}}>python3 tools/python-bridge/tools/srtlab_unlock_catalog_gen.py</code>
        </div>
      </Card>
    );
  }
  if (!catalog) return null;

  // Prefer the live dispatcher view; fall back to catalog static fields
  // when the /api/unlock-coverage/stats endpoint is unavailable. The two
  // are kept in sync by test_native_count_matches_catalog_reversed in the
  // python-bridge tests, so under normal operation they agree.
  const statsSource = dispatcherStats ? "dispatcher" : "catalog";
  const nativeCount = dispatcherStats
    ? dispatcherStats.native_count
    : catalog.reversed_count;
  const emulatedCount = dispatcherStats
    ? dispatcherStats.emulated_count
    : catalog.dll_only_count;
  const totalCount = dispatcherStats
    ? dispatcherStats.entry_count
    : catalog.entry_count;
  const pctReversed = totalCount > 0
    ? Math.round((nativeCount / totalCount) * 100)
    : 0;
  const fullyNative = totalCount > 0
    && emulatedCount === 0
    && nativeCount === totalCount;
  const algoFamilyCount = dispatcherStats?.algo_family_count ?? new Set(
    catalog.entries.map((e) => e.algorithm).filter(Boolean),
  ).size;

  return (
    <div data-testid="unlock-coverage-tab" style={{display: "flex", flexDirection: "column", gap: 14}}>
      {fullyNative && (
        <Card glow data-testid="all-native-banner" data-stats-source={statsSource} style={{
          background: "linear-gradient(90deg, #1B5E2010, #43A04710)",
          borderColor: "#1B5E20",
        }}>
          <div style={{display: "flex", flexWrap: "wrap", gap: 14, alignItems: "center"}}>
            <div style={{
              fontFamily: "'JetBrains Mono', monospace", fontWeight: 900,
              fontSize: 16, color: "#1B5E20", letterSpacing: 1,
              padding: "4px 10px", border: "2px solid #1B5E20", borderRadius: 6,
            }}>100% NATIVE</div>
            <div style={{flex: 1, minWidth: 220}}>
              <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 16, color: C.tx}}>
                Every FCA unlock now runs as a pure-Python port — zero Unicorn fallback.
              </div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tm, marginTop: 2}}>
                <span data-testid="native-count">{nativeCount}</span> / {totalCount} modules native ·{" "}
                <span data-testid="emulated-count">{emulatedCount}</span> emulated · spans{" "}
                <span data-testid="algo-family-count">{algoFamilyCount}</span> algorithm families
              </div>
              <div data-testid="stats-source" style={{
                fontFamily: "'JetBrains Mono', monospace", fontSize: 10,
                color: C.tm, marginTop: 4, letterSpacing: 0.5,
              }}>source: {statsSource === "dispatcher"
                ? "live python dispatcher"
                : "catalog (dispatcher offline — using cached counts)"}</div>
            </div>
          </div>
        </Card>
      )}

      <Card glow>
        <div style={{display: "flex", flexWrap: "wrap", gap: 18, alignItems: "baseline"}}>
          <div>
            <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 22, color: C.tx}}>Unlock Coverage</div>
            <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tm, marginTop: 2}}>
              FCA seed→key DLL catalog · schema v{catalog.schema_version}
            </div>
          </div>
          <div style={{flex: 1}}/>
          <div style={{textAlign: "right"}} data-testid="coverage-header" data-stats-source={statsSource}>
            <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 28, fontWeight: 800, color: C.tx, letterSpacing: -0.5}}>
              <span data-testid="reversed-count">{nativeCount}</span>
              <span style={{color: C.tm, fontSize: 18, fontWeight: 700}}> / </span>
              <span data-testid="total-count">{totalCount}</span>
            </div>
            <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              native Python ports · {pctReversed}% coverage ·{" "}
              <span data-testid="dll-only-count">{emulatedCount}</span> emulated
            </div>
          </div>
        </div>
        <div style={{height: 10, background: "#0000000A", borderRadius: 5, overflow: "hidden", marginTop: 14}}>
          <div style={{
            width: `${pctReversed}%`, height: "100%",
            background: `linear-gradient(90deg, #1B5E20, #43A047)`, transition: "width 0.4s",
          }}/>
        </div>
      </Card>

      <Card>
        <div style={{display: "flex", flexWrap: "wrap", gap: 10, alignItems: "center"}}>
          <input
            type="search"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search file, module, display name, family, function…"
            data-testid="catalog-search"
            style={{
              flex: "1 1 280px", padding: "9px 12px", borderRadius: 8,
              border: `1.5px solid ${C.bd}`, fontFamily: "'Nunito'", fontSize: 12,
              background: "#fff", color: C.tx,
            }}
          />
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            data-testid="status-filter"
            style={{padding: "9px 10px", borderRadius: 8, border: `1.5px solid ${C.bd}`, fontFamily: "'Nunito'", fontSize: 12, background: "#fff", color: C.tx}}
          >
            <option value="all">All statuses</option>
            <option value="reversed">Reversed only</option>
            <option value="dll_only">DLL only</option>
          </select>
          <select
            value={familyFilter}
            onChange={(e) => setFamilyFilter(e.target.value)}
            data-testid="family-filter"
            style={{padding: "9px 10px", borderRadius: 8, border: `1.5px solid ${C.bd}`, fontFamily: "'Nunito'", fontSize: 12, background: "#fff", color: C.tx}}
          >
            <option value="all">All families</option>
            {families.map((f) => <option key={f} value={f}>{f}</option>)}
          </select>
          <Btn outline onClick={() => { setQ(""); setStatusFilter("all"); setFamilyFilter("all"); setAlgoFilter("all"); }}>Reset</Btn>
        </div>
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginTop: 10}}>
          Showing <strong style={{color: C.tx}}>{filtered.length}</strong> of {catalog.entry_count} entries
        </div>
      </Card>

      {algoCounts.length > 0 && (
        <Card data-testid="algo-chip-row">
          <div style={{display: "flex", alignItems: "baseline", gap: 10, marginBottom: 10, flexWrap: "wrap"}}>
            <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 13, color: C.tx, letterSpacing: 0.3}}>
              Algorithm family
            </div>
            <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              {algoFilter === "all"
                ? `${algoCounts.length} families across ${algoCounts.reduce((s, x) => s + x.count, 0)} modules — pick one to filter`
                : <>Filtering by <strong style={{color: C.tx}}>{friendlyAlgo(algoFilter)}</strong> — click again or “All” to clear</>}
            </div>
          </div>
          <div style={{display: "flex", flexWrap: "wrap", gap: 8}}>
            <AlgoChip
              label="All"
              count={algoCounts.reduce((s, x) => s + x.count, 0)}
              active={algoFilter === "all"}
              onClick={() => setAlgoFilter("all")}
              testId="algo-chip-all"
              title="Show every algorithm family"
            />
            {algoCounts.map(({algorithm, count}) => (
              <AlgoChip
                key={algorithm}
                label={friendlyAlgo(algorithm)}
                count={count}
                active={algoFilter === algorithm}
                onClick={() => setAlgoFilter((cur) => cur === algorithm ? "all" : algorithm)}
                testId={`algo-chip-${algorithm}`}
                title={`algorithm tag: ${algorithm}`}
              />
            ))}
          </div>
        </Card>
      )}

      <Card style={{padding: 0, overflow: "hidden"}}>
        <div style={{overflowX: "auto"}}>
          <table style={{width: "100%", borderCollapse: "collapse", fontFamily: "'Nunito'", fontSize: 12}}>
            <thead>
              <tr style={{background: "#0000000A", textAlign: "left"}}>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>FILE</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>DISPLAY NAME</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>FAMILY</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>ALGO</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>TX</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>RX</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>SIZE</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>STATUS</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}></th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((e) => {
                const open = expanded.has(e.module);
                return (
                  <React.Fragment key={e.module}>
                    <tr data-testid={`row-${e.module}`} style={{borderTop: `1px solid ${C.bd}`, background: open ? "#0000000A" : "transparent"}}>
                      <td style={{padding: "10px 12px", fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tx}}>{e.file}</td>
                      <td style={{padding: "10px 12px", color: C.tx}}>{e.display_name}</td>
                      <td style={{padding: "10px 12px"}}>
                        <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm, background: "#0001", padding: "2px 6px", borderRadius: 4}}>{e.family}</span>
                      </td>
                      <td style={{padding: "10px 12px"}} data-testid={`algo-${e.module}`}>
                        <AlgoBadge algorithm={e.algorithm}/>
                      </td>
                      <td style={{padding: "10px 12px", fontFamily: "'JetBrains Mono', monospace", color: C.tx}}>{fmtCanId(e.tx_can_id)}</td>
                      <td style={{padding: "10px 12px", fontFamily: "'JetBrains Mono', monospace", color: C.tx}}>{fmtCanId(e.rx_can_id)}</td>
                      <td style={{padding: "10px 12px", color: C.tm}}>{fmtBytes(e.size_bytes)}</td>
                      <td style={{padding: "10px 12px"}}><StatusBadge status={e.status}/></td>
                      <td style={{padding: "10px 12px", textAlign: "right"}}>
                        <button
                          onClick={() => toggle(e.module)}
                          data-testid={`toggle-${e.module}`}
                          style={{
                            background: "transparent", border: `1px solid ${C.bd}`,
                            color: C.tm, fontFamily: "'Nunito'", fontWeight: 700,
                            fontSize: 10, padding: "4px 10px", borderRadius: 6, cursor: "pointer",
                          }}
                        >{open ? "Hide" : "Details"}</button>
                      </td>
                    </tr>
                    {open && (
                      <tr style={{background: "#0000000A", borderTop: `1px solid ${C.bd}`}}>
                        <td colSpan={9} style={{padding: "12px 18px"}}>
                          <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14}}>
                            <div>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>MODULE KEY</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tx, marginTop: 2}}>{e.module}</div>
                            </div>
                            <div>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>ECU NAME (DECODED)</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tx, marginTop: 2}}>
                                {e.ecu_info?.name || <span style={{color: C.tm}}>—</span>}
                              </div>
                            </div>
                            <div>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>ECU_INFO RAW (12 B)</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tx, marginTop: 2, wordBreak: "break-all"}}>
                                {e.ecu_info?.raw_hex || <span style={{color: C.tm}}>—</span>}
                              </div>
                            </div>
                            <div data-testid={`algo-detail-${e.module}`}>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>ALGORITHM</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tx, marginTop: 2}}>
                                {e.algorithm
                                  ? <>{friendlyAlgo(e.algorithm)} <span style={{color: C.tm}}>({e.algorithm})</span></>
                                  : <span style={{color: C.tm}}>—</span>}
                              </div>
                            </div>
                            {e.status === "reversed" ? (
                              <div>
                                <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>PYTHON FUNCTION</div>
                                <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: "#1B5E20", marginTop: 2}}>{e.python_function}()</div>
                              </div>
                            ) : (
                              <div style={{gridColumn: "1 / -1"}}>
                                <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>WHY DLL-ONLY</div>
                                <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tx, marginTop: 2, lineHeight: 1.5}}>{e.reason}</div>
                              </div>
                            )}
                          </div>
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                );
              })}
              {filtered.length === 0 && (
                <tr>
                  <td colSpan={9} style={{padding: "24px 12px", textAlign: "center", color: C.tm, fontFamily: "'Nunito'"}}>
                    No entries match the current filter.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
