import React, {useEffect, useMemo, useState} from "react";
import {C} from "../lib/constants.js";
import {Card, Btn} from "../lib/ui.jsx";
import {parseCatalog} from "../lib/unlockCatalogSchema.js";
import {friendlyAlgo} from "../lib/algoFriendly.js";
import {getAuth29Detections, subscribeAuth29, clearAuth29Detections, loadAuth29Detections, getAuth29Unlocks, clearAuth29Unlocks} from "../lib/auth29State.js";

/**
 * Unlock Coverage tab — Task #499.
 *
 * Renders the contents of /unlock_catalog.json (generated by
 * tools/python-bridge/tools/srtlab_unlock_catalog_gen.py and copied at
 * build time by scripts/copy-unlock-catalog.mjs).
 *
 * For every one of the 81 FCA seed→key DLLs we show:
 *   • file name + module key + display name + DLL size
 *   • decoded ecu_info (CAN tx/rx, ECU name, raw 12-byte hex)
 *   • status badge — "REVERSED" (Python port available) or "DLL ONLY"
 *     (must be emulated under Unicorn — reason text included)
 *   • Python function name when reversed
 *   • family tag for grouping
 *
 * Includes a search box, status filter, family filter, and a small
 * coverage banner with the rolled-up reversed/dll_only counts.
 */
function fmtCanId(n) {
  if (n === null || n === undefined) return "—";
  return "0x" + n.toString(16).toUpperCase().padStart(3, "0");
}

function fmtBytes(n) {
  if (!n) return "—";
  if (n < 1024) return `${n} B`;
  return `${(n / 1024).toFixed(1)} KB`;
}

const STATUS_STYLES = {
  reversed: {bg: "#1B5E2010", color: "#1B5E20", label: "NATIVE"},
  dll_only: {bg: "#E65100" + "10", color: "#E65100", label: "DLL ONLY"},
  // Task #641 — task-634 hand-curated rows surface as bench-pending
  // until an operator marks them verified against a real car.
  "bench-pending": {bg: "#E6510010", color: "#E65100", label: "BENCH-PENDING"},
  verified: {bg: "#1B5E2010", color: "#1B5E20", label: "VERIFIED"},
};

function StatusBadge({status}) {
  const s = STATUS_STYLES[status] || {bg: "#9E9E9E20", color: "#616161", label: String(status).toUpperCase()};
  return (
    <span data-status={status} style={{
      display: "inline-block", padding: "3px 9px", borderRadius: 6,
      background: s.bg, color: s.color, fontFamily: "'Nunito'",
      fontWeight: 900, fontSize: 10, letterSpacing: 1,
    }}>{s.label}</span>
  );
}

// Friendly-label + tooltip copy for algorithm-family tags lives in
// ../lib/algoFriendly.js so the badge in the table cell, the expanded
// details row, and the tests all read from the same source of truth.

function AlgoBadge({algorithm}) {
  if (!algorithm) {
    return <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "#9E9E9E"}}>—</span>;
  }
  const friendly = friendlyAlgo(algorithm);
  const isPlaceholder = !!friendly.placeholder;
  // Placeholders ("unfit", "bitpack", "cummins-style?") get a muted neutral
  // pill so the table reads consistently — they are not real algorithm
  // families, just notes from the underlying coverage data.
  const palette = isPlaceholder
    ? {bg: "#9E9E9E1F", color: "#616161"}
    : {bg: "#0D47A110", color: "#0D47A1"};
  return (
    <span
      data-placeholder={isPlaceholder ? "true" : "false"}
      data-algo-tag={algorithm}
      title={`${friendly.description} (tag: ${algorithm})`}
      style={{
        display: "inline-block", padding: "2px 7px", borderRadius: 4,
        background: palette.bg, color: palette.color,
        fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 700,
        fontStyle: isPlaceholder ? "italic" : "normal",
      }}
    >{friendly.label}</span>
  );
}

// Algorithm-family chip used in the row above the table. Active chips are
// filled; inactive ones are outlined. The "All" chip clears the filter.
function AlgoChip({label, count, active, onClick, testId, title}) {
  return (
    <button
      type="button"
      data-testid={testId}
      data-active={active ? "true" : "false"}
      title={title}
      onClick={onClick}
      style={{
        display: "inline-flex", alignItems: "center", gap: 6,
        padding: "5px 10px", borderRadius: 999, cursor: "pointer",
        border: `1.5px solid ${active ? "#0D47A1" : "#0D47A140"}`,
        background: active ? "#0D47A1" : "#fff",
        color: active ? "#fff" : "#0D47A1",
        fontFamily: "'Nunito'", fontWeight: 800, fontSize: 11, letterSpacing: 0.3,
        transition: "background 0.15s, color 0.15s, border-color 0.15s",
      }}
    >
      <span>{label}</span>
      <span
        data-testid={testId ? `${testId}-count` : undefined}
        style={{
          fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 800,
          padding: "1px 6px", borderRadius: 999,
          background: active ? "#ffffff22" : "#0D47A114",
          color: active ? "#fff" : "#0D47A1",
        }}
      >{count}</span>
    </button>
  );
}

// Convert a URL ?algo=… value back into the canonical algorithm tag used
// in component state. Encoding/decoding is handled by URLSearchParams
// natively — we don't manually encodeURIComponent on the way out, since
// URLSearchParams.set() already does that and stacking the two produces
// double-encoded URLs (e.g. "+" → "%252B") for tags with reserved chars.
function slugToAlgo(slug) {
  if (slug === null || slug === undefined || slug === "") return "all";
  return slug;
}

export default function UnlockCoverageTab() {
  const [catalog, setCatalog] = useState(null);
  // Optional extended catalog from tools/asset-sweep (DLLs + UDS tables).
  const [extCatalog, setExtCatalog] = useState(null);
  // Hand-curated task-634 competitor-parity additions (XC2268 RFHUB,
  // Mopar radio codes, dealer-lockout bypass, ZF-8HP TCU). Kept in its
  // own public/task634_entries.json so the asset-sweep regenerator
  // never clobbers the hand edits.
  const [task634, setTask634] = useState(null);
  // Task #641 — which task-634 entry ids have been marked bench-verified.
  // Hydrated from the API server first; falls back to localStorage when
  // the bench is offline. Writes propagate to both so a verification
  // made on one machine shows up on every other bench.
  const [verifiedIds, setVerifiedIds] = useState(() => {
    if (typeof window === "undefined") return new Set();
    try {
      const raw = window.localStorage.getItem("srtlab.task634.verified.v1");
      if (!raw) return new Set();
      const arr = JSON.parse(raw);
      return new Set(Array.isArray(arr) ? arr.filter((x) => typeof x === "string") : []);
    } catch {
      return new Set();
    }
  });
  // Live dispatcher stats; falls back to on-disk catalog counts if offline.
  const [dispatcherStats, setDispatcherStats] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);
  const [q, setQ] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [familyFilter, setFamilyFilter] = useState("all");
  // Active algorithm-family chip; seeded from ?algo=… so shared links open pre-filtered.
  const [algoFilter, setAlgoFilter] = useState(() => {
    if (typeof window === "undefined") return "all";
    try {
      const sp = new URLSearchParams(window.location.search);
      return slugToAlgo(sp.get("algo"));
    } catch {
      return "all";
    }
  });
  const [expanded, setExpanded] = useState(() => new Set());
  // Task #567 — UDS 0x29 detection banner state. Mirrors SeedTab's
  // subscription so a probe firing in either tab lights both up.
  const [auth29, setAuth29] = useState(() => getAuth29Detections());
  const [auth29Ok, setAuth29Ok] = useState(() => getAuth29Unlocks());
  // Task #573 — when set, the table is filtered to only modules whose
  // tx address has a confirmed 0x29 detection on file (server-side or
  // locally cached). Surfaced as a toggle chip in the search row so an
  // operator can pull up "what does this fleet need 0x29 for?" with one
  // click rather than scrolling the catalog.
  const [needs29Only, setNeeds29Only] = useState(false);
  useEffect(() => {
    const refresh = () => { setAuth29(getAuth29Detections()); setAuth29Ok(getAuth29Unlocks()); };
    const off = subscribeAuth29(refresh);
    const onStorage = (e) => { if (!e || e.key === 'srtlab.auth29.detections' || e.key === 'srtlab.auth29.unlocks') refresh(); };
    if (typeof window !== 'undefined') window.addEventListener('storage', onStorage);
    // Task #573 — hydrate from the API so the coverage banner reflects
    // server-side history, not just this browser's localStorage.
    loadAuth29Detections().then(() => refresh()).catch(() => {});
    return () => { off(); if (typeof window !== 'undefined') window.removeEventListener('storage', onStorage); };
  }, []);

  // Set of tx addresses that require 0x29, used by the table column /
  // filter below. Built from `auth29` so it tracks live updates.
  const auth29TxSet = useMemo(() => {
    const s = new Set();
    for (const d of auth29) if (Number.isFinite(d.tx)) s.add(d.tx | 0);
    return s;
  }, [auth29]);

  useEffect(() => {
    let cancelled = false;
    const url = `${import.meta.env.BASE_URL || "/"}unlock_catalog.json`;
    fetch(url, {cache: "no-cache"})
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} loading ${url}`);
        return r.json();
      })
      .then((raw) => {
        if (cancelled) return;
        try {
          const parsed = parseCatalog(raw);
          setCatalog(parsed);
        } catch (e) {
          setError(`Catalog failed schema validation: ${e.message}`);
        }
      })
      .catch((e) => !cancelled && setError(e.message))
      .finally(() => !cancelled && setLoading(false));
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    let cancelled = false;
    const url = `${import.meta.env.BASE_URL || "/"}unlock_catalog_extended.json`;
    fetch(url, {cache: "no-cache"})
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (cancelled || !data) return;
        // Light shape check; the asset-sweep tool guarantees the schema but
        // we keep the UI defensive so a corrupted file doesn't blank the tab.
        if (
          data && typeof data === "object"
          && Array.isArray(data.entries)
          && data.uds && typeof data.uds === "object"
        ) setExtCatalog(data);
      })
      .catch(() => { /* extended catalog is optional */ });
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    let cancelled = false;
    const url = `${import.meta.env.BASE_URL || "/"}task634_entries.json`;
    fetch(url, {cache: "no-cache"})
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (cancelled || !data || typeof data !== "object") return;
        // Defensive shape check — we only merge files that explicitly
        // self-identify as the task-634 hand-curated catalog so a stray
        // fetch returning unlock_catalog.json never gets double-counted.
        if (data.provenance !== "task-634" || !Array.isArray(data.entries)) return;
        setTask634(data);
      })
      .catch(() => { /* hand-curated catalog is optional */ });
    return () => { cancelled = true; };
  }, []);

  // Task #641 — hydrate verifications from the API so a flag set on
  // another bench shows up here. Server is authoritative; if it's
  // reachable we replace the localStorage seed with its view.
  useEffect(() => {
    let cancelled = false;
    fetch("/api/task634-verifications", {cache: "no-cache"})
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (cancelled || !data || !Array.isArray(data.verifications)) return;
        const ids = data.verifications
          .map((v) => v && typeof v.entryId === "string" ? v.entryId : null)
          .filter(Boolean);
        setVerifiedIds(new Set(ids));
        try {
          window.localStorage.setItem(
            "srtlab.task634.verified.v1",
            JSON.stringify(ids),
          );
        } catch { /* storage is best-effort */ }
      })
      .catch(() => { /* server is optional — localStorage seed stands */ });
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/unlock-coverage/stats", {cache: "no-cache"})
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} from /api/unlock-coverage/stats`);
        return r.json();
      })
      .then((data) => {
        if (cancelled) return;
        // Light validation; full validation is enforced server-side by Zod.
        if (
          data && typeof data === "object"
          && typeof data.native_count === "number"
          && typeof data.emulated_count === "number"
          && typeof data.entry_count === "number"
        ) {
          setDispatcherStats(data);
        }
      })
      .catch((e) => {
        if (!cancelled) {
          console.warn(
            "unlock-coverage stats endpoint unavailable; falling back to catalog counts:",
            e.message,
          );
        }
      });
    return () => { cancelled = true; };
  }, []);

  // Sweep-only delta promoted to canonical-row shape; empty when the sweep
  // adds no new DLLs. Prefer `extension_entries` to avoid double-counting
  // the canonical 81 rows that `entries` (the superset) also contains.
  // Declared before `mergedEntries` so the TDZ doesn't trip useMemo's
  // dependency capture (would otherwise throw "Cannot access 'extEntries'
  // before initialization" on first render).
  const extEntries = useMemo(() => {
    if (!extCatalog) return [];
    const sweepDelta = Array.isArray(extCatalog.extension_entries)
      ? extCatalog.extension_entries
      : (Array.isArray(extCatalog.entries) ? extCatalog.entries : []);
    return sweepDelta.map((e) => ({
      file: e.file,
      module: `ext_${e.file}`,
      display_name: e.file.replace(/\.dll$/i, ""),
      family: "asset_sweep",
      algorithm: null,
      tx_can_id: null,
      rx_can_id: null,
      ecu_info: null,
      size_bytes: e.size_bytes,
      status: e.status || "dll_only",
      python_function: null,
      reason: e.reason,
      provenance: e.provenance || extCatalog.provenance || "asset_sweep",
    }));
  }, [extCatalog]);

  // Hand-curated task-634 entries promoted to canonical-row shape so
  // they slot into the same table / chip / filter machinery. These are
  // bench-tool capabilities (not seed→key DLLs) so they have no CAN id
  // or ECU info; status is mapped to `dll_only` because the unlocks
  // exist in srt-lab itself rather than as a reversed Python port of
  // someone else's DLL — that lets the table's expanded "WHY DLL-ONLY"
  // slot render the synthesised reason / impl pointer below.
  const task634Entries = useMemo(() => {
    if (!task634 || !Array.isArray(task634.entries)) return [];
    return task634.entries.map((e) => {
      const verified = verifiedIds.has(e.id);
      const reason = [
        `Hand-curated competitor-parity addition (task #${e.task ?? 634}).`,
        e.lib ? `Implementation: ${e.lib}.` : null,
        e.ui ? `UI: ${e.ui}.` : null,
        e.status ? `Source status: ${e.status}.` : null,
      ].filter(Boolean).join(" ");
      return {
        file: e.id,
        module: `task634_${e.id}`,
        display_name: e.label || e.id,
        family: e.category ? `task634_${e.category}` : "task634",
        algorithm: e.algorithm || null,
        tx_can_id: null,
        rx_can_id: null,
        ecu_info: null,
        size_bytes: 0,
        // Task #641 — task-634 rows have their own bench-verified
        // lifecycle (bench-pending → verified) rather than the
        // python-port lifecycle (dll_only → reversed) used by the
        // generated DLL rows.
        status: verified ? "verified" : "bench-pending",
        python_function: null,
        reason,
        provenance: task634.provenance || "task-634",
        // Carry the raw id + verified flag through to the renderer so
        // the expand panel can offer a Mark verified / Unmark button.
        task634Id: e.id,
        verified,
      };
    });
  }, [task634, verifiedIds]);

  // Computed from merged rows so families/algoCounts/totals stay
  // consistent when the asset-sweep extension or task-634 hand-curated
  // additions contribute new entries.
  const mergedEntries = useMemo(
    () => (catalog ? [...catalog.entries, ...extEntries, ...task634Entries] : []),
    [catalog, extEntries, task634Entries],
  );

  const families = useMemo(() => {
    const set = new Set(mergedEntries.map((e) => e.family));
    return Array.from(set).sort();
  }, [mergedEntries]);

  const algoCounts = useMemo(() => {
    const m = new Map();
    for (const e of mergedEntries) {
      if (!e.algorithm) continue;
      m.set(e.algorithm, (m.get(e.algorithm) || 0) + 1);
    }
    return Array.from(m.entries())
      .map(([algorithm, count]) => ({algorithm, count}))
      .sort((a, b) => b.count - a.count || a.algorithm.localeCompare(b.algorithm));
  }, [mergedEntries]);

  // Keep the URL in sync with the active chip so the filter is shareable.
  // Uses replaceState (not pushState) so chip clicks don't pollute browser
  // history. Skipped on the server / when there is no window.
  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const sp = new URLSearchParams(window.location.search);
      const current = sp.get("algo") || "";
      const next = algoFilter === "all" ? "" : algoFilter;
      if (current === next) return;
      if (next) sp.set("algo", next); else sp.delete("algo");
      const qs = sp.toString();
      const newUrl = window.location.pathname
        + (qs ? `?${qs}` : "")
        + (window.location.hash || "");
      window.history.replaceState(null, "", newUrl);
    } catch {
      // URL bookkeeping is best-effort; never break the UI over it.
    }
  }, [algoFilter]);

  const filtered = useMemo(() => {
    if (!catalog) return [];
    const term = q.trim().toLowerCase();
    return mergedEntries.filter((e) => {
      if (statusFilter !== "all" && e.status !== statusFilter) return false;
      if (familyFilter !== "all" && e.family !== familyFilter) return false;
      if (algoFilter !== "all" && e.algorithm !== algoFilter) return false;
      if (needs29Only && !auth29TxSet.has(e.tx_can_id | 0)) return false;
      if (!term) return true;
      const blob = `${e.file} ${e.module} ${e.display_name} ${e.family} ${e.python_function || ""} ${e.algorithm || ""} ${e.ecu_info?.name || ""}`.toLowerCase();
      return blob.includes(term);
    });
  }, [catalog, q, statusFilter, familyFilter, algoFilter, mergedEntries, needs29Only, auth29TxSet]);

  // Quick count for the filter chip — how many catalog entries match a
  // tx address that we've confirmed (locally or server-side) requires
  // 0x29. Computed off mergedEntries so the asset-sweep delta is
  // included on equal footing.
  const needs29Count = useMemo(
    () => mergedEntries.filter((e) => auth29TxSet.has(e.tx_can_id | 0)).length,
    [mergedEntries, auth29TxSet],
  );

  // Task #641 — flip a task-634 entry between bench-pending and verified.
  // Optimistically updates local state (+ localStorage) so the badge
  // changes instantly, then mirrors to the API server. If the server
  // call fails the row still flips locally — re-hydration on the next
  // mount will reconcile.
  function markVerified(entryId, verified) {
    setVerifiedIds((prev) => {
      const next = new Set(prev);
      if (verified) next.add(entryId); else next.delete(entryId);
      try {
        window.localStorage.setItem(
          "srtlab.task634.verified.v1",
          JSON.stringify(Array.from(next)),
        );
      } catch { /* storage is best-effort */ }
      return next;
    });
    const req = verified
      ? fetch("/api/task634-verifications", {
          method: "POST",
          headers: {"Content-Type": "application/json"},
          body: JSON.stringify({entryId}),
        })
      : fetch(`/api/task634-verifications/${encodeURIComponent(entryId)}`, {
          method: "DELETE",
        });
    req.catch(() => { /* offline → localStorage holds the line */ });
  }

  function toggle(module) {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(module)) next.delete(module); else next.add(module);
      return next;
    });
  }

  if (loading) {
    return <Card><div style={{color: C.tm, fontFamily: "'Nunito'", padding: 12}}>Loading unlock catalog…</div></Card>;
  }
  if (error) {
    return (
      <Card>
        <div style={{color: C.sr, fontFamily: "'Nunito'", fontWeight: 800, marginBottom: 6}}>
          Unable to load unlock_catalog.json
        </div>
        <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tm, whiteSpace: "pre-wrap"}}>{error}</div>
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginTop: 10}}>
          Regenerate with: <code style={{background: "#0001", padding: "1px 4px", borderRadius: 3}}>python3 tools/python-bridge/tools/srtlab_unlock_catalog_gen.py</code>
        </div>
      </Card>
    );
  }
  if (!catalog) return null;

  // Prefer the live dispatcher view; fall back to catalog static fields
  // when the /api/unlock-coverage/stats endpoint is unavailable. The two
  // are kept in sync by test_native_count_matches_catalog_reversed in the
  // python-bridge tests, so under normal operation they agree.
  const statsSource = dispatcherStats ? "dispatcher" : "catalog";
  const nativeCount = dispatcherStats
    ? dispatcherStats.native_count
    : catalog.reversed_count;
  const emulatedCount = dispatcherStats
    ? dispatcherStats.emulated_count
    : catalog.dll_only_count;
  const totalCount = dispatcherStats
    ? dispatcherStats.entry_count
    : catalog.entry_count;
  const pctReversed = totalCount > 0
    ? Math.round((nativeCount / totalCount) * 100)
    : 0;
  const fullyNative = totalCount > 0
    && emulatedCount === 0
    && nativeCount === totalCount;
  const algoFamilyCount = dispatcherStats?.algo_family_count ?? new Set(
    catalog.entries.map((e) => e.algorithm).filter(Boolean),
  ).size;

  return (
    <div data-testid="unlock-coverage-tab" style={{display: "flex", flexDirection: "column", gap: 14}}>
      {auth29Ok.length > 0 && (
        <Card data-testid="auth29-unlocked-banner" style={{background: "#E8F5E9", borderColor: "#1B5E20"}}>
          <div style={{display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12}}>
            <div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, fontWeight: 900, color: "#1B5E20", letterSpacing: 1, marginBottom: 4}}>UDS 0x29 UNLOCKED</div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tx, marginBottom: 4}}>
                {auth29Ok.length === 1 ? "A module" : `${auth29Ok.length} modules`} on this bench unlocked via the UDS 0x29 Authentication challenge/response handshake.
              </div>
              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm}}>
                {auth29Ok.map(d => `tx=0x${(d.tx >>> 0).toString(16).toUpperCase().padStart(3, "0")}${d.label ? ` (${d.label})` : ""}${d.statusInfo != null ? ` · statusInfo 0x${d.statusInfo.toString(16).toUpperCase().padStart(2, "0")}` : ""}`).join(" · ")}
              </div>
            </div>
            <button onClick={clearAuth29Unlocks} data-testid="auth29-unlocked-banner-clear" style={{cursor: "pointer", border: "1.5px solid #1B5E20", padding: "4px 10px", borderRadius: 6, background: "#fff", color: "#1B5E20", fontWeight: 800, fontSize: 10, letterSpacing: 1, whiteSpace: "nowrap"}}>DISMISS</button>
          </div>
        </Card>
      )}
      {auth29.length > 0 && (
        <Card data-testid="auth29-banner" style={{background: "#FFF3E0", borderColor: "#E65100"}}>
          <div style={{display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12}}>
            <div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, fontWeight: 900, color: "#E65100", letterSpacing: 1, marginBottom: 4}}>UDS 0x29 DETECTED</div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tx, marginBottom: 4}}>
                {auth29.length === 1 ? "A module" : `${auth29.length} modules`} on this bench answered the 0x29 probe — they require Authentication (0x29) instead of SecurityAccess (0x27). The unlock catalog below cannot drive {auth29.length === 1 ? "it" : "them"} until 0x29 is implemented.
              </div>
              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm}}>
                {auth29.map(d => `tx=0x${(d.tx >>> 0).toString(16).toUpperCase().padStart(3, "0")}${d.label ? ` (${d.label})` : ""}${d.nrc != null ? ` · seed NRC 0x${d.nrc.toString(16).toUpperCase().padStart(2, "0")}` : ""}`).join(" · ")}
              </div>
            </div>
            <button onClick={clearAuth29Detections} data-testid="auth29-banner-clear" style={{cursor: "pointer", border: "1.5px solid #E65100", padding: "4px 10px", borderRadius: 6, background: "#fff", color: "#E65100", fontWeight: 800, fontSize: 10, letterSpacing: 1, whiteSpace: "nowrap"}}>DISMISS</button>
          </div>
        </Card>
      )}
      {fullyNative && (
        <Card glow data-testid="all-native-banner" data-stats-source={statsSource} style={{
          background: "linear-gradient(90deg, #1B5E2010, #43A04710)",
          borderColor: "#1B5E20",
        }}>
          <div style={{display: "flex", flexWrap: "wrap", gap: 14, alignItems: "center"}}>
            <div style={{
              fontFamily: "'JetBrains Mono', monospace", fontWeight: 900,
              fontSize: 16, color: "#1B5E20", letterSpacing: 1,
              padding: "4px 10px", border: "2px solid #1B5E20", borderRadius: 6,
            }}>100% NATIVE</div>
            <div style={{flex: 1, minWidth: 220}}>
              <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 16, color: C.tx}}>
                Every FCA unlock now runs as a pure-Python port — zero Unicorn fallback.
              </div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tm, marginTop: 2}}>
                <span data-testid="native-count">{nativeCount}</span> / {totalCount} modules native ·{" "}
                <span data-testid="emulated-count">{emulatedCount}</span> emulated · spans{" "}
                <span data-testid="algo-family-count">{algoFamilyCount}</span> algorithm families
              </div>
              <div data-testid="stats-source" style={{
                fontFamily: "'JetBrains Mono', monospace", fontSize: 10,
                color: C.tm, marginTop: 4, letterSpacing: 0.5,
              }}>source: {statsSource === "dispatcher"
                ? "live python dispatcher"
                : "catalog (dispatcher offline — using cached counts)"}</div>
            </div>
          </div>
        </Card>
      )}

      <Card glow>
        <div style={{display: "flex", flexWrap: "wrap", gap: 18, alignItems: "baseline"}}>
          <div>
            <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 22, color: C.tx}}>Unlock Coverage</div>
            <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tm, marginTop: 2}}>
              FCA seed→key DLL catalog · schema v{catalog.schema_version}
            </div>
          </div>
          <div style={{flex: 1}}/>
          <div style={{textAlign: "right"}} data-testid="coverage-header" data-stats-source={statsSource}>
            <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 28, fontWeight: 800, color: C.tx, letterSpacing: -0.5}}>
              <span data-testid="reversed-count">{nativeCount}</span>
              <span style={{color: C.tm, fontSize: 18, fontWeight: 700}}> / </span>
              <span data-testid="total-count">{totalCount}</span>
            </div>
            <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              native Python ports · {pctReversed}% coverage ·{" "}
              <span data-testid="dll-only-count">{emulatedCount}</span> emulated
            </div>
          </div>
        </div>
        <div style={{height: 10, background: "#0000000A", borderRadius: 5, overflow: "hidden", marginTop: 14}}>
          <div style={{
            width: `${pctReversed}%`, height: "100%",
            background: `linear-gradient(90deg, #1B5E20, #43A047)`, transition: "width 0.4s",
          }}/>
        </div>
      </Card>

      <Card>
        <div style={{display: "flex", flexWrap: "wrap", gap: 10, alignItems: "center"}}>
          <input
            type="search"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search file, module, display name, family, function…"
            data-testid="catalog-search"
            style={{
              flex: "1 1 280px", padding: "9px 12px", borderRadius: 8,
              border: `1.5px solid ${C.bd}`, fontFamily: "'Nunito'", fontSize: 12,
              background: "#fff", color: C.tx,
            }}
          />
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            data-testid="status-filter"
            style={{padding: "9px 10px", borderRadius: 8, border: `1.5px solid ${C.bd}`, fontFamily: "'Nunito'", fontSize: 12, background: "#fff", color: C.tx}}
          >
            <option value="all">All statuses</option>
            <option value="reversed">Reversed only</option>
            <option value="dll_only">DLL only</option>
          </select>
          <select
            value={familyFilter}
            onChange={(e) => setFamilyFilter(e.target.value)}
            data-testid="family-filter"
            style={{padding: "9px 10px", borderRadius: 8, border: `1.5px solid ${C.bd}`, fontFamily: "'Nunito'", fontSize: 12, background: "#fff", color: C.tx}}
          >
            <option value="all">All families</option>
            {families.map((f) => <option key={f} value={f}>{f}</option>)}
          </select>
          <button
            type="button"
            data-testid="needs-29-filter"
            data-active={needs29Only ? "true" : "false"}
            onClick={() => setNeeds29Only((v) => !v)}
            disabled={auth29TxSet.size === 0}
            title={auth29TxSet.size === 0
              ? "No 0x29 detections recorded yet — flag one from the bench to enable this filter"
              : `Show only modules whose tx address has a confirmed 0x29 detection (${needs29Count} match)`}
            style={{
              padding: "8px 12px", borderRadius: 8, cursor: auth29TxSet.size === 0 ? "not-allowed" : "pointer",
              border: `1.5px solid ${needs29Only ? "#E65100" : (auth29TxSet.size === 0 ? C.bd : "#E6510080")}`,
              background: needs29Only ? "#E65100" : "#fff",
              color: needs29Only ? "#fff" : (auth29TxSet.size === 0 ? C.tm : "#E65100"),
              fontFamily: "'Nunito'", fontWeight: 800, fontSize: 11, letterSpacing: 0.5,
              opacity: auth29TxSet.size === 0 ? 0.55 : 1, whiteSpace: "nowrap",
            }}
          >
            Needs 0x29
            <span data-testid="needs-29-filter-count" style={{
              marginLeft: 6, fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 800,
              padding: "1px 6px", borderRadius: 999,
              background: needs29Only ? "#ffffff22" : "#E6510014",
              color: needs29Only ? "#fff" : "#E65100",
            }}>{needs29Count}</span>
          </button>
          <Btn outline onClick={() => { setQ(""); setStatusFilter("all"); setFamilyFilter("all"); setAlgoFilter("all"); setNeeds29Only(false); }}>Reset</Btn>
        </div>
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginTop: 10}}>
          Showing <strong style={{color: C.tx}}>{filtered.length}</strong> of {mergedEntries.length} entries
        </div>
      </Card>

      {algoCounts.length > 0 && (
        <Card data-testid="algo-chip-row">
          <div style={{display: "flex", alignItems: "baseline", gap: 10, marginBottom: 10, flexWrap: "wrap"}}>
            <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 13, color: C.tx, letterSpacing: 0.3}}>
              Algorithm family
            </div>
            <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              {algoFilter === "all"
                ? `${algoCounts.length} families across ${algoCounts.reduce((s, x) => s + x.count, 0)} modules — pick one to filter`
                : <>Filtering by <strong style={{color: C.tx}}>{friendlyAlgo(algoFilter).label}</strong> — click again or “All” to clear</>}
            </div>
          </div>
          <div style={{display: "flex", flexWrap: "wrap", gap: 8}}>
            <AlgoChip
              label="All"
              count={algoCounts.reduce((s, x) => s + x.count, 0)}
              active={algoFilter === "all"}
              onClick={() => setAlgoFilter("all")}
              testId="algo-chip-all"
              title="Show every algorithm family"
            />
            {algoCounts.map(({algorithm, count}) => {
              const f = friendlyAlgo(algorithm);
              return (
                <AlgoChip
                  key={algorithm}
                  label={f.label}
                  count={count}
                  active={algoFilter === algorithm}
                  onClick={() => setAlgoFilter((cur) => cur === algorithm ? "all" : algorithm)}
                  testId={`algo-chip-${algorithm}`}
                  title={`${f.description} (tag: ${algorithm})`}
                />
              );
            })}
          </div>
        </Card>
      )}

      <Card style={{padding: 0, overflow: "hidden"}}>
        <div style={{overflowX: "auto"}}>
          <table style={{width: "100%", borderCollapse: "collapse", fontFamily: "'Nunito'", fontSize: 12}}>
            <thead>
              <tr style={{background: "#0000000A", textAlign: "left"}}>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>FILE</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>DISPLAY NAME</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>FAMILY</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>ALGO</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>TX</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>RX</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>SIZE</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>STATUS</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>0x29</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}></th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((e) => {
                const open = expanded.has(e.module);
                return (
                  <React.Fragment key={e.module}>
                    <tr data-testid={`row-${e.module}`} data-provenance={e.provenance || "catalog"} style={{borderTop: `1px solid ${C.bd}`, background: open ? "#0000000A" : "transparent"}}>
                      <td style={{padding: "10px 12px", fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tx}}>
                        {e.file}
                        {e.provenance === "asset_sweep" && (
                          <span data-testid={`provenance-chip-${e.module}`} title="Surfaced by tools/asset-sweep — re-run with `pnpm sweep:assets`" style={{
                            marginLeft: 8, fontFamily: "'JetBrains Mono', monospace",
                            fontSize: 8, fontWeight: 800, letterSpacing: 1,
                            padding: "1px 5px", borderRadius: 3,
                            background: "#9C27B014", color: "#6A1B9A",
                          }}>SWEEP</span>
                        )}
                        {e.provenance === "task-634" && (
                          <span data-testid={`provenance-chip-${e.module}`} title="Hand-curated task #634 competitor-parity addition — see public/task634_entries.json" style={{
                            marginLeft: 8, fontFamily: "'JetBrains Mono', monospace",
                            fontSize: 8, fontWeight: 800, letterSpacing: 1,
                            padding: "1px 5px", borderRadius: 3,
                            background: "#D32F2F14", color: "#B71C1C",
                          }}>TASK 634</span>
                        )}
                      </td>
                      <td style={{padding: "10px 12px", color: C.tx}}>{e.display_name}</td>
                      <td style={{padding: "10px 12px"}}>
                        <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm, background: "#0001", padding: "2px 6px", borderRadius: 4}}>{e.family}</span>
                      </td>
                      <td style={{padding: "10px 12px"}} data-testid={`algo-${e.module}`}>
                        <AlgoBadge algorithm={e.algorithm}/>
                      </td>
                      <td style={{padding: "10px 12px", fontFamily: "'JetBrains Mono', monospace", color: C.tx}}>{fmtCanId(e.tx_can_id)}</td>
                      <td style={{padding: "10px 12px", fontFamily: "'JetBrains Mono', monospace", color: C.tx}}>{fmtCanId(e.rx_can_id)}</td>
                      <td style={{padding: "10px 12px", color: C.tm}}>{fmtBytes(e.size_bytes)}</td>
                      <td style={{padding: "10px 12px"}}><StatusBadge status={e.status}/></td>
                      <td style={{padding: "10px 12px"}} data-testid={`auth29-cell-${e.module}`}>
                        {auth29TxSet.has(e.tx_can_id | 0) ? (
                          <span
                            data-testid={`auth29-required-${e.module}`}
                            title="Confirmed 0x29 detection on this tx address"
                            style={{
                              display: "inline-block", padding: "3px 8px", borderRadius: 6,
                              background: "#E6510014", color: "#E65100",
                              fontFamily: "'JetBrains Mono', monospace",
                              fontWeight: 900, fontSize: 10, letterSpacing: 1,
                            }}
                          >REQ 0x29</span>
                        ) : (
                          <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm}}>—</span>
                        )}
                      </td>
                      <td style={{padding: "10px 12px", textAlign: "right"}}>
                        <button
                          onClick={() => toggle(e.module)}
                          data-testid={`toggle-${e.module}`}
                          style={{
                            background: "transparent", border: `1px solid ${C.bd}`,
                            color: C.tm, fontFamily: "'Nunito'", fontWeight: 700,
                            fontSize: 10, padding: "4px 10px", borderRadius: 6, cursor: "pointer",
                          }}
                        >{open ? "Hide" : "Details"}</button>
                      </td>
                    </tr>
                    {open && (
                      <tr style={{background: "#0000000A", borderTop: `1px solid ${C.bd}`}}>
                        <td colSpan={10} style={{padding: "12px 18px"}}>
                          <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14}}>
                            <div>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>MODULE KEY</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tx, marginTop: 2}}>{e.module}</div>
                            </div>
                            <div>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>ECU NAME (DECODED)</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tx, marginTop: 2}}>
                                {e.ecu_info?.name || <span style={{color: C.tm}}>—</span>}
                              </div>
                            </div>
                            <div>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>ECU_INFO RAW (12 B)</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tx, marginTop: 2, wordBreak: "break-all"}}>
                                {e.ecu_info?.raw_hex || <span style={{color: C.tm}}>—</span>}
                              </div>
                            </div>
                            <div data-testid={`algo-detail-${e.module}`}>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>ALGORITHM</div>
                              {e.algorithm ? (() => {
                                const fa = friendlyAlgo(e.algorithm);
                                return (
                                  <>
                                    <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tx, marginTop: 2}}>
                                      {fa.label} <span style={{color: C.tm}}>({e.algorithm})</span>
                                    </div>
                                    <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginTop: 4, lineHeight: 1.4}}>
                                      {fa.description}
                                    </div>
                                  </>
                                );
                              })() : (
                                <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tm, marginTop: 2}}>—</div>
                              )}
                            </div>
                            {e.status === "reversed" ? (
                              <div>
                                <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>PYTHON FUNCTION</div>
                                <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: "#1B5E20", marginTop: 2}}>{e.python_function}()</div>
                              </div>
                            ) : (
                              <div style={{gridColumn: "1 / -1"}}>
                                <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>
                                  {e.provenance === "task-634" ? "IMPLEMENTATION" : "WHY DLL-ONLY"}
                                </div>
                                <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tx, marginTop: 2, lineHeight: 1.5}}>{e.reason}</div>
                              </div>
                            )}
                            {e.provenance === "task-634" && e.task634Id && (
                              <div
                                data-testid={`verify-panel-${e.task634Id}`}
                                style={{gridColumn: "1 / -1", marginTop: 4, paddingTop: 10, borderTop: `1px dashed ${C.bd}`}}
                              >
                                <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700, marginBottom: 6}}>
                                  BENCH VERIFICATION
                                </div>
                                <div style={{display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap"}}>
                                  <button
                                    type="button"
                                    data-testid={`verify-btn-${e.task634Id}`}
                                    data-verified={e.verified ? "true" : "false"}
                                    onClick={() => markVerified(e.task634Id, !e.verified)}
                                    style={{
                                      cursor: "pointer",
                                      border: `1.5px solid ${e.verified ? "#1B5E20" : "#E65100"}`,
                                      background: e.verified ? "#1B5E20" : "#fff",
                                      color: e.verified ? "#fff" : "#E65100",
                                      fontFamily: "'Nunito'", fontWeight: 800, fontSize: 11,
                                      letterSpacing: 0.5, padding: "5px 12px", borderRadius: 6,
                                    }}
                                  >
                                    {e.verified ? "✓ Verified — click to unmark" : "Mark verified"}
                                  </button>
                                  <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, lineHeight: 1.4}}>
                                    {e.verified
                                      ? "Bench-confirmed against a real vehicle. Synced to the API server so other benches see the same flag."
                                      : "Flip this once you've run the capability on a real car. Persists across reloads (localStorage + API server)."}
                                  </div>
                                </div>
                              </div>
                            )}
                          </div>
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                );
              })}
              {filtered.length === 0 && (
                <tr>
                  <td colSpan={10} style={{padding: "24px 12px", textAlign: "center", color: C.tm, fontFamily: "'Nunito'"}}>
                    No entries match the current filter.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>

      {/* Extended catalog appendix — asset sweep provenance.
          Always rendered (even when DLL-only is empty) because the UDS
          service / NRC / DID dictionaries are useful on their own and
          replace what used to be hand-maintained in srtlab_uds_errors.py. */}
      {extCatalog && (
        <Card data-testid="asset-sweep-appendix">
          <div style={{display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap", marginBottom: 10}}>
            <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 16, color: C.tx}}>
              Asset sweep appendix
            </div>
            <span style={{
              fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 800,
              padding: "2px 7px", borderRadius: 999,
              background: "#9C27B014", color: "#6A1B9A", letterSpacing: 1,
            }}>provenance: {extCatalog.provenance || "asset_sweep"}</span>
            <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              Re-run with <code style={{padding: "1px 5px", background: "#0001", borderRadius: 3, fontSize: 10}}>pnpm sweep:assets</code>.
            </div>
          </div>

          {/* Extended DLL entries (status: dll_only) — the sweep-side
              delta from `extension_entries`. Currently zero, but when a
              future drop adds a new canflash unlock DLL it shows up here
              without needing to touch the python catalog. */}
          {(() => {
            const sweepDelta = Array.isArray(extCatalog.extension_entries)
              ? extCatalog.extension_entries
              : (Array.isArray(extCatalog.entries) ? extCatalog.entries : []);
            if (sweepDelta.length === 0) return null;
            return (
              <div style={{marginBottom: 14}}>
                <div style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 12, color: C.tx, marginBottom: 6}}>
                  New DLLs found in attached_assets/ ({sweepDelta.length})
                </div>
                <table data-testid="ext-dll-table" style={{width: "100%", borderCollapse: "collapse", fontFamily: "'JetBrains Mono', monospace", fontSize: 11}}>
                  <thead style={{background: "#0000000A"}}>
                    <tr>
                      <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm}}>FILE</th>
                      <th style={{textAlign: "right", padding: "6px 10px", fontSize: 10, color: C.tm}}>SIZE</th>
                      <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm}}>SHA256 (8)</th>
                      <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm}}>WHY</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sweepDelta.map((e) => (
                      <tr key={e.file} style={{borderTop: `1px solid ${C.bd}`}}>
                        <td style={{padding: "6px 10px", color: C.tx}}>{e.file}</td>
                        <td style={{padding: "6px 10px", textAlign: "right", color: C.tm}}>{e.size_bytes}</td>
                        <td style={{padding: "6px 10px", color: C.tm}}>{(e.sha256 || "").slice(0, 8)}…</td>
                        <td style={{padding: "6px 10px", fontFamily: "'Nunito'", fontSize: 11, color: C.tx}}>{e.reason}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            );
          })()}

          <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14}}>
            {extCatalog.uds.services && (
              <UdsCodeList
                title="UDS Services (ISO 14229-1)"
                source={extCatalog.uds.services.sourcePath}
                codes={extCatalog.uds.services.codes}
                testId="uds-services"
              />
            )}
            {extCatalog.uds.negative_response_codes && (
              <UdsCodeList
                title="Negative Response Codes"
                source={extCatalog.uds.negative_response_codes.sourcePath}
                codes={extCatalog.uds.negative_response_codes.codes}
                testId="uds-nrcs"
              />
            )}
            {extCatalog.uds.sessions && (
              <UdsCodeList
                title="Diagnostic Sessions"
                source={extCatalog.uds.sessions.sourcePath}
                codes={extCatalog.uds.sessions.codes}
                testId="uds-sessions"
              />
            )}
          </div>

          {extCatalog.villain_operations && Array.isArray(extCatalog.villain_operations.groups) && extCatalog.villain_operations.groups.length > 0 && (
            <VillainOperations vops={extCatalog.villain_operations}/>
          )}

          {extCatalog.uds.did_maps && extCatalog.uds.did_maps.length > 0 && (
            <div style={{marginTop: 14}}>
              <div style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 12, color: C.tx, marginBottom: 4}}>
                DID maps ({extCatalog.uds.did_maps.length} source files)
              </div>
              <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
                {extCatalog.uds.did_maps.reduce((s, m) => s + (m.count || 0), 0)} DID definitions across the
                AlfaOBD database dumps. Largest:{" "}
                <strong style={{color: C.tx}}>
                  {Math.max(...extCatalog.uds.did_maps.map((m) => m.count || 0))} entries
                </strong>.
              </div>
            </div>
          )}
        </Card>
      )}
    </div>
  );
}

// VILLAIN operations panel — renders the named operation groups extracted
// from VILLAIN_GPEC for Chrysler/FCA ECU programming. Each group is an
// expandable accordion row showing its protocol scope and the underlying
// operations (DID + service byte). The SRI Mileage group flags the 0xE2
// prefix quirk inline so an operator browsing the catalog notices it
// before trying to drive that op.
function VillainOperations({vops}) {
  const [open, setOpen] = useState(() => new Set());
  const toggle = (name) => setOpen((prev) => {
    const next = new Set(prev);
    if (next.has(name)) next.delete(name); else next.add(name);
    return next;
  });
  const totalOps = (vops.groups || []).reduce(
    (s, g) => s + (Array.isArray(g.operations) ? g.operations.length : 0), 0);
  return (
    <div data-testid="villain-operations" style={{marginTop: 14}}>
      <div style={{display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap", marginBottom: 8}}>
        <div style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 13, color: C.tx}}>
          VILLAIN Operations
        </div>
        <span style={{
          fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 800,
          padding: "2px 7px", borderRadius: 999,
          background: "#1B5E2014", color: "#1B5E20", letterSpacing: 1,
        }}>provenance: {vops.provenance || "VILLAIN_GPEC extraction"}</span>
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
          {vops.groups.length} groups · {totalOps} operations
        </div>
      </div>
      {vops.description && (
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginBottom: 8, lineHeight: 1.4}}>
          {vops.description}
        </div>
      )}
      <div style={{display: "flex", flexDirection: "column", gap: 6}}>
        {vops.groups.map((g) => {
          const isOpen = open.has(g.name);
          const isSri = /SRI/i.test(g.name);
          const opCount = Array.isArray(g.operations) ? g.operations.length : 0;
          return (
            <div
              key={g.name}
              data-testid={`villain-group-${g.name}`}
              style={{border: `1px solid ${C.bd}`, borderRadius: 6, background: "#fff"}}
            >
              <button
                type="button"
                data-testid={`villain-group-toggle-${g.name}`}
                onClick={() => toggle(g.name)}
                style={{
                  width: "100%", display: "flex", alignItems: "center", gap: 10,
                  padding: "8px 12px", background: "transparent", border: "none",
                  cursor: "pointer", textAlign: "left",
                }}
              >
                <span style={{
                  fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tm,
                  width: 12, display: "inline-block",
                }}>{isOpen ? "▾" : "▸"}</span>
                <span style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 12, color: C.tx, flex: "0 0 auto"}}>
                  {g.name}
                </span>
                <span
                  data-testid={`villain-protocol-${g.name}`}
                  title={`Protocol scope: ${g.protocol}`}
                  style={{
                    fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 800,
                    padding: "2px 7px", borderRadius: 999, letterSpacing: 0.5,
                    background: "#0D47A114", color: "#0D47A1",
                  }}
                >{g.protocol}</span>
                {isSri && (
                  <span
                    data-testid={`villain-sri-quirk-${g.name}`}
                    title="SRI ops require a 0xE2 prefix byte before the DID"
                    style={{
                      fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 800,
                      padding: "2px 7px", borderRadius: 999, letterSpacing: 0.5,
                      background: "#E6510014", color: "#E65100",
                    }}
                  >⚠ 0xE2 PREFIX REQUIRED</span>
                )}
                <span style={{flex: 1}}/>
                <span style={{
                  fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm,
                  padding: "1px 6px", borderRadius: 999, background: "#0001",
                }}>{opCount} op{opCount === 1 ? "" : "s"}</span>
              </button>
              {isOpen && (
                <div style={{borderTop: `1px solid ${C.bd}`, padding: "8px 12px", background: "#0000000A"}}>
                  {isSri && (
                    <div
                      data-testid={`villain-sri-note-${g.name}`}
                      style={{
                        fontFamily: "'Nunito'", fontSize: 11, color: "#E65100",
                        background: "#FFF3E0", border: "1px solid #E6510040",
                        borderRadius: 4, padding: "6px 10px", marginBottom: 8, lineHeight: 1.4,
                      }}
                    >
                      <strong>SRI quirk:</strong> these ops require a <code style={{fontFamily: "'JetBrains Mono', monospace"}}>0xE2</code> prefix byte sent before the DID. Forgetting it yields an NRC.
                    </div>
                  )}
                  <table style={{width: "100%", borderCollapse: "collapse", fontFamily: "'JetBrains Mono', monospace", fontSize: 10}}>
                    <thead>
                      <tr style={{textAlign: "left", color: C.tm}}>
                        <th style={{padding: "4px 8px", fontSize: 9, letterSpacing: 1}}>OPERATION</th>
                        <th style={{padding: "4px 8px", fontSize: 9, letterSpacing: 1}}>SERVICE</th>
                        <th style={{padding: "4px 8px", fontSize: 9, letterSpacing: 1}}>DID</th>
                        <th style={{padding: "4px 8px", fontSize: 9, letterSpacing: 1}}>NOTES</th>
                      </tr>
                    </thead>
                    <tbody>
                      {(g.operations || []).map((op) => (
                        <tr key={op.id} data-testid={`villain-op-${op.id}`} style={{borderTop: `1px solid ${C.bd}80`}}>
                          <td style={{padding: "4px 8px", color: C.tx}}>
                            <div style={{fontFamily: "'Nunito'", fontWeight: 700, fontSize: 11}}>{op.label}</div>
                            <div style={{fontSize: 9, color: C.tm}}>{op.id}</div>
                          </td>
                          <td style={{padding: "4px 8px", color: op.service ? C.a3 : C.tm, fontWeight: 700}}>
                            {op.service || "—"}
                          </td>
                          <td style={{padding: "4px 8px", color: op.did ? C.tx : C.tm}}>
                            {op.did || "—"}
                            {op.value && <span style={{color: C.tm}}> = {op.value}</span>}
                          </td>
                          <td style={{padding: "4px 8px", color: C.tm, fontFamily: "'Nunito'", fontSize: 10}}>
                            {op.notes || ""}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// Compact UDS code-table renderer used inside the asset-sweep appendix.
// The data shape is `{ "0xNN": "(Name, Description)" | "name" }` straight
// out of the python source — we display it as-is since the value strings
// are already operator-readable.
function UdsCodeList({title, source, codes, testId}) {
  const entries = Object.entries(codes || {}).sort(([a], [b]) =>
    parseInt(a, 16) - parseInt(b, 16));
  return (
    <div data-testid={testId}>
      <div style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 12, color: C.tx, marginBottom: 4}}>
        {title} <span style={{fontWeight: 600, color: C.tm}}>({entries.length})</span>
      </div>
      <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: C.tm, marginBottom: 6, wordBreak: "break-all"}}>
        from {source}
      </div>
      <div style={{maxHeight: 220, overflow: "auto", border: `1px solid ${C.bd}`, borderRadius: 6, background: "#0000000A"}}>
        <table style={{width: "100%", borderCollapse: "collapse", fontFamily: "'JetBrains Mono', monospace", fontSize: 10}}>
          <tbody>
            {entries.map(([code, value]) => (
              <tr key={code} style={{borderTop: `1px solid ${C.bd}80`}}>
                <td style={{padding: "3px 8px", color: C.a3, fontWeight: 700, whiteSpace: "nowrap"}}>{code}</td>
                <td style={{padding: "3px 8px", color: C.tx}}>{value}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
