import React, {useEffect, useMemo, useState} from "react";
import {C} from "../lib/constants.js";
import {Card, Btn} from "../lib/ui.jsx";
import {parseCatalog} from "../lib/unlockCatalogSchema.js";
import {friendlyAlgo} from "../lib/algoFriendly.js";
import {getAuth29Detections, subscribeAuth29, clearAuth29Detections, loadAuth29Detections, getAuth29Unlocks, clearAuth29Unlocks} from "../lib/auth29State.js";
import {useMasterVin} from "../lib/masterVinContext.jsx";

// Task #643 — format a verifiedAt ISO string for the tooltip / panel.
// Falls back to the raw string if parsing fails so the UI never blanks.
function fmtVerifiedAt(iso) {
  if (!iso) return "";
  try {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return iso;
    return d.toLocaleString();
  } catch {
    return String(iso);
  }
}

// Task #643 — single-line provenance summary suitable for a tooltip /
// title attribute. Mirrors what the panel renders so the badge hover
// matches the expanded card.
function verificationTooltip(meta) {
  if (!meta) return "";
  const parts = [];
  if (meta.operator) parts.push(`by ${meta.operator}`);
  if (meta.verifiedAt) parts.push(`on ${fmtVerifiedAt(meta.verifiedAt)}`);
  if (meta.vin) parts.push(`VIN ${meta.vin}`);
  if (meta.notes) parts.push(`notes: ${meta.notes}`);
  return parts.length === 0
    ? "Bench-verified (no operator metadata recorded)"
    : `Verified ${parts.join(" · ")}`;
}

/**
 * Unlock Coverage tab — Task #499.
 *
 * Renders the contents of /unlock_catalog.json (generated by
 * tools/python-bridge/tools/srtlab_unlock_catalog_gen.py and copied at
 * build time by scripts/copy-unlock-catalog.mjs).
 *
 * For every one of the 81 FCA seed→key DLLs we show:
 *   • file name + module key + display name + DLL size
 *   • decoded ecu_info (CAN tx/rx, ECU name, raw 12-byte hex)
 *   • status badge — "REVERSED" (Python port available) or "DLL ONLY"
 *     (must be emulated under Unicorn — reason text included)
 *   • Python function name when reversed
 *   • family tag for grouping
 *
 * Includes a search box, status filter, family filter, and a small
 * coverage banner with the rolled-up reversed/dll_only counts.
 */
function fmtCanId(n) {
  if (n === null || n === undefined) return "—";
  return "0x" + n.toString(16).toUpperCase().padStart(3, "0");
}

function fmtBytes(n) {
  if (!n) return "—";
  if (n < 1024) return `${n} B`;
  return `${(n / 1024).toFixed(1)} KB`;
}

const STATUS_STYLES = {
  reversed: {bg: "#1B5E2010", color: "#1B5E20", label: "NATIVE"},
  dll_only: {bg: "#E65100" + "10", color: "#E65100", label: "DLL ONLY"},
  // Task #641 — task-634 hand-curated rows surface as bench-pending
  // until an operator marks them verified against a real car.
  "bench-pending": {bg: "#E6510010", color: "#E65100", label: "BENCH-PENDING"},
  verified: {bg: "#1B5E2010", color: "#1B5E20", label: "VERIFIED"},
};

function StatusBadge({status, title}) {
  const s = STATUS_STYLES[status] || {bg: "#9E9E9E20", color: "#616161", label: String(status).toUpperCase()};
  return (
    <span
      data-status={status}
      title={title || undefined}
      style={{
        display: "inline-block", padding: "3px 9px", borderRadius: 6,
        background: s.bg, color: s.color, fontFamily: "'Nunito'",
        fontWeight: 900, fontSize: 10, letterSpacing: 1,
        cursor: title ? "help" : "default",
      }}
    >{s.label}</span>
  );
}

// Friendly-label + tooltip copy for algorithm-family tags lives in
// ../lib/algoFriendly.js so the badge in the table cell, the expanded
// details row, and the tests all read from the same source of truth.

function AlgoBadge({algorithm}) {
  if (!algorithm) {
    return <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "#9E9E9E"}}>—</span>;
  }
  const friendly = friendlyAlgo(algorithm);
  const isPlaceholder = !!friendly.placeholder;
  // Placeholders ("unfit", "bitpack", "cummins-style?") get a muted neutral
  // pill so the table reads consistently — they are not real algorithm
  // families, just notes from the underlying coverage data.
  const palette = isPlaceholder
    ? {bg: "#9E9E9E1F", color: "#616161"}
    : {bg: "#0D47A110", color: "#0D47A1"};
  return (
    <span
      data-placeholder={isPlaceholder ? "true" : "false"}
      data-algo-tag={algorithm}
      title={`${friendly.description} (tag: ${algorithm})`}
      style={{
        display: "inline-block", padding: "2px 7px", borderRadius: 4,
        background: palette.bg, color: palette.color,
        fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 700,
        fontStyle: isPlaceholder ? "italic" : "normal",
      }}
    >{friendly.label}</span>
  );
}

// Algorithm-family chip used in the row above the table. Active chips are
// filled; inactive ones are outlined. The "All" chip clears the filter.
function AlgoChip({label, count, active, onClick, testId, title}) {
  return (
    <button
      type="button"
      data-testid={testId}
      data-active={active ? "true" : "false"}
      title={title}
      onClick={onClick}
      style={{
        display: "inline-flex", alignItems: "center", gap: 6,
        padding: "5px 10px", borderRadius: 999, cursor: "pointer",
        border: `1.5px solid ${active ? "#0D47A1" : "#0D47A140"}`,
        background: active ? "#0D47A1" : "#fff",
        color: active ? "#fff" : "#0D47A1",
        fontFamily: "'Nunito'", fontWeight: 800, fontSize: 11, letterSpacing: 0.3,
        transition: "background 0.15s, color 0.15s, border-color 0.15s",
      }}
    >
      <span>{label}</span>
      <span
        data-testid={testId ? `${testId}-count` : undefined}
        style={{
          fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 800,
          padding: "1px 6px", borderRadius: 999,
          background: active ? "#ffffff22" : "#0D47A114",
          color: active ? "#fff" : "#0D47A1",
        }}
      >{count}</span>
    </button>
  );
}

// Convert a URL ?algo=… value back into the canonical algorithm tag used
// in component state. Encoding/decoding is handled by URLSearchParams
// natively — we don't manually encodeURIComponent on the way out, since
// URLSearchParams.set() already does that and stacking the two produces
// double-encoded URLs (e.g. "+" → "%252B") for tags with reserved chars.
function slugToAlgo(slug) {
  if (slug === null || slug === undefined || slug === "") return "all";
  return slug;
}

export default function UnlockCoverageTab() {
  const masterVin = useMasterVin();
  const benchVin = masterVin?.vin || "";
  // Task #643 — last operator name typed into a verify form. Remembered
  // per-browser so the tech doesn't have to retype their initials on
  // every row. Stored as a plain string (no PII guardrails — same as
  // localStorage VIN history elsewhere in the app).
  const [operatorName, setOperatorName] = useState(() => {
    if (typeof window === "undefined") return "";
    try { return window.localStorage.getItem("srtlab.task634.operator.v1") || ""; }
    catch { return ""; }
  });
  const [catalog, setCatalog] = useState(null);
  // Optional extended catalog from tools/asset-sweep (DLLs + UDS tables).
  const [extCatalog, setExtCatalog] = useState(null);
  // Hand-curated task-634 competitor-parity additions (XC2268 RFHUB,
  // Mopar radio codes, dealer-lockout bypass, ZF-8HP TCU). Kept in its
  // own public/task634_entries.json so the asset-sweep regenerator
  // never clobbers the hand edits.
  const [task634, setTask634] = useState(null);
  // Task #641 — which task-634 entry ids have been marked bench-verified.
  // Hydrated from the API server first; falls back to localStorage when
  // the bench is offline. Writes propagate to both so a verification
  // made on one machine shows up on every other bench.
  const [verifiedIds, setVerifiedIds] = useState(() => {
    if (typeof window === "undefined") return new Set();
    try {
      const raw = window.localStorage.getItem("srtlab.task634.verified.v1");
      if (!raw) return new Set();
      const arr = JSON.parse(raw);
      return new Set(Array.isArray(arr) ? arr.filter((x) => typeof x === "string") : []);
    } catch {
      return new Set();
    }
  });
  // Task #643 — full verification metadata keyed by entry id. Holds the
  // operator name, VIN, free-form notes, and verifiedAt timestamp the
  // API returned. Drives both the expanded verify panel and the badge
  // tooltip. localStorage seed runs first so the panel paints with the
  // last known values when the API is offline; the GET refresh below
  // replaces it with the server's view when reachable.
  const [verifications, setVerifications] = useState(() => {
    if (typeof window === "undefined") return {};
    try {
      const raw = window.localStorage.getItem("srtlab.task634.verifications.v1");
      if (!raw) return {};
      const obj = JSON.parse(raw);
      return obj && typeof obj === "object" ? obj : {};
    } catch {
      return {};
    }
  });
  // Which task-634 rows currently have their inline edit form open
  // ("Mark verified" or "Edit" clicked but Save not yet pressed). Map
  // of entryId → {operator, vin, notes} draft so each row remembers
  // what was typed when toggling other rows.
  const [verifyDrafts, setVerifyDrafts] = useState({});
  // Live dispatcher stats; falls back to on-disk catalog counts if offline.
  const [dispatcherStats, setDispatcherStats] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);
  const [q, setQ] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [familyFilter, setFamilyFilter] = useState("all");
  // Active algorithm-family chip; seeded from ?algo=… so shared links open pre-filtered.
  const [algoFilter, setAlgoFilter] = useState(() => {
    if (typeof window === "undefined") return "all";
    try {
      const sp = new URLSearchParams(window.location.search);
      return slugToAlgo(sp.get("algo"));
    } catch {
      return "all";
    }
  });
  const [expanded, setExpanded] = useState(() => new Set());
  // Task #567 — UDS 0x29 detection banner state. Mirrors SeedTab's
  // subscription so a probe firing in either tab lights both up.
  const [auth29, setAuth29] = useState(() => getAuth29Detections());
  const [auth29Ok, setAuth29Ok] = useState(() => getAuth29Unlocks());
  // Task #573 — when set, the table is filtered to only modules whose
  // tx address has a confirmed 0x29 detection on file (server-side or
  // locally cached). Surfaced as a toggle chip in the search row so an
  // operator can pull up "what does this fleet need 0x29 for?" with one
  // click rather than scrolling the catalog.
  const [needs29Only, setNeeds29Only] = useState(false);
  useEffect(() => {
    const refresh = () => { setAuth29(getAuth29Detections()); setAuth29Ok(getAuth29Unlocks()); };
    const off = subscribeAuth29(refresh);
    const onStorage = (e) => { if (!e || e.key === 'srtlab.auth29.detections' || e.key === 'srtlab.auth29.unlocks') refresh(); };
    if (typeof window !== 'undefined') window.addEventListener('storage', onStorage);
    // Task #573 — hydrate from the API so the coverage banner reflects
    // server-side history, not just this browser's localStorage.
    loadAuth29Detections().then(() => refresh()).catch(() => {});
    return () => { off(); if (typeof window !== 'undefined') window.removeEventListener('storage', onStorage); };
  }, []);

  // Set of tx addresses that require 0x29, used by the table column /
  // filter below. Built from `auth29` so it tracks live updates.
  const auth29TxSet = useMemo(() => {
    const s = new Set();
    for (const d of auth29) if (Number.isFinite(d.tx)) s.add(d.tx | 0);
    return s;
  }, [auth29]);

  useEffect(() => {
    let cancelled = false;
    const url = `${import.meta.env.BASE_URL || "/"}unlock_catalog.json`;
    fetch(url, {cache: "no-cache"})
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} loading ${url}`);
        return r.json();
      })
      .then((raw) => {
        if (cancelled) return;
        try {
          const parsed = parseCatalog(raw);
          setCatalog(parsed);
        } catch (e) {
          setError(`Catalog failed schema validation: ${e.message}`);
        }
      })
      .catch((e) => !cancelled && setError(e.message))
      .finally(() => !cancelled && setLoading(false));
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    let cancelled = false;
    const url = `${import.meta.env.BASE_URL || "/"}unlock_catalog_extended.json`;
    fetch(url, {cache: "no-cache"})
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (cancelled || !data) return;
        // Light shape check; the asset-sweep tool guarantees the schema but
        // we keep the UI defensive so a corrupted file doesn't blank the tab.
        if (
          data && typeof data === "object"
          && Array.isArray(data.entries)
          && data.uds && typeof data.uds === "object"
        ) setExtCatalog(data);
      })
      .catch(() => { /* extended catalog is optional */ });
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    let cancelled = false;
    const url = `${import.meta.env.BASE_URL || "/"}task634_entries.json`;
    fetch(url, {cache: "no-cache"})
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (cancelled || !data || typeof data !== "object") return;
        // Defensive shape check — we only merge files that explicitly
        // self-identify as the task-634 hand-curated catalog so a stray
        // fetch returning unlock_catalog.json never gets double-counted.
        if (data.provenance !== "task-634" || !Array.isArray(data.entries)) return;
        setTask634(data);
      })
      .catch(() => { /* hand-curated catalog is optional */ });
    return () => { cancelled = true; };
  }, []);

  // Task #641 — hydrate verifications from the API so a flag set on
  // another bench shows up here. Server is authoritative; if it's
  // reachable we replace the localStorage seed with its view.
  useEffect(() => {
    let cancelled = false;
    fetch("/api/task634-verifications", {cache: "no-cache"})
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (cancelled || !data || !Array.isArray(data.verifications)) return;
        const ids = [];
        const meta = {};
        for (const v of data.verifications) {
          if (!v || typeof v.entryId !== "string") continue;
          ids.push(v.entryId);
          meta[v.entryId] = {
            operator: v.operator ?? null,
            vin: v.vin ?? null,
            notes: v.notes ?? null,
            verifiedAt: v.verifiedAt ?? null,
          };
        }
        setVerifiedIds(new Set(ids));
        setVerifications(meta);
        try {
          window.localStorage.setItem(
            "srtlab.task634.verified.v1",
            JSON.stringify(ids),
          );
          window.localStorage.setItem(
            "srtlab.task634.verifications.v1",
            JSON.stringify(meta),
          );
        } catch { /* storage is best-effort */ }
      })
      .catch(() => { /* server is optional — localStorage seed stands */ });
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/unlock-coverage/stats", {cache: "no-cache"})
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} from /api/unlock-coverage/stats`);
        return r.json();
      })
      .then((data) => {
        if (cancelled) return;
        // Light validation; full validation is enforced server-side by Zod.
        if (
          data && typeof data === "object"
          && typeof data.native_count === "number"
          && typeof data.emulated_count === "number"
          && typeof data.entry_count === "number"
        ) {
          setDispatcherStats(data);
        }
      })
      .catch((e) => {
        if (!cancelled) {
          console.warn(
            "unlock-coverage stats endpoint unavailable; falling back to catalog counts:",
            e.message,
          );
        }
      });
    return () => { cancelled = true; };
  }, []);

  // Sweep-only delta promoted to canonical-row shape; empty when the sweep
  // adds no new DLLs. Prefer `extension_entries` to avoid double-counting
  // the canonical 81 rows that `entries` (the superset) also contains.
  // Declared before `mergedEntries` so the TDZ doesn't trip useMemo's
  // dependency capture (would otherwise throw "Cannot access 'extEntries'
  // before initialization" on first render).
  const extEntries = useMemo(() => {
    if (!extCatalog) return [];
    const sweepDelta = Array.isArray(extCatalog.extension_entries)
      ? extCatalog.extension_entries
      : (Array.isArray(extCatalog.entries) ? extCatalog.entries : []);
    return sweepDelta.map((e) => ({
      file: e.file,
      module: `ext_${e.file}`,
      display_name: e.file.replace(/\.dll$/i, ""),
      family: "asset_sweep",
      algorithm: null,
      tx_can_id: null,
      rx_can_id: null,
      ecu_info: null,
      size_bytes: e.size_bytes,
      status: e.status || "dll_only",
      python_function: null,
      reason: e.reason,
      provenance: e.provenance || extCatalog.provenance || "asset_sweep",
    }));
  }, [extCatalog]);

  // Hand-curated task-634 entries kept in raw shape. These bench-tool
  // capabilities live in their own collapsible "Competitor-parity
  // additions" card below the main coverage table (task #640) so they
  // do not get rolled into the DLL coverage percentage, the family
  // dropdown, the algorithm chips, or the "Showing X of Y" counter.
  // Rebase resolution (task #640 + #641): keep raw entries (task #640's
  // separate card consumes them directly) and annotate each one with a
  // `verified` flag derived from #641's verifiedIds set so the dedicated
  // Task634Row can flip its badge between BENCH-PENDING and VERIFIED.
  const task634Entries = useMemo(() => {
    if (!task634 || !Array.isArray(task634.entries)) return [];
    return task634.entries.map((e) => ({...e, verified: verifiedIds.has(e.id)}));
  }, [task634, verifiedIds]);

  // Computed from merged rows so families/algoCounts/totals stay
  // consistent when the asset-sweep extension contributes new entries.
  // Task-634 hand-curated additions intentionally live outside this
  // merge so the DLL-catalog coverage stats stay clean.
  const mergedEntries = useMemo(
    () => (catalog ? [...catalog.entries, ...extEntries] : []),
    [catalog, extEntries],
  );

  const families = useMemo(() => {
    const set = new Set(mergedEntries.map((e) => e.family));
    return Array.from(set).sort();
  }, [mergedEntries]);

  const algoCounts = useMemo(() => {
    const m = new Map();
    for (const e of mergedEntries) {
      if (!e.algorithm) continue;
      m.set(e.algorithm, (m.get(e.algorithm) || 0) + 1);
    }
    return Array.from(m.entries())
      .map(([algorithm, count]) => ({algorithm, count}))
      .sort((a, b) => b.count - a.count || a.algorithm.localeCompare(b.algorithm));
  }, [mergedEntries]);

  // Keep the URL in sync with the active chip so the filter is shareable.
  // Uses replaceState (not pushState) so chip clicks don't pollute browser
  // history. Skipped on the server / when there is no window.
  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const sp = new URLSearchParams(window.location.search);
      const current = sp.get("algo") || "";
      const next = algoFilter === "all" ? "" : algoFilter;
      if (current === next) return;
      if (next) sp.set("algo", next); else sp.delete("algo");
      const qs = sp.toString();
      const newUrl = window.location.pathname
        + (qs ? `?${qs}` : "")
        + (window.location.hash || "");
      window.history.replaceState(null, "", newUrl);
    } catch {
      // URL bookkeeping is best-effort; never break the UI over it.
    }
  }, [algoFilter]);

  const filtered = useMemo(() => {
    if (!catalog) return [];
    const term = q.trim().toLowerCase();
    return mergedEntries.filter((e) => {
      if (statusFilter !== "all" && e.status !== statusFilter) return false;
      if (familyFilter !== "all" && e.family !== familyFilter) return false;
      if (algoFilter !== "all" && e.algorithm !== algoFilter) return false;
      if (needs29Only && !auth29TxSet.has(e.tx_can_id | 0)) return false;
      if (!term) return true;
      const blob = `${e.file} ${e.module} ${e.display_name} ${e.family} ${e.python_function || ""} ${e.algorithm || ""} ${e.ecu_info?.name || ""}`.toLowerCase();
      return blob.includes(term);
    });
  }, [catalog, q, statusFilter, familyFilter, algoFilter, mergedEntries, needs29Only, auth29TxSet]);

  // Quick count for the filter chip — how many catalog entries match a
  // tx address that we've confirmed (locally or server-side) requires
  // 0x29. Computed off mergedEntries so the asset-sweep delta is
  // included on equal footing.
  const needs29Count = useMemo(
    () => mergedEntries.filter((e) => auth29TxSet.has(e.tx_can_id | 0)).length,
    [mergedEntries, auth29TxSet],
  );

  // Task #641 + #643 — record (or un-record) a bench verification for a
  // task-634 entry. Optimistically flips local state + localStorage so
  // the badge and verify panel update instantly, then mirrors the call
  // to the API server. The server response (with its authoritative
  // verifiedAt timestamp) replaces the optimistic metadata when it
  // arrives so the panel never drifts from what was persisted.
  function verifyEntry(entryId, {operator, vin, notes}) {
    const cleanOperator = (operator || "").trim() || null;
    const cleanVin = (vin || "").toUpperCase().replace(/\s+/g, "") || null;
    const cleanNotes = (notes || "").trim() || null;
    const verifiedAt = new Date().toISOString();
    const meta = {operator: cleanOperator, vin: cleanVin, notes: cleanNotes, verifiedAt};

    // Persist the operator name for next time so the tech doesn't retype it.
    if (cleanOperator) {
      setOperatorName(cleanOperator);
      try { window.localStorage.setItem("srtlab.task634.operator.v1", cleanOperator); }
      catch { /* best-effort */ }
    }

    setVerifiedIds((prev) => {
      const next = new Set(prev);
      next.add(entryId);
      try {
        window.localStorage.setItem(
          "srtlab.task634.verified.v1",
          JSON.stringify(Array.from(next)),
        );
      } catch { /* storage is best-effort */ }
      return next;
    });
    setVerifications((prev) => {
      const next = {...prev, [entryId]: meta};
      try {
        window.localStorage.setItem(
          "srtlab.task634.verifications.v1",
          JSON.stringify(next),
        );
      } catch { /* storage is best-effort */ }
      return next;
    });
    // Close any open draft form for this row — Save just took effect.
    setVerifyDrafts((prev) => {
      if (!(entryId in prev)) return prev;
      const next = {...prev};
      delete next[entryId];
      return next;
    });

    fetch("/api/task634-verifications", {
      method: "POST",
      headers: {"Content-Type": "application/json"},
      body: JSON.stringify({
        entryId,
        operator: cleanOperator,
        vin: cleanVin,
        notes: cleanNotes,
      }),
    })
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        // Replace the optimistic verifiedAt with the server-issued one.
        if (!data || !data.verification) return;
        const v = data.verification;
        setVerifications((prev) => {
          const next = {
            ...prev,
            [entryId]: {
              operator: v.operator ?? null,
              vin: v.vin ?? null,
              notes: v.notes ?? null,
              verifiedAt: v.verifiedAt ?? verifiedAt,
            },
          };
          try {
            window.localStorage.setItem(
              "srtlab.task634.verifications.v1",
              JSON.stringify(next),
            );
          } catch { /* storage is best-effort */ }
          return next;
        });
      })
      .catch(() => { /* offline → optimistic state stands */ });
  }

  function clearVerification(entryId) {
    setVerifiedIds((prev) => {
      const next = new Set(prev);
      next.delete(entryId);
      try {
        window.localStorage.setItem(
          "srtlab.task634.verified.v1",
          JSON.stringify(Array.from(next)),
        );
      } catch { /* storage is best-effort */ }
      return next;
    });
    setVerifications((prev) => {
      if (!(entryId in prev)) return prev;
      const next = {...prev};
      delete next[entryId];
      try {
        window.localStorage.setItem(
          "srtlab.task634.verifications.v1",
          JSON.stringify(next),
        );
      } catch { /* storage is best-effort */ }
      return next;
    });
    fetch(`/api/task634-verifications/${encodeURIComponent(entryId)}`, {
      method: "DELETE",
    }).catch(() => { /* offline → localStorage holds the line */ });
  }

  function openVerifyDraft(entryId) {
    const existing = verifications[entryId] || {};
    setVerifyDrafts((prev) => ({
      ...prev,
      [entryId]: {
        operator: existing.operator || operatorName || "",
        vin: existing.vin || benchVin || "",
        notes: existing.notes || "",
      },
    }));
  }

  function closeVerifyDraft(entryId) {
    setVerifyDrafts((prev) => {
      if (!(entryId in prev)) return prev;
      const next = {...prev};
      delete next[entryId];
      return next;
    });
  }

  function updateVerifyDraft(entryId, patch) {
    setVerifyDrafts((prev) => ({
      ...prev,
      [entryId]: {...(prev[entryId] || {}), ...patch},
    }));
  }

  function toggle(module) {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(module)) next.delete(module); else next.add(module);
      return next;
    });
  }

  if (loading) {
    return <Card><div style={{color: C.tm, fontFamily: "'Nunito'", padding: 12}}>Loading unlock catalog…</div></Card>;
  }
  if (error) {
    return (
      <Card>
        <div style={{color: C.sr, fontFamily: "'Nunito'", fontWeight: 800, marginBottom: 6}}>
          Unable to load unlock_catalog.json
        </div>
        <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tm, whiteSpace: "pre-wrap"}}>{error}</div>
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginTop: 10}}>
          Regenerate with: <code style={{background: "#0001", padding: "1px 4px", borderRadius: 3}}>python3 tools/python-bridge/tools/srtlab_unlock_catalog_gen.py</code>
        </div>
      </Card>
    );
  }
  if (!catalog) return null;

  // Prefer the live dispatcher view; fall back to catalog static fields
  // when the /api/unlock-coverage/stats endpoint is unavailable. The two
  // are kept in sync by test_native_count_matches_catalog_reversed in the
  // python-bridge tests, so under normal operation they agree.
  const statsSource = dispatcherStats ? "dispatcher" : "catalog";
  const nativeCount = dispatcherStats
    ? dispatcherStats.native_count
    : catalog.reversed_count;
  const emulatedCount = dispatcherStats
    ? dispatcherStats.emulated_count
    : catalog.dll_only_count;
  const totalCount = dispatcherStats
    ? dispatcherStats.entry_count
    : catalog.entry_count;
  const pctReversed = totalCount > 0
    ? Math.round((nativeCount / totalCount) * 100)
    : 0;
  const fullyNative = totalCount > 0
    && emulatedCount === 0
    && nativeCount === totalCount;
  const algoFamilyCount = dispatcherStats?.algo_family_count ?? new Set(
    catalog.entries.map((e) => e.algorithm).filter(Boolean),
  ).size;

  return (
    <div data-testid="unlock-coverage-tab" style={{display: "flex", flexDirection: "column", gap: 14}}>
      {auth29Ok.length > 0 && (
        <Card data-testid="auth29-unlocked-banner" style={{background: "#E8F5E9", borderColor: "#1B5E20"}}>
          <div style={{display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12}}>
            <div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, fontWeight: 900, color: "#1B5E20", letterSpacing: 1, marginBottom: 4}}>UDS 0x29 UNLOCKED</div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tx, marginBottom: 4}}>
                {auth29Ok.length === 1 ? "A module" : `${auth29Ok.length} modules`} on this bench unlocked via the UDS 0x29 Authentication challenge/response handshake.
              </div>
              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm}}>
                {auth29Ok.map(d => `tx=0x${(d.tx >>> 0).toString(16).toUpperCase().padStart(3, "0")}${d.label ? ` (${d.label})` : ""}${d.statusInfo != null ? ` · statusInfo 0x${d.statusInfo.toString(16).toUpperCase().padStart(2, "0")}` : ""}`).join(" · ")}
              </div>
            </div>
            <button onClick={clearAuth29Unlocks} data-testid="auth29-unlocked-banner-clear" style={{cursor: "pointer", border: "1.5px solid #1B5E20", padding: "4px 10px", borderRadius: 6, background: "#fff", color: "#1B5E20", fontWeight: 800, fontSize: 10, letterSpacing: 1, whiteSpace: "nowrap"}}>DISMISS</button>
          </div>
        </Card>
      )}
      {auth29.length > 0 && (
        <Card data-testid="auth29-banner" style={{background: "#FFF3E0", borderColor: "#E65100"}}>
          <div style={{display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12}}>
            <div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, fontWeight: 900, color: "#E65100", letterSpacing: 1, marginBottom: 4}}>UDS 0x29 DETECTED</div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tx, marginBottom: 4}}>
                {auth29.length === 1 ? "A module" : `${auth29.length} modules`} on this bench answered the 0x29 probe — they require Authentication (0x29) instead of SecurityAccess (0x27). The unlock catalog below cannot drive {auth29.length === 1 ? "it" : "them"} until 0x29 is implemented.
              </div>
              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm}}>
                {auth29.map(d => `tx=0x${(d.tx >>> 0).toString(16).toUpperCase().padStart(3, "0")}${d.label ? ` (${d.label})` : ""}${d.nrc != null ? ` · seed NRC 0x${d.nrc.toString(16).toUpperCase().padStart(2, "0")}` : ""}`).join(" · ")}
              </div>
            </div>
            <button onClick={clearAuth29Detections} data-testid="auth29-banner-clear" style={{cursor: "pointer", border: "1.5px solid #E65100", padding: "4px 10px", borderRadius: 6, background: "#fff", color: "#E65100", fontWeight: 800, fontSize: 10, letterSpacing: 1, whiteSpace: "nowrap"}}>DISMISS</button>
          </div>
        </Card>
      )}
      {fullyNative && (
        <Card glow data-testid="all-native-banner" data-stats-source={statsSource} style={{
          background: "linear-gradient(90deg, #1B5E2010, #43A04710)",
          borderColor: "#1B5E20",
        }}>
          <div style={{display: "flex", flexWrap: "wrap", gap: 14, alignItems: "center"}}>
            <div style={{
              fontFamily: "'JetBrains Mono', monospace", fontWeight: 900,
              fontSize: 16, color: "#1B5E20", letterSpacing: 1,
              padding: "4px 10px", border: "2px solid #1B5E20", borderRadius: 6,
            }}>100% NATIVE</div>
            <div style={{flex: 1, minWidth: 220}}>
              <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 16, color: C.tx}}>
                Every FCA unlock now runs as a pure-Python port — zero Unicorn fallback.
              </div>
              <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tm, marginTop: 2}}>
                <span data-testid="native-count">{nativeCount}</span> / {totalCount} modules native ·{" "}
                <span data-testid="emulated-count">{emulatedCount}</span> emulated · spans{" "}
                <span data-testid="algo-family-count">{algoFamilyCount}</span> algorithm families
              </div>
              <div data-testid="stats-source" style={{
                fontFamily: "'JetBrains Mono', monospace", fontSize: 10,
                color: C.tm, marginTop: 4, letterSpacing: 0.5,
              }}>source: {statsSource === "dispatcher"
                ? "live python dispatcher"
                : "catalog (dispatcher offline — using cached counts)"}</div>
            </div>
          </div>
        </Card>
      )}

      <Card glow>
        <div style={{display: "flex", flexWrap: "wrap", gap: 18, alignItems: "baseline"}}>
          <div>
            <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 22, color: C.tx}}>Unlock Coverage</div>
            <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tm, marginTop: 2}}>
              FCA seed→key DLL catalog · schema v{catalog.schema_version}
            </div>
          </div>
          <div style={{flex: 1}}/>
          <div style={{textAlign: "right"}} data-testid="coverage-header" data-stats-source={statsSource}>
            <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 28, fontWeight: 800, color: C.tx, letterSpacing: -0.5}}>
              <span data-testid="reversed-count">{nativeCount}</span>
              <span style={{color: C.tm, fontSize: 18, fontWeight: 700}}> / </span>
              <span data-testid="total-count">{totalCount}</span>
            </div>
            <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              native Python ports · {pctReversed}% coverage ·{" "}
              <span data-testid="dll-only-count">{emulatedCount}</span> emulated
            </div>
          </div>
        </div>
        <div style={{height: 10, background: "#0000000A", borderRadius: 5, overflow: "hidden", marginTop: 14}}>
          <div style={{
            width: `${pctReversed}%`, height: "100%",
            background: `linear-gradient(90deg, #1B5E20, #43A047)`, transition: "width 0.4s",
          }}/>
        </div>
      </Card>

      <Card>
        <div style={{display: "flex", flexWrap: "wrap", gap: 10, alignItems: "center"}}>
          <input
            type="search"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search file, module, display name, family, function…"
            data-testid="catalog-search"
            style={{
              flex: "1 1 280px", padding: "9px 12px", borderRadius: 8,
              border: `1.5px solid ${C.bd}`, fontFamily: "'Nunito'", fontSize: 12,
              background: "#fff", color: C.tx,
            }}
          />
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            data-testid="status-filter"
            style={{padding: "9px 10px", borderRadius: 8, border: `1.5px solid ${C.bd}`, fontFamily: "'Nunito'", fontSize: 12, background: "#fff", color: C.tx}}
          >
            <option value="all">All statuses</option>
            <option value="reversed">Reversed only</option>
            <option value="dll_only">DLL only</option>
          </select>
          <select
            value={familyFilter}
            onChange={(e) => setFamilyFilter(e.target.value)}
            data-testid="family-filter"
            style={{padding: "9px 10px", borderRadius: 8, border: `1.5px solid ${C.bd}`, fontFamily: "'Nunito'", fontSize: 12, background: "#fff", color: C.tx}}
          >
            <option value="all">All families</option>
            {families.map((f) => <option key={f} value={f}>{f}</option>)}
          </select>
          <button
            type="button"
            data-testid="needs-29-filter"
            data-active={needs29Only ? "true" : "false"}
            onClick={() => setNeeds29Only((v) => !v)}
            disabled={auth29TxSet.size === 0}
            title={auth29TxSet.size === 0
              ? "No 0x29 detections recorded yet — flag one from the bench to enable this filter"
              : `Show only modules whose tx address has a confirmed 0x29 detection (${needs29Count} match)`}
            style={{
              padding: "8px 12px", borderRadius: 8, cursor: auth29TxSet.size === 0 ? "not-allowed" : "pointer",
              border: `1.5px solid ${needs29Only ? "#E65100" : (auth29TxSet.size === 0 ? C.bd : "#E6510080")}`,
              background: needs29Only ? "#E65100" : "#fff",
              color: needs29Only ? "#fff" : (auth29TxSet.size === 0 ? C.tm : "#E65100"),
              fontFamily: "'Nunito'", fontWeight: 800, fontSize: 11, letterSpacing: 0.5,
              opacity: auth29TxSet.size === 0 ? 0.55 : 1, whiteSpace: "nowrap",
            }}
          >
            Needs 0x29
            <span data-testid="needs-29-filter-count" style={{
              marginLeft: 6, fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 800,
              padding: "1px 6px", borderRadius: 999,
              background: needs29Only ? "#ffffff22" : "#E6510014",
              color: needs29Only ? "#fff" : "#E65100",
            }}>{needs29Count}</span>
          </button>
          <Btn outline onClick={() => { setQ(""); setStatusFilter("all"); setFamilyFilter("all"); setAlgoFilter("all"); setNeeds29Only(false); }}>Reset</Btn>
        </div>
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginTop: 10}}>
          Showing <strong style={{color: C.tx}}>{filtered.length}</strong> of {mergedEntries.length} entries
        </div>
      </Card>

      {algoCounts.length > 0 && (
        <Card data-testid="algo-chip-row">
          <div style={{display: "flex", alignItems: "baseline", gap: 10, marginBottom: 10, flexWrap: "wrap"}}>
            <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 13, color: C.tx, letterSpacing: 0.3}}>
              Algorithm family
            </div>
            <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              {algoFilter === "all"
                ? `${algoCounts.length} families across ${algoCounts.reduce((s, x) => s + x.count, 0)} modules — pick one to filter`
                : <>Filtering by <strong style={{color: C.tx}}>{friendlyAlgo(algoFilter).label}</strong> — click again or “All” to clear</>}
            </div>
          </div>
          <div style={{display: "flex", flexWrap: "wrap", gap: 8}}>
            <AlgoChip
              label="All"
              count={algoCounts.reduce((s, x) => s + x.count, 0)}
              active={algoFilter === "all"}
              onClick={() => setAlgoFilter("all")}
              testId="algo-chip-all"
              title="Show every algorithm family"
            />
            {algoCounts.map(({algorithm, count}) => {
              const f = friendlyAlgo(algorithm);
              return (
                <AlgoChip
                  key={algorithm}
                  label={f.label}
                  count={count}
                  active={algoFilter === algorithm}
                  onClick={() => setAlgoFilter((cur) => cur === algorithm ? "all" : algorithm)}
                  testId={`algo-chip-${algorithm}`}
                  title={`${f.description} (tag: ${algorithm})`}
                />
              );
            })}
          </div>
        </Card>
      )}

      <Card style={{padding: 0, overflow: "hidden"}}>
        <div style={{overflowX: "auto"}}>
          <table style={{width: "100%", borderCollapse: "collapse", fontFamily: "'Nunito'", fontSize: 12}}>
            <thead>
              <tr style={{background: "#0000000A", textAlign: "left"}}>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>FILE</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>DISPLAY NAME</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>FAMILY</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>ALGO</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>TX</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>RX</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>SIZE</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>STATUS</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}>0x29</th>
                <th style={{padding: "10px 12px", fontSize: 10, letterSpacing: 1, color: C.tm}}></th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((e) => {
                const open = expanded.has(e.module);
                return (
                  <React.Fragment key={e.module}>
                    <tr data-testid={`row-${e.module}`} data-provenance={e.provenance || "catalog"} style={{borderTop: `1px solid ${C.bd}`, background: open ? "#0000000A" : "transparent"}}>
                      <td style={{padding: "10px 12px", fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tx}}>
                        {e.file}
                        {e.provenance === "asset_sweep" && (
                          <span data-testid={`provenance-chip-${e.module}`} title="Surfaced by tools/asset-sweep — re-run with `pnpm sweep:assets`" style={{
                            marginLeft: 8, fontFamily: "'JetBrains Mono', monospace",
                            fontSize: 8, fontWeight: 800, letterSpacing: 1,
                            padding: "1px 5px", borderRadius: 3,
                            background: "#9C27B014", color: "#6A1B9A",
                          }}>SWEEP</span>
                        )}
                      </td>
                      <td style={{padding: "10px 12px", color: C.tx}}>{e.display_name}</td>
                      <td style={{padding: "10px 12px"}}>
                        <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm, background: "#0001", padding: "2px 6px", borderRadius: 4}}>{e.family}</span>
                      </td>
                      <td style={{padding: "10px 12px"}} data-testid={`algo-${e.module}`}>
                        <AlgoBadge algorithm={e.algorithm}/>
                      </td>
                      <td style={{padding: "10px 12px", fontFamily: "'JetBrains Mono', monospace", color: C.tx}}>{fmtCanId(e.tx_can_id)}</td>
                      <td style={{padding: "10px 12px", fontFamily: "'JetBrains Mono', monospace", color: C.tx}}>{fmtCanId(e.rx_can_id)}</td>
                      <td style={{padding: "10px 12px", color: C.tm}}>{fmtBytes(e.size_bytes)}</td>
                      <td style={{padding: "10px 12px"}}>
                        <StatusBadge
                          status={e.status}
                          title={
                            e.status === "verified" && e.task634Id
                              ? verificationTooltip(verifications[e.task634Id])
                              : undefined
                          }
                        />
                      </td>
                      <td style={{padding: "10px 12px"}} data-testid={`auth29-cell-${e.module}`}>
                        {auth29TxSet.has(e.tx_can_id | 0) ? (
                          <span
                            data-testid={`auth29-required-${e.module}`}
                            title="Confirmed 0x29 detection on this tx address"
                            style={{
                              display: "inline-block", padding: "3px 8px", borderRadius: 6,
                              background: "#E6510014", color: "#E65100",
                              fontFamily: "'JetBrains Mono', monospace",
                              fontWeight: 900, fontSize: 10, letterSpacing: 1,
                            }}
                          >REQ 0x29</span>
                        ) : (
                          <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm}}>—</span>
                        )}
                      </td>
                      <td style={{padding: "10px 12px", textAlign: "right"}}>
                        <button
                          onClick={() => toggle(e.module)}
                          data-testid={`toggle-${e.module}`}
                          style={{
                            background: "transparent", border: `1px solid ${C.bd}`,
                            color: C.tm, fontFamily: "'Nunito'", fontWeight: 700,
                            fontSize: 10, padding: "4px 10px", borderRadius: 6, cursor: "pointer",
                          }}
                        >{open ? "Hide" : "Details"}</button>
                      </td>
                    </tr>
                    {open && (
                      <tr style={{background: "#0000000A", borderTop: `1px solid ${C.bd}`}}>
                        <td colSpan={10} style={{padding: "12px 18px"}}>
                          <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14}}>
                            <div>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>MODULE KEY</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tx, marginTop: 2}}>{e.module}</div>
                            </div>
                            <div>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>ECU NAME (DECODED)</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tx, marginTop: 2}}>
                                {e.ecu_info?.name || <span style={{color: C.tm}}>—</span>}
                              </div>
                            </div>
                            <div>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>ECU_INFO RAW (12 B)</div>
                              <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tx, marginTop: 2, wordBreak: "break-all"}}>
                                {e.ecu_info?.raw_hex || <span style={{color: C.tm}}>—</span>}
                              </div>
                            </div>
                            <div data-testid={`algo-detail-${e.module}`}>
                              <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>ALGORITHM</div>
                              {e.algorithm ? (() => {
                                const fa = friendlyAlgo(e.algorithm);
                                return (
                                  <>
                                    <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tx, marginTop: 2}}>
                                      {fa.label} <span style={{color: C.tm}}>({e.algorithm})</span>
                                    </div>
                                    <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginTop: 4, lineHeight: 1.4}}>
                                      {fa.description}
                                    </div>
                                  </>
                                );
                              })() : (
                                <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: C.tm, marginTop: 2}}>—</div>
                              )}
                            </div>
                            {e.status === "reversed" ? (
                              <div>
                                <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>PYTHON FUNCTION</div>
                                <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: "#1B5E20", marginTop: 2}}>{e.python_function}()</div>
                              </div>
                            ) : (
                              <div style={{gridColumn: "1 / -1"}}>
                                <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>
                                  {e.provenance === "task-634" ? "IMPLEMENTATION" : "WHY DLL-ONLY"}
                                </div>
                                <div style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tx, marginTop: 2, lineHeight: 1.5}}>{e.reason}</div>
                              </div>
                            )}
                            {e.provenance === "task-634" && e.task634Id && (
                              <VerifyPanel
                                entryId={e.task634Id}
                                verified={e.verified}
                                meta={verifications[e.task634Id]}
                                draft={verifyDrafts[e.task634Id]}
                                benchVin={benchVin}
                                lastOperator={operatorName}
                                onOpenDraft={openVerifyDraft}
                                onCloseDraft={closeVerifyDraft}
                                onUpdateDraft={updateVerifyDraft}
                                onSave={verifyEntry}
                                onClear={clearVerification}
                              />
                            )}
                          </div>
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                );
              })}
              {filtered.length === 0 && (
                <tr>
                  <td colSpan={10} style={{padding: "24px 12px", textAlign: "center", color: C.tm, fontFamily: "'Nunito'"}}>
                    No entries match the current filter.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>

      {task634Entries.length > 0 && (
        <Task634Card
          entries={task634Entries}
          verifications={verifications}
          verifyDrafts={verifyDrafts}
          benchVin={benchVin}
          operatorName={operatorName}
          onOpenDraft={openVerifyDraft}
          onCloseDraft={closeVerifyDraft}
          onUpdateDraft={updateVerifyDraft}
          onSave={verifyEntry}
          onClear={clearVerification}
        />
      )}

      {/* Task #646 — single-screen audit log of every bench verification
          recorded for the task-634 capabilities. Pulls from the same
          verifications state the per-row VerifyPanel writes to, joined
          with the task634 entry labels so a shop owner can scan a week
          of bench work in one place and export it for billing. */}
      <VerificationsLogCard
        verifications={verifications}
        task634Entries={task634Entries}
      />

      {/* Extended catalog appendix — asset sweep provenance.
          Always rendered (even when DLL-only is empty) because the UDS
          service / NRC / DID dictionaries are useful on their own and
          replace what used to be hand-maintained in srtlab_uds_errors.py. */}
      {extCatalog && (
        <Card data-testid="asset-sweep-appendix">
          <div style={{display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap", marginBottom: 10}}>
            <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 16, color: C.tx}}>
              Asset sweep appendix
            </div>
            <span style={{
              fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 800,
              padding: "2px 7px", borderRadius: 999,
              background: "#9C27B014", color: "#6A1B9A", letterSpacing: 1,
            }}>provenance: {extCatalog.provenance || "asset_sweep"}</span>
            <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              Re-run with <code style={{padding: "1px 5px", background: "#0001", borderRadius: 3, fontSize: 10}}>pnpm sweep:assets</code>.
            </div>
          </div>

          {/* Extended DLL entries (status: dll_only) — the sweep-side
              delta from `extension_entries`. Currently zero, but when a
              future drop adds a new canflash unlock DLL it shows up here
              without needing to touch the python catalog. */}
          {(() => {
            const sweepDelta = Array.isArray(extCatalog.extension_entries)
              ? extCatalog.extension_entries
              : (Array.isArray(extCatalog.entries) ? extCatalog.entries : []);
            if (sweepDelta.length === 0) return null;
            return (
              <div style={{marginBottom: 14}}>
                <div style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 12, color: C.tx, marginBottom: 6}}>
                  New DLLs found in attached_assets/ ({sweepDelta.length})
                </div>
                <table data-testid="ext-dll-table" style={{width: "100%", borderCollapse: "collapse", fontFamily: "'JetBrains Mono', monospace", fontSize: 11}}>
                  <thead style={{background: "#0000000A"}}>
                    <tr>
                      <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm}}>FILE</th>
                      <th style={{textAlign: "right", padding: "6px 10px", fontSize: 10, color: C.tm}}>SIZE</th>
                      <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm}}>SHA256 (8)</th>
                      <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm}}>WHY</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sweepDelta.map((e) => (
                      <tr key={e.file} style={{borderTop: `1px solid ${C.bd}`}}>
                        <td style={{padding: "6px 10px", color: C.tx}}>{e.file}</td>
                        <td style={{padding: "6px 10px", textAlign: "right", color: C.tm}}>{e.size_bytes}</td>
                        <td style={{padding: "6px 10px", color: C.tm}}>{(e.sha256 || "").slice(0, 8)}…</td>
                        <td style={{padding: "6px 10px", fontFamily: "'Nunito'", fontSize: 11, color: C.tx}}>{e.reason}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            );
          })()}

          <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14}}>
            {extCatalog.uds.services && (
              <UdsCodeList
                title="UDS Services (ISO 14229-1)"
                source={extCatalog.uds.services.sourcePath}
                codes={extCatalog.uds.services.codes}
                testId="uds-services"
              />
            )}
            {extCatalog.uds.negative_response_codes && (
              <UdsCodeList
                title="Negative Response Codes"
                source={extCatalog.uds.negative_response_codes.sourcePath}
                codes={extCatalog.uds.negative_response_codes.codes}
                testId="uds-nrcs"
              />
            )}
            {extCatalog.uds.sessions && (
              <UdsCodeList
                title="Diagnostic Sessions"
                source={extCatalog.uds.sessions.sourcePath}
                codes={extCatalog.uds.sessions.codes}
                testId="uds-sessions"
              />
            )}
          </div>

          {extCatalog.villain_operations && Array.isArray(extCatalog.villain_operations.groups) && extCatalog.villain_operations.groups.length > 0 && (
            <VillainOperations vops={extCatalog.villain_operations}/>
          )}

          {extCatalog.uds.did_maps && extCatalog.uds.did_maps.length > 0 && (
            <div style={{marginTop: 14}}>
              <div style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 12, color: C.tx, marginBottom: 4}}>
                DID maps ({extCatalog.uds.did_maps.length} source files)
              </div>
              <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
                {extCatalog.uds.did_maps.reduce((s, m) => s + (m.count || 0), 0)} DID definitions across the
                AlfaOBD database dumps. Largest:{" "}
                <strong style={{color: C.tx}}>
                  {Math.max(...extCatalog.uds.did_maps.map((m) => m.count || 0))} entries
                </strong>.
              </div>
            </div>
          )}
        </Card>
      )}
    </div>
  );
}

// Competitor-parity additions card (task #640 + #643). Renders the
// hand-curated task-634 bench-tool entries in their own collapsible
// section with a count badge, so they show up at a glance without being
// merged into the DLL coverage table or its rollup stats. Each entry
// exposes its lib/UI source paths as clickable links so an operator can
// jump straight from the catalog to the implementation file, and embeds
// the task #643 VerifyPanel behind a per-row Details toggle so the full
// operator / VIN / notes provenance can be captured against the same
// entries that live in this dedicated card.
function Task634Card({
  entries, verifications, verifyDrafts, benchVin, operatorName,
  onOpenDraft, onCloseDraft, onUpdateDraft, onSave, onClear,
}) {
  const [open, setOpen] = useState(true);
  return (
    <Card data-testid="task634-card">
      <div style={{display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap"}}>
        <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 16, color: C.tx}}>
          Competitor-parity additions
        </div>
        <span
          data-testid="task634-count"
          style={{
            fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 800,
            letterSpacing: 1, padding: "2px 7px", borderRadius: 999,
            background: "#D32F2F14", color: "#B71C1C",
          }}
        >{entries.length} {entries.length === 1 ? "ENTRY" : "ENTRIES"}</span>
        <span style={{
          fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 800,
          padding: "2px 7px", borderRadius: 999,
          background: "#D32F2F14", color: "#B71C1C", letterSpacing: 1,
        }}>provenance: task-634</span>
        <div style={{flex: 1}}/>
        <button
          type="button"
          data-testid="task634-toggle"
          onClick={() => setOpen((v) => !v)}
          style={{
            background: "transparent", border: `1px solid ${C.bd}`, color: C.tm,
            fontFamily: "'Nunito'", fontWeight: 700, fontSize: 10, letterSpacing: 1,
            padding: "4px 10px", borderRadius: 6, cursor: "pointer",
          }}
        >{open ? "HIDE" : "SHOW"}</button>
      </div>
      <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginTop: 6, lineHeight: 1.4}}>
        Bench-tool capabilities that ship outside the FCA seed→key DLL pipeline.
        Tracked separately so they do not skew the headline DLL coverage percentage above.
      </div>
      {open && (
        <div style={{marginTop: 12, display: "flex", flexDirection: "column", gap: 8}}>
          {entries.map((e) => (
            <Task634Row
              key={e.id}
              entry={e}
              meta={verifications?.[e.id]}
              draft={verifyDrafts?.[e.id]}
              benchVin={benchVin}
              operatorName={operatorName}
              onOpenDraft={onOpenDraft}
              onCloseDraft={onCloseDraft}
              onUpdateDraft={onUpdateDraft}
              onSave={onSave}
              onClear={onClear}
            />
          ))}
        </div>
      )}
    </Card>
  );
}

function Task634Row({
  entry, meta, draft, benchVin, operatorName,
  onOpenDraft, onCloseDraft, onUpdateDraft, onSave, onClear,
}) {
  const [open, setOpen] = useState(false);
  const verified = !!entry.verified;
  return (
    <div
      data-testid={`task634-row-${entry.id}`}
      data-provenance="task-634"
      style={{
        border: `1px solid ${C.bd}`, borderRadius: 8, padding: "10px 12px",
        background: "#fff",
      }}
    >
      <div style={{display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap"}}>
        <div style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 13, color: C.tx}}>
          {entry.label || entry.id}
        </div>
        {entry.category && (
          <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm, background: "#0001", padding: "2px 6px", borderRadius: 4}}>
            {entry.category}
          </span>
        )}
        {entry.algorithm && (
          <span style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "#0D47A1", background: "#0D47A114", padding: "2px 6px", borderRadius: 4}}>
            {entry.algorithm}
          </span>
        )}
        {/* Rebase resolution (task #641 + #643): bench-verified lifecycle
            badge with a tooltip echoing the operator / when / VIN /
            notes provenance captured by the task #643 verify panel. */}
        <StatusBadge
          status={verified ? "verified" : "bench-pending"}
          title={verified ? verificationTooltip(meta) : undefined}
        />
        <div style={{flex: 1}}/>
        <button
          type="button"
          data-testid={`toggle-task634_${entry.id}`}
          onClick={() => setOpen((v) => !v)}
          style={{
            background: "transparent", border: `1px solid ${C.bd}`,
            color: C.tm, fontFamily: "'Nunito'", fontWeight: 700,
            fontSize: 10, padding: "4px 10px", borderRadius: 6, cursor: "pointer",
          }}
        >{open ? "Hide" : "Details"}</button>
      </div>
      {(entry.lib || entry.ui) && (
        <div style={{marginTop: 8, display: "flex", flexWrap: "wrap", gap: 14, fontFamily: "'JetBrains Mono', monospace", fontSize: 11}}>
          {entry.lib && (
            <div>
              <span style={{color: C.tm, fontWeight: 700, letterSpacing: 0.5}}>lib: </span>
              <a
                data-testid={`task634-lib-${entry.id}`}
                href={`/${entry.lib}`}
                target="_blank"
                rel="noopener noreferrer"
                title={`Open ${entry.lib}`}
                style={{color: "#0D47A1", textDecoration: "underline"}}
              >{entry.lib}</a>
            </div>
          )}
          {entry.ui && (
            <div>
              <span style={{color: C.tm, fontWeight: 700, letterSpacing: 0.5}}>ui: </span>
              <a
                data-testid={`task634-ui-${entry.id}`}
                href={`/${entry.ui}`}
                target="_blank"
                rel="noopener noreferrer"
                title={`Open ${entry.ui}`}
                style={{color: "#0D47A1", textDecoration: "underline"}}
              >{entry.ui}</a>
            </div>
          )}
        </div>
      )}
      {open && (
        <VerifyPanel
          entryId={entry.id}
          verified={verified}
          meta={meta}
          draft={draft}
          benchVin={benchVin}
          lastOperator={operatorName}
          onOpenDraft={onOpenDraft}
          onCloseDraft={onCloseDraft}
          onUpdateDraft={onUpdateDraft}
          onSave={onSave}
          onClear={onClear}
        />
      )}
    </div>
  );
}

// Task #643 — bench-verification panel for a single task-634 entry.
// Renders one of three states:
//   1. Not verified, draft closed → "Mark verified" button + hint copy.
//   2. Draft open (verifying or editing) → operator / VIN / notes form.
//   3. Verified, draft closed → who-verified-it / when / VIN / notes
//      summary + Edit / Unmark buttons.
function VerifyPanel({
  entryId, verified, meta, draft,
  benchVin, lastOperator,
  onOpenDraft, onCloseDraft, onUpdateDraft, onSave, onClear,
}) {
  const isEditing = !!draft;
  const operatorVal = draft?.operator ?? "";
  const vinVal = draft?.vin ?? "";
  const notesVal = draft?.notes ?? "";
  const canSave = operatorVal.trim().length > 0;
  const inputStyle = {
    fontFamily: "'JetBrains Mono', monospace", fontSize: 11,
    padding: "5px 8px", border: `1px solid ${C.bd}`, borderRadius: 4,
    background: "#fff", color: C.tx, width: "100%", boxSizing: "border-box",
  };
  const labelStyle = {
    fontSize: 9, color: C.tm, letterSpacing: 1, fontWeight: 700,
    marginBottom: 3, fontFamily: "'Nunito'",
  };
  return (
    <div
      data-testid={`verify-panel-${entryId}`}
      style={{gridColumn: "1 / -1", marginTop: 4, paddingTop: 10, borderTop: `1px dashed ${C.bd}`}}
    >
      <div style={{display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: 8, marginBottom: 8, flexWrap: "wrap"}}>
        <div style={{fontSize: 10, color: C.tm, letterSpacing: 1, fontWeight: 700}}>
          BENCH VERIFICATION
        </div>
        {verified && meta?.verifiedAt && !isEditing && (
          <div
            data-testid={`verify-summary-${entryId}`}
            style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}
          >
            verified <span data-testid={`verify-when-${entryId}`} style={{color: C.tx, fontWeight: 700}}>{fmtVerifiedAt(meta.verifiedAt)}</span>
            {meta.operator && (
              <>
                {" by "}
                <span data-testid={`verify-operator-${entryId}`} style={{color: C.tx, fontWeight: 700}}>{meta.operator}</span>
              </>
            )}
            {meta.vin && (
              <>
                {" against VIN "}
                <span data-testid={`verify-vin-${entryId}`} style={{fontFamily: "'JetBrains Mono', monospace", color: C.tx, fontWeight: 700}}>{meta.vin}</span>
              </>
            )}
          </div>
        )}
      </div>

      {!isEditing && !verified && (
        <div style={{display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap"}}>
          <button
            type="button"
            data-testid={`verify-btn-${entryId}`}
            data-verified="false"
            onClick={() => onOpenDraft(entryId)}
            style={{
              cursor: "pointer",
              border: "1.5px solid #E65100", background: "#fff", color: "#E65100",
              fontFamily: "'Nunito'", fontWeight: 800, fontSize: 11,
              letterSpacing: 0.5, padding: "5px 12px", borderRadius: 6,
            }}
          >Mark verified</button>
          <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, lineHeight: 1.4}}>
            Flip this once you've run the capability on a real car. Records who / when / which VIN so other techs can see the provenance.
          </div>
        </div>
      )}

      {!isEditing && verified && (
        <div style={{display: "flex", flexDirection: "column", gap: 8}}>
          {meta?.notes && (
            <div
              data-testid={`verify-notes-${entryId}`}
              style={{
                fontFamily: "'Nunito'", fontSize: 11, color: C.tx,
                background: "#1B5E2010", border: "1px solid #1B5E2040",
                borderRadius: 4, padding: "6px 10px", lineHeight: 1.4,
                whiteSpace: "pre-wrap",
              }}
            >
              <span style={{fontWeight: 800, color: "#1B5E20", marginRight: 6, letterSpacing: 0.5}}>NOTES:</span>
              {meta.notes}
            </div>
          )}
          <div style={{display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap"}}>
            <button
              type="button"
              data-testid={`verify-btn-${entryId}`}
              data-verified="true"
              onClick={() => onOpenDraft(entryId)}
              style={{
                cursor: "pointer",
                border: "1.5px solid #1B5E20", background: "#1B5E20", color: "#fff",
                fontFamily: "'Nunito'", fontWeight: 800, fontSize: 11,
                letterSpacing: 0.5, padding: "5px 12px", borderRadius: 6,
              }}
            >✓ Verified — edit</button>
            <button
              type="button"
              data-testid={`verify-unmark-${entryId}`}
              onClick={() => onClear(entryId)}
              style={{
                cursor: "pointer",
                border: `1px solid ${C.bd}`, background: "transparent", color: C.tm,
                fontFamily: "'Nunito'", fontWeight: 700, fontSize: 11,
                padding: "5px 10px", borderRadius: 6,
              }}
            >Unmark</button>
            {!meta?.operator && (
              <span style={{fontFamily: "'Nunito'", fontSize: 11, color: "#E65100", fontStyle: "italic"}}>
                (no operator recorded — click Edit to add)
              </span>
            )}
          </div>
        </div>
      )}

      {isEditing && (
        <form
          data-testid={`verify-form-${entryId}`}
          onSubmit={(ev) => {
            ev.preventDefault();
            if (!canSave) return;
            onSave(entryId, {operator: operatorVal, vin: vinVal, notes: notesVal});
          }}
          style={{display: "flex", flexDirection: "column", gap: 8}}
        >
          <div style={{display: "grid", gridTemplateColumns: "minmax(160px, 1fr) minmax(160px, 1fr)", gap: 10}}>
            <div>
              <div style={labelStyle}>OPERATOR <span style={{color: "#E65100"}}>*</span></div>
              <input
                type="text"
                data-testid={`verify-operator-input-${entryId}`}
                value={operatorVal}
                placeholder={lastOperator ? `e.g. ${lastOperator}` : "tech initials / name"}
                onChange={(ev) => onUpdateDraft(entryId, {operator: ev.target.value})}
                maxLength={120}
                style={inputStyle}
                autoFocus
              />
            </div>
            <div>
              <div style={labelStyle}>VIN</div>
              <input
                type="text"
                data-testid={`verify-vin-input-${entryId}`}
                value={vinVal}
                placeholder={benchVin || "17-char VIN (optional)"}
                onChange={(ev) => onUpdateDraft(entryId, {vin: ev.target.value.toUpperCase()})}
                maxLength={17}
                spellCheck={false}
                style={inputStyle}
              />
            </div>
          </div>
          <div>
            <div style={labelStyle}>NOTES (optional)</div>
            <textarea
              data-testid={`verify-notes-input-${entryId}`}
              value={notesVal}
              placeholder="Anything worth flagging for the next tech — caveats, vehicle, NRC seen, etc."
              onChange={(ev) => onUpdateDraft(entryId, {notes: ev.target.value})}
              rows={2}
              maxLength={2000}
              style={{...inputStyle, fontFamily: "'Nunito'", resize: "vertical", minHeight: 44}}
            />
          </div>
          <div style={{display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap"}}>
            <button
              type="submit"
              data-testid={`verify-save-${entryId}`}
              disabled={!canSave}
              style={{
                cursor: canSave ? "pointer" : "not-allowed",
                border: "1.5px solid #1B5E20",
                background: canSave ? "#1B5E20" : "#1B5E2040",
                color: "#fff",
                fontFamily: "'Nunito'", fontWeight: 800, fontSize: 11,
                letterSpacing: 0.5, padding: "5px 12px", borderRadius: 6,
                opacity: canSave ? 1 : 0.7,
              }}
            >{verified ? "Update verification" : "Save verification"}</button>
            <button
              type="button"
              data-testid={`verify-cancel-${entryId}`}
              onClick={() => onCloseDraft(entryId)}
              style={{
                cursor: "pointer",
                border: `1px solid ${C.bd}`, background: "transparent", color: C.tm,
                fontFamily: "'Nunito'", fontWeight: 700, fontSize: 11,
                padding: "5px 10px", borderRadius: 6,
              }}
            >Cancel</button>
            {!canSave && (
              <span style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, fontStyle: "italic"}}>
                Operator is required so we can audit who confirmed the unlock.
              </span>
            )}
          </div>
        </form>
      )}
    </div>
  );
}

// VILLAIN operations panel — renders the named operation groups extracted
// from VILLAIN_GPEC for Chrysler/FCA ECU programming. Each group is an
// expandable accordion row showing its protocol scope and the underlying
// operations (DID + service byte). The SRI Mileage group flags the 0xE2
// prefix quirk inline so an operator browsing the catalog notices it
// before trying to drive that op.
function VillainOperations({vops}) {
  const [open, setOpen] = useState(() => new Set());
  const toggle = (name) => setOpen((prev) => {
    const next = new Set(prev);
    if (next.has(name)) next.delete(name); else next.add(name);
    return next;
  });
  const totalOps = (vops.groups || []).reduce(
    (s, g) => s + (Array.isArray(g.operations) ? g.operations.length : 0), 0);
  return (
    <div data-testid="villain-operations" style={{marginTop: 14}}>
      <div style={{display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap", marginBottom: 8}}>
        <div style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 13, color: C.tx}}>
          VILLAIN Operations
        </div>
        <span style={{
          fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 800,
          padding: "2px 7px", borderRadius: 999,
          background: "#1B5E2014", color: "#1B5E20", letterSpacing: 1,
        }}>provenance: {vops.provenance || "VILLAIN_GPEC extraction"}</span>
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
          {vops.groups.length} groups · {totalOps} operations
        </div>
      </div>
      {vops.description && (
        <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginBottom: 8, lineHeight: 1.4}}>
          {vops.description}
        </div>
      )}
      <div style={{display: "flex", flexDirection: "column", gap: 6}}>
        {vops.groups.map((g) => {
          const isOpen = open.has(g.name);
          const isSri = /SRI/i.test(g.name);
          const opCount = Array.isArray(g.operations) ? g.operations.length : 0;
          return (
            <div
              key={g.name}
              data-testid={`villain-group-${g.name}`}
              style={{border: `1px solid ${C.bd}`, borderRadius: 6, background: "#fff"}}
            >
              <button
                type="button"
                data-testid={`villain-group-toggle-${g.name}`}
                onClick={() => toggle(g.name)}
                style={{
                  width: "100%", display: "flex", alignItems: "center", gap: 10,
                  padding: "8px 12px", background: "transparent", border: "none",
                  cursor: "pointer", textAlign: "left",
                }}
              >
                <span style={{
                  fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: C.tm,
                  width: 12, display: "inline-block",
                }}>{isOpen ? "▾" : "▸"}</span>
                <span style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 12, color: C.tx, flex: "0 0 auto"}}>
                  {g.name}
                </span>
                <span
                  data-testid={`villain-protocol-${g.name}`}
                  title={`Protocol scope: ${g.protocol}`}
                  style={{
                    fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 800,
                    padding: "2px 7px", borderRadius: 999, letterSpacing: 0.5,
                    background: "#0D47A114", color: "#0D47A1",
                  }}
                >{g.protocol}</span>
                {isSri && (
                  <span
                    data-testid={`villain-sri-quirk-${g.name}`}
                    title="SRI ops require a 0xE2 prefix byte before the DID"
                    style={{
                      fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 800,
                      padding: "2px 7px", borderRadius: 999, letterSpacing: 0.5,
                      background: "#E6510014", color: "#E65100",
                    }}
                  >⚠ 0xE2 PREFIX REQUIRED</span>
                )}
                <span style={{flex: 1}}/>
                <span style={{
                  fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.tm,
                  padding: "1px 6px", borderRadius: 999, background: "#0001",
                }}>{opCount} op{opCount === 1 ? "" : "s"}</span>
              </button>
              {isOpen && (
                <div style={{borderTop: `1px solid ${C.bd}`, padding: "8px 12px", background: "#0000000A"}}>
                  {isSri && (
                    <div
                      data-testid={`villain-sri-note-${g.name}`}
                      style={{
                        fontFamily: "'Nunito'", fontSize: 11, color: "#E65100",
                        background: "#FFF3E0", border: "1px solid #E6510040",
                        borderRadius: 4, padding: "6px 10px", marginBottom: 8, lineHeight: 1.4,
                      }}
                    >
                      <strong>SRI quirk:</strong> these ops require a <code style={{fontFamily: "'JetBrains Mono', monospace"}}>0xE2</code> prefix byte sent before the DID. Forgetting it yields an NRC.
                    </div>
                  )}
                  <table style={{width: "100%", borderCollapse: "collapse", fontFamily: "'JetBrains Mono', monospace", fontSize: 10}}>
                    <thead>
                      <tr style={{textAlign: "left", color: C.tm}}>
                        <th style={{padding: "4px 8px", fontSize: 9, letterSpacing: 1}}>OPERATION</th>
                        <th style={{padding: "4px 8px", fontSize: 9, letterSpacing: 1}}>SERVICE</th>
                        <th style={{padding: "4px 8px", fontSize: 9, letterSpacing: 1}}>DID</th>
                        <th style={{padding: "4px 8px", fontSize: 9, letterSpacing: 1}}>NOTES</th>
                      </tr>
                    </thead>
                    <tbody>
                      {(g.operations || []).map((op) => (
                        <tr key={op.id} data-testid={`villain-op-${op.id}`} style={{borderTop: `1px solid ${C.bd}80`}}>
                          <td style={{padding: "4px 8px", color: C.tx}}>
                            <div style={{fontFamily: "'Nunito'", fontWeight: 700, fontSize: 11}}>{op.label}</div>
                            <div style={{fontSize: 9, color: C.tm}}>{op.id}</div>
                          </td>
                          <td style={{padding: "4px 8px", color: op.service ? C.a3 : C.tm, fontWeight: 700}}>
                            {op.service || "—"}
                          </td>
                          <td style={{padding: "4px 8px", color: op.did ? C.tx : C.tm}}>
                            {op.did || "—"}
                            {op.value && <span style={{color: C.tm}}> = {op.value}</span>}
                          </td>
                          <td style={{padding: "4px 8px", color: C.tm, fontFamily: "'Nunito'", fontSize: 10}}>
                            {op.notes || ""}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// Task #646 — single-screen audit log of every bench verification.
//
// Joins the live `verifications` map (keyed by entryId — written by the
// per-row VerifyPanel and hydrated from /api/task634-verifications) with
// the task-634 entry labels so each row shows the human-readable
// capability name instead of just the slug. Filtering happens client-side
// (operator dropdown, VIN dropdown, free-text notes search) so a shop
// owner can scan a week's worth of bench work without round-tripping the
// server. CSV export honors the active filter so the downloaded report
// matches what's on screen.
function VerificationsLogCard({verifications, task634Entries}) {
  const [operatorFilter, setOperatorFilter] = useState("all");
  const [vinFilter, setVinFilter] = useState("all");
  const [notesQ, setNotesQ] = useState("");
  // Date range filter — inclusive on both ends. Inputs are HTML date
  // strings (YYYY-MM-DD) interpreted in the user's local timezone so
  // "May 18" means the operator's local May 18, not UTC.
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");

  // Convert a local YYYY-MM-DD string into a numeric ms timestamp at the
  // start (00:00:00.000) or end (23:59:59.999) of that local day. Returns
  // null for an empty / malformed string so callers can short-circuit.
  function localDayBounds(ymd, edge) {
    if (!ymd) return null;
    const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(ymd);
    if (!m) return null;
    const y = Number(m[1]); const mo = Number(m[2]) - 1; const d = Number(m[3]);
    const dt = edge === "end"
      ? new Date(y, mo, d, 23, 59, 59, 999)
      : new Date(y, mo, d, 0, 0, 0, 0);
    const t = dt.getTime();
    return Number.isFinite(t) ? t : null;
  }

  function fmtLocalYmd(date) {
    const y = date.getFullYear();
    const mo = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");
    return `${y}-${mo}-${d}`;
  }
  function applyPresetToday() {
    const today = fmtLocalYmd(new Date());
    setFromDate(today); setToDate(today);
  }
  function applyPresetThisWeek() {
    // Week = Monday → Sunday in the operator's local timezone. JS getDay
    // returns 0 (Sun)…6 (Sat), so shift so Monday is index 0.
    const now = new Date();
    const dow = (now.getDay() + 6) % 7;
    const monday = new Date(now.getFullYear(), now.getMonth(), now.getDate() - dow);
    const sunday = new Date(monday.getFullYear(), monday.getMonth(), monday.getDate() + 6);
    setFromDate(fmtLocalYmd(monday)); setToDate(fmtLocalYmd(sunday));
  }
  function applyPresetThisMonth() {
    const now = new Date();
    const first = new Date(now.getFullYear(), now.getMonth(), 1);
    const last = new Date(now.getFullYear(), now.getMonth() + 1, 0);
    setFromDate(fmtLocalYmd(first)); setToDate(fmtLocalYmd(last));
  }

  // Index task-634 entries by id so we can resolve a friendly capability
  // label for each verification row. Falls back to the raw entryId when
  // the verification references a row that's been removed from the
  // hand-curated catalog (defensive — should not happen in practice).
  const labelById = useMemo(() => {
    const m = new Map();
    for (const e of task634Entries || []) {
      if (e && typeof e.id === "string") m.set(e.id, e.label || e.id);
    }
    return m;
  }, [task634Entries]);

  // Flatten the verifications dict into an array of rows sorted by
  // verifiedAt desc. Rows missing a verifiedAt sort last so they don't
  // jump to the top with epoch-0 NaN comparisons.
  const rows = useMemo(() => {
    const out = [];
    for (const [entryId, meta] of Object.entries(verifications || {})) {
      if (!meta) continue;
      out.push({
        entryId,
        capability: labelById.get(entryId) || entryId,
        operator: meta.operator || "",
        vin: meta.vin || "",
        notes: meta.notes || "",
        verifiedAt: meta.verifiedAt || "",
      });
    }
    out.sort((a, b) => {
      const ta = a.verifiedAt ? Date.parse(a.verifiedAt) : -Infinity;
      const tb = b.verifiedAt ? Date.parse(b.verifiedAt) : -Infinity;
      return tb - ta;
    });
    return out;
  }, [verifications, labelById]);

  // Distinct operator + VIN values for the filter dropdowns. Sorted
  // case-insensitively so the dropdown reads alphabetically regardless
  // of how the tech typed their initials.
  const operators = useMemo(() => {
    const s = new Set();
    for (const r of rows) if (r.operator) s.add(r.operator);
    return Array.from(s).sort((a, b) => a.localeCompare(b, undefined, {sensitivity: "base"}));
  }, [rows]);
  const vins = useMemo(() => {
    const s = new Set();
    for (const r of rows) if (r.vin) s.add(r.vin);
    return Array.from(s).sort();
  }, [rows]);

  const fromTs = useMemo(() => localDayBounds(fromDate, "start"), [fromDate]);
  const toTs = useMemo(() => localDayBounds(toDate, "end"), [toDate]);

  const filtered = useMemo(() => {
    const term = notesQ.trim().toLowerCase();
    return rows.filter((r) => {
      if (operatorFilter !== "all" && r.operator !== operatorFilter) return false;
      if (vinFilter !== "all" && r.vin !== vinFilter) return false;
      if (term && !r.notes.toLowerCase().includes(term)) return false;
      if (fromTs !== null || toTs !== null) {
        // Rows missing a timestamp can't satisfy a date filter — exclude
        // them so the count + CSV stay consistent with what's visible.
        const t = r.verifiedAt ? Date.parse(r.verifiedAt) : NaN;
        if (!Number.isFinite(t)) return false;
        if (fromTs !== null && t < fromTs) return false;
        if (toTs !== null && t > toTs) return false;
      }
      return true;
    });
  }, [rows, operatorFilter, vinFilter, notesQ, fromTs, toTs]);

  const hasActiveFilter =
    operatorFilter !== "all" || vinFilter !== "all" || notesQ || fromDate || toDate;

  function exportCsv() {
    // RFC 4180-ish CSV: wrap every field in double quotes, escape embedded
    // quotes by doubling them. Keeps newlines inside notes intact since the
    // surrounding quotes make that legal.
    const esc = (v) => `"${String(v ?? "").replace(/"/g, '""')}"`;
    const header = ["verifiedAt", "operator", "vin", "capability", "entryId", "notes"];
    const lines = [header.map(esc).join(",")];
    for (const r of filtered) {
      lines.push([
        r.verifiedAt, r.operator, r.vin, r.capability, r.entryId, r.notes,
      ].map(esc).join(","));
    }
    const csv = lines.join("\r\n");
    if (typeof window === "undefined" || typeof document === "undefined") return;
    try {
      const blob = new Blob([csv], {type: "text/csv;charset=utf-8"});
      const url = URL.createObjectURL(blob);
      const stamp = new Date().toISOString().replace(/[:.]/g, "-");
      const a = document.createElement("a");
      a.href = url;
      a.download = `bench-verifications-${stamp}.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      // Defer revoke so Safari finishes the download dialog before we
      // pull the rug out from under the blob URL.
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch {
      /* download is best-effort */
    }
  }

  const hasAny = rows.length > 0;
  const inputStyle = {
    fontFamily: "'Nunito'", fontSize: 11,
    padding: "5px 8px", border: `1px solid ${C.bd}`, borderRadius: 4,
    background: "#fff", color: C.tx,
  };

  return (
    <Card data-testid="verifications-log-card">
      <div style={{display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap", marginBottom: 8}}>
        <div style={{fontFamily: "'Nunito'", fontWeight: 900, fontSize: 16, color: C.tx}}>
          Verifications log
        </div>
        <span
          data-testid="verifications-log-count"
          style={{
            fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 800,
            letterSpacing: 1, padding: "2px 7px", borderRadius: 999,
            background: "#1B5E2014", color: "#1B5E20",
          }}
        >{filtered.length} of {rows.length}</span>
        <div style={{flex: 1}}/>
        <button
          type="button"
          data-testid="verifications-log-export"
          onClick={exportCsv}
          disabled={filtered.length === 0}
          style={{
            cursor: filtered.length === 0 ? "not-allowed" : "pointer",
            border: "1.5px solid #0D47A1",
            background: filtered.length === 0 ? "#0D47A140" : "#0D47A1",
            color: "#fff", fontFamily: "'Nunito'", fontWeight: 800,
            fontSize: 11, letterSpacing: 0.5, padding: "5px 12px",
            borderRadius: 6, opacity: filtered.length === 0 ? 0.7 : 1,
          }}
        >Export CSV</button>
      </div>
      <div style={{fontFamily: "'Nunito'", fontSize: 11, color: C.tm, marginBottom: 10, lineHeight: 1.4}}>
        Chronological audit of every bench verification recorded for the competitor-parity capabilities — operator, VIN, capability, when, free-form notes. Filter or search, then export CSV for compliance / billing.
      </div>

      {!hasAny && (
        <div
          data-testid="verifications-log-empty"
          style={{fontFamily: "'Nunito'", fontSize: 12, color: C.tm, padding: "12px 8px", fontStyle: "italic"}}
        >
          No verifications recorded yet. Mark a capability verified in the Competitor-parity additions card above and it will show up here.
        </div>
      )}

      {hasAny && (
        <>
          <div style={{display: "flex", flexWrap: "wrap", gap: 10, marginBottom: 10, alignItems: "center"}}>
            <label style={{display: "flex", alignItems: "center", gap: 6, fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              Operator
              <select
                data-testid="verifications-log-operator"
                value={operatorFilter}
                onChange={(ev) => setOperatorFilter(ev.target.value)}
                style={inputStyle}
              >
                <option value="all">All ({operators.length})</option>
                {operators.map((op) => (
                  <option key={op} value={op}>{op}</option>
                ))}
              </select>
            </label>
            <label style={{display: "flex", alignItems: "center", gap: 6, fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              VIN
              <select
                data-testid="verifications-log-vin"
                value={vinFilter}
                onChange={(ev) => setVinFilter(ev.target.value)}
                style={inputStyle}
              >
                <option value="all">All ({vins.length})</option>
                {vins.map((v) => (
                  <option key={v} value={v}>{v}</option>
                ))}
              </select>
            </label>
            <input
              type="search"
              data-testid="verifications-log-search"
              value={notesQ}
              onChange={(ev) => setNotesQ(ev.target.value)}
              placeholder="Search notes…"
              style={{...inputStyle, flex: 1, minWidth: 180, fontFamily: "'Nunito'"}}
            />
            {hasActiveFilter && (
              <button
                type="button"
                data-testid="verifications-log-clear"
                onClick={() => {
                  setOperatorFilter("all"); setVinFilter("all"); setNotesQ("");
                  setFromDate(""); setToDate("");
                }}
                style={{
                  cursor: "pointer", border: `1px solid ${C.bd}`,
                  background: "transparent", color: C.tm,
                  fontFamily: "'Nunito'", fontWeight: 700, fontSize: 10,
                  letterSpacing: 1, padding: "5px 10px", borderRadius: 6,
                }}
              >CLEAR</button>
            )}
          </div>

          <div style={{display: "flex", flexWrap: "wrap", gap: 10, marginBottom: 10, alignItems: "center"}}>
            <label style={{display: "flex", alignItems: "center", gap: 6, fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              From
              <input
                type="date"
                data-testid="verifications-log-from"
                value={fromDate}
                max={toDate || undefined}
                onChange={(ev) => setFromDate(ev.target.value)}
                style={inputStyle}
              />
            </label>
            <label style={{display: "flex", alignItems: "center", gap: 6, fontFamily: "'Nunito'", fontSize: 11, color: C.tm}}>
              To
              <input
                type="date"
                data-testid="verifications-log-to"
                value={toDate}
                min={fromDate || undefined}
                onChange={(ev) => setToDate(ev.target.value)}
                style={inputStyle}
              />
            </label>
            <div style={{display: "flex", gap: 4, alignItems: "center"}}>
              {[
                {id: "today", label: "Today", apply: applyPresetToday},
                {id: "week", label: "This week", apply: applyPresetThisWeek},
                {id: "month", label: "This month", apply: applyPresetThisMonth},
              ].map((p) => (
                <button
                  key={p.id}
                  type="button"
                  data-testid={`verifications-log-preset-${p.id}`}
                  onClick={p.apply}
                  style={{
                    cursor: "pointer", border: `1px solid ${C.bd}`,
                    background: "transparent", color: C.tx,
                    fontFamily: "'Nunito'", fontWeight: 700, fontSize: 10,
                    letterSpacing: 0.5, padding: "5px 8px", borderRadius: 6,
                  }}
                >{p.label}</button>
              ))}
            </div>
          </div>

          <div style={{overflowX: "auto", border: `1px solid ${C.bd}`, borderRadius: 6}}>
            <table data-testid="verifications-log-table" style={{width: "100%", borderCollapse: "collapse", fontFamily: "'Nunito'", fontSize: 11}}>
              <thead style={{background: "#0000000A"}}>
                <tr>
                  <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm, letterSpacing: 1}}>WHEN</th>
                  <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm, letterSpacing: 1}}>OPERATOR</th>
                  <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm, letterSpacing: 1}}>VIN</th>
                  <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm, letterSpacing: 1}}>CAPABILITY</th>
                  <th style={{textAlign: "left", padding: "6px 10px", fontSize: 10, color: C.tm, letterSpacing: 1}}>NOTES</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((r) => (
                  <tr
                    key={r.entryId}
                    data-testid={`verifications-log-row-${r.entryId}`}
                    style={{borderTop: `1px solid ${C.bd}`}}
                  >
                    <td style={{padding: "6px 10px", color: C.tx, whiteSpace: "nowrap", fontFamily: "'JetBrains Mono', monospace", fontSize: 10}}>
                      {fmtVerifiedAt(r.verifiedAt)}
                    </td>
                    <td style={{padding: "6px 10px", color: C.tx, fontWeight: 700}}>
                      {r.operator || <span style={{color: C.tm, fontStyle: "italic", fontWeight: 400}}>—</span>}
                    </td>
                    <td style={{padding: "6px 10px", color: C.tx, fontFamily: "'JetBrains Mono', monospace", fontSize: 10}}>
                      {r.vin || <span style={{color: C.tm, fontStyle: "italic", fontFamily: "'Nunito'"}}>—</span>}
                    </td>
                    <td style={{padding: "6px 10px", color: C.tx}}>
                      {r.capability}
                      <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: C.tm}}>{r.entryId}</div>
                    </td>
                    <td style={{padding: "6px 10px", color: C.tx, whiteSpace: "pre-wrap", lineHeight: 1.4}}>
                      {r.notes || <span style={{color: C.tm, fontStyle: "italic"}}>—</span>}
                    </td>
                  </tr>
                ))}
                {filtered.length === 0 && (
                  <tr>
                    <td
                      colSpan={5}
                      data-testid="verifications-log-no-match"
                      style={{padding: "16px 10px", textAlign: "center", color: C.tm, fontStyle: "italic"}}
                    >
                      No verifications match the current filter.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </>
      )}
    </Card>
  );
}

// Compact UDS code-table renderer used inside the asset-sweep appendix.
// The data shape is `{ "0xNN": "(Name, Description)" | "name" }` straight
// out of the python source — we display it as-is since the value strings
// are already operator-readable.
function UdsCodeList({title, source, codes, testId}) {
  const entries = Object.entries(codes || {}).sort(([a], [b]) =>
    parseInt(a, 16) - parseInt(b, 16));
  return (
    <div data-testid={testId}>
      <div style={{fontFamily: "'Nunito'", fontWeight: 800, fontSize: 12, color: C.tx, marginBottom: 4}}>
        {title} <span style={{fontWeight: 600, color: C.tm}}>({entries.length})</span>
      </div>
      <div style={{fontFamily: "'JetBrains Mono', monospace", fontSize: 9, color: C.tm, marginBottom: 6, wordBreak: "break-all"}}>
        from {source}
      </div>
      <div style={{maxHeight: 220, overflow: "auto", border: `1px solid ${C.bd}`, borderRadius: 6, background: "#0000000A"}}>
        <table style={{width: "100%", borderCollapse: "collapse", fontFamily: "'JetBrains Mono', monospace", fontSize: 10}}>
          <tbody>
            {entries.map(([code, value]) => (
              <tr key={code} style={{borderTop: `1px solid ${C.bd}80`}}>
                <td style={{padding: "3px 8px", color: C.a3, fontWeight: 700, whiteSpace: "nowrap"}}>{code}</td>
                <td style={{padding: "3px 8px", color: C.tx}}>{value}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
