/* Auto-generated from unlock_catalog_extended.json — BCM Body parameter DIDs
 * in the 0x04C0..0x05DF range. 47 DIDs, 113 fields.
 *
 * Bit positions are MSB-first 0..N in catalog order — provisional, confirm
 * against a live BCM read before trusting writes. */

export const BCM_CONFIG_EXTRA_CATALOG = [
  { request: '05AE', groupName: 'BCM Body Presence Flags (0x05AE)', name: 'Full Central Vision Processing Present', bit: 0, length: 1, options: [{value:0,label:'Not present'},{value:1,label:'Present'}] },
  { request: '05AE', groupName: 'BCM Body Presence Flags (0x05AE)', name: 'Surround View Camera Present', bit: 1, length: 1, options: [{value:0,label:'Not present'},{value:1,label:'Present'}] },
  { request: '05AE', groupName: 'BCM Body Presence Flags (0x05AE)', name: 'Air Suspension Control Module (ASCM) — Suspension', bit: 2, length: 1, options: [{value:0,label:'Not present'},{value:1,label:'Present'}] },
  { request: '05AE', groupName: 'BCM Body Presence Flags (0x05AE)', name: 'Air Suspension Control Module (ASCM) — Active Damping', bit: 3, length: 1, options: [{value:0,label:'Not present'},{value:1,label:'Present'}] },
  { request: '05AE', groupName: 'BCM Body Presence Flags (0x05AE)', name: 'Red Key Feature Present', bit: 4, length: 1, options: [{value:0,label:'Disabled (Black Key only)'},{value:1,label:'Enabled (Red Key recognised)'}] },
  { request: '05AE', groupName: 'BCM Body Presence Flags (0x05AE)', name: 'Active Blind Spot Present', bit: 5, length: 1, options: [{value:0,label:'Not present'},{value:1,label:'Present'}] },
  { request: '04C8', groupName: 'BCM Body — DID 0x04C8 (1 field)', name: 'Left/Right Hand Drive', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04C9', groupName: 'BCM Body — DID 0x04C9 (2 fields)', name: 'Emode Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04C9', groupName: 'BCM Body — DID 0x04C9 (2 fields)', name: 'Auto Highbeam', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04CA', groupName: 'BCM Body — DID 0x04CA (1 field)', name: 'Shifter Type', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04CC', groupName: 'BCM Body — DID 0x04CC (4 fields)', name: 'Headrest Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04CC', groupName: 'BCM Body — DID 0x04CC (4 fields)', name: 'PTS Configuration', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04CC', groupName: 'BCM Body — DID 0x04CC (4 fields)', name: 'Rear View Camera', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04CC', groupName: 'BCM Body — DID 0x04CC (4 fields)', name: 'Select Speed Control  Feature Present0', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D0', groupName: 'BCM Body — DID 0x04D0 (1 field)', name: 'Run Flat Tires Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D1', groupName: 'BCM Body — DID 0x04D1 (5 fields)', name: 'Maserati Vehicle Mode', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D1', groupName: 'BCM Body — DID 0x04D1 (5 fields)', name: 'SKIM System Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D1', groupName: 'BCM Body — DID 0x04D1 (5 fields)', name: 'Air Conditioning Present', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D1', groupName: 'BCM Body — DID 0x04D1 (5 fields)', name: 'Full Size Spare', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D1', groupName: 'BCM Body — DID 0x04D1 (5 fields)', name: 'Off-road Capable', bit: 4, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D2', groupName: 'BCM Body — DID 0x04D2 (2 fields)', name: 'Drive mode feature configuration', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D2', groupName: 'BCM Body — DID 0x04D2 (2 fields)', name: 'Non-Regulated Tire Pressure Information System', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D3', groupName: 'BCM Body — DID 0x04D3 (2 fields)', name: 'ECM Drive Mode Sub-Feature Configuration', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04D3', groupName: 'BCM Body — DID 0x04D3 (2 fields)', name: 'Secure Park Feature Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DA', groupName: 'BCM Body — DID 0x04DA (2 fields)', name: 'Police Lighting Feature', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DA', groupName: 'BCM Body — DID 0x04DA (2 fields)', name: 'Power Lift Gate Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DB', groupName: 'BCM Body — DID 0x04DB (4 fields)', name: 'RKE System Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DB', groupName: 'BCM Body — DID 0x04DB (4 fields)', name: 'Sunshade Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DB', groupName: 'BCM Body — DID 0x04DB (4 fields)', name: 'T-CasE TypE0', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DB', groupName: 'BCM Body — DID 0x04DB (4 fields)', name: 'Wheel Base', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DC', groupName: 'BCM Body — DID 0x04DC (1 field)', name: 'Window Express Feature Configuration', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DD', groupName: 'BCM Body — DID 0x04DD (2 fields)', name: 'Door Alert Feature Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DD', groupName: 'BCM Body — DID 0x04DD (2 fields)', name: 'Two Fuel Sending Units Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DE', groupName: 'BCM Body — DID 0x04DE (2 fields)', name: 'Display Outside Temperature Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DE', groupName: 'BCM Body — DID 0x04DE (2 fields)', name: 'Vehicle Brand', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DF', groupName: 'BCM Body — DID 0x04DF (3 fields)', name: 'Display Compass Heading Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DF', groupName: 'BCM Body — DID 0x04DF (3 fields)', name: 'High Intensity Discharge Headlamps', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04DF', groupName: 'BCM Body — DID 0x04DF (3 fields)', name: 'Secondary Lock Present', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04E0', groupName: 'BCM Body — DID 0x04E0 (4 fields)', name: 'Forward Collision Warning Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04E0', groupName: 'BCM Body — DID 0x04E0 (4 fields)', name: 'Base TPM System Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04E0', groupName: 'BCM Body — DID 0x04E0 (4 fields)', name: 'Sport Mode Present', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04E0', groupName: 'BCM Body — DID 0x04E0 (4 fields)', name: 'Auto Park Present', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04E4', groupName: 'BCM Body — DID 0x04E4 (1 field)', name: '6xTransfer Case High Ratio (0-16.', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04EE', groupName: 'BCM Body — DID 0x04EE (3 fields)', name: 'Luci Feature Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04EE', groupName: 'BCM Body — DID 0x04EE (3 fields)', name: 'Dual Rear Wheel (DRW) Vehicle Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04EE', groupName: 'BCM Body — DID 0x04EE (3 fields)', name: 'Wait to Start Feature is Present', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04F4', groupName: 'BCM Body — DID 0x04F4 (4 fields)', name: 'Rear Door Lock Switch Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04F4', groupName: 'BCM Body — DID 0x04F4 (4 fields)', name: 'Child Display Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04F4', groupName: 'BCM Body — DID 0x04F4 (4 fields)', name: 'Off-Road Pages Present', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04F4', groupName: 'BCM Body — DID 0x04F4 (4 fields)', name: 'Park With Stop Present', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '04F8', groupName: 'BCM Body — DID 0x04F8 (1 field)', name: 'Analog Door Sensor Configuration', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0503', groupName: 'BCM Body — DID 0x0503 (3 fields)', name: 'Chiller Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0503', groupName: 'BCM Body — DID 0x0503 (3 fields)', name: 'High Octane Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0503', groupName: 'BCM Body — DID 0x0503 (3 fields)', name: 'Transmission Brake', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0504', groupName: 'BCM Body — DID 0x0504 (6 fields)', name: 'Overtaking Ban PresEnt', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0504', groupName: 'BCM Body — DID 0x0504 (6 fields)', name: 'SBL FBL Cornering Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0504', groupName: 'BCM Body — DID 0x0504 (6 fields)', name: 'Beam Shaping present', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0504', groupName: 'BCM Body — DID 0x0504 (6 fields)', name: 'Off', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0504', groupName: 'BCM Body — DID 0x0504 (6 fields)', name: 'PPPA Hard Button Present', bit: 4, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0504', groupName: 'BCM Body — DID 0x0504 (6 fields)', name: 'Digital CHMSL Camera Present', bit: 5, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0505', groupName: 'BCM Body — DID 0x0505 (1 field)', name: 'HDC Button Location', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0506', groupName: 'BCM Body — DID 0x0506 (2 fields)', name: 'Trailer Light Check Cycle Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0506', groupName: 'BCM Body — DID 0x0506 (2 fields)', name: 'Auxiliary Trailer Camera Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0507', groupName: 'BCM Body — DID 0x0507 (2 fields)', name: 'Headlamp LED Intensity Configuration Referred to Market Homologation', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0507', groupName: 'BCM Body — DID 0x0507 (2 fields)', name: 'Tire Fill Alert present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0508', groupName: 'BCM Body — DID 0x0508 (2 fields)', name: 'Wheel Base Length', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0508', groupName: 'BCM Body — DID 0x0508 (2 fields)', name: 'Overhead Console Type', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052A', groupName: 'BCM Body — DID 0x052A (3 fields)', name: 'Configuration Messages Status 3', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052A', groupName: 'BCM Body — DID 0x052A (3 fields)', name: 'Rear Camera Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052A', groupName: 'BCM Body — DID 0x052A (3 fields)', name: 'Front Park Assist Present', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052B', groupName: 'BCM Body — DID 0x052B (1 field)', name: 'Front Heated Seats Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052C', groupName: 'BCM Body — DID 0x052C (1 field)', name: 'Hill Start Assist Customer Setting Option Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052D', groupName: 'BCM Body — DID 0x052D (3 fields)', name: 'CTP Auto Lock Disabled', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052D', groupName: 'BCM Body — DID 0x052D (3 fields)', name: 'Vehicle Theft Alarm (VTA) System Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052D', groupName: 'BCM Body — DID 0x052D (3 fields)', name: 'Surround Sound Feature Present', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052E', groupName: 'BCM Body — DID 0x052E (5 fields)', name: 'CTP Max A/C Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052E', groupName: 'BCM Body — DID 0x052E (5 fields)', name: 'Hybrid Electric Powertrain Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052E', groupName: 'BCM Body — DID 0x052E (5 fields)', name: 'DtV SiDe', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052E', groupName: 'BCM Body — DID 0x052E (5 fields)', name: 'Tow Haul Switch Feature Present', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052E', groupName: 'BCM Body — DID 0x052E (5 fields)', name: 'PASS Call Feature Present', bit: 4, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052F', groupName: 'BCM Body — DID 0x052F (4 fields)', name: 'Memory Customer Setting Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052F', groupName: 'BCM Body — DID 0x052F (4 fields)', name: 'Microphone Tuning Parameter', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052F', groupName: 'BCM Body — DID 0x052F (4 fields)', name: 'CTP Navigation Haptic Speller ENableD0', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '052F', groupName: 'BCM Body — DID 0x052F (4 fields)', name: 'Disable Navigation Lockout', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0530', groupName: 'BCM Body — DID 0x0530 (2 fields)', name: 'Splash Screen Type', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0530', groupName: 'BCM Body — DID 0x0530 (2 fields)', name: 'PASS WiFi Antenna Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0534', groupName: 'BCM Body — DID 0x0534 (1 field)', name: 'Max Gear', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0535', groupName: 'BCM Body — DID 0x0535 (1 field)', name: 'Virtual Speedometer Units', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0536', groupName: 'BCM Body — DID 0x0536 (6 fields)', name: 'PTO Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0536', groupName: 'BCM Body — DID 0x0536 (6 fields)', name: 'Ambient Dimmer', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0536', groupName: 'BCM Body — DID 0x0536 (6 fields)', name: 'Vehicle Class', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0536', groupName: 'BCM Body — DID 0x0536 (6 fields)', name: 'Fleet Vehicle Content', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0536', groupName: 'BCM Body — DID 0x0536 (6 fields)', name: 'Gear Shift Indicator', bit: 4, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0536', groupName: 'BCM Body — DID 0x0536 (6 fields)', name: 'Warning Text Suppression', bit: 5, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0537', groupName: 'BCM Body — DID 0x0537 (2 fields)', name: 'Temperature Celsius for UK', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0537', groupName: 'BCM Body — DID 0x0537 (2 fields)', name: 'Type of Gallons', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0538', groupName: 'BCM Body — DID 0x0538 (4 fields)', name: 'TPM on RFHUB Setting', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0538', groupName: 'BCM Body — DID 0x0538 (4 fields)', name: 'ETC Bulb Check Setting', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0538', groupName: 'BCM Body — DID 0x0538 (4 fields)', name: 'Joystick Shifter Type (IC) Setting', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0538', groupName: 'BCM Body — DID 0x0538 (4 fields)', name: 'Brake Energy Regeneration Cluster Setting', bit: 3, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0539', groupName: 'BCM Body — DID 0x0539 (2 fields)', name: 'Manual DPF Regeneration Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '0539', groupName: 'BCM Body — DID 0x0539 (2 fields)', name: 'Speed Alert Threshold Setting', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05AC', groupName: 'BCM Body — DID 0x05AC (2 fields)', name: 'Paddles Lock-out Feature Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05AC', groupName: 'BCM Body — DID 0x05AC (2 fields)', name: 'Dynamic Steering Torque Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05AD', groupName: 'BCM Body — DID 0x05AD (1 field)', name: 'Automatic transmission type', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05AF', groupName: 'BCM Body — DID 0x05AF (2 fields)', name: 'Park Brake Type', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05AF', groupName: 'BCM Body — DID 0x05AF (2 fields)', name: 'Smart Alternator Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05B0', groupName: 'BCM Body — DID 0x05B0 (3 fields)', name: 'ADR Feature Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05B0', groupName: 'BCM Body — DID 0x05B0 (3 fields)', name: 'Active Grille Shutter (AGS) Feature Present', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05B0', groupName: 'BCM Body — DID 0x05B0 (3 fields)', name: 'Motor on Caliper Type', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05B1', groupName: 'BCM Body — DID 0x05B1 (3 fields)', name: 'Sunroof Present', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05B1', groupName: 'BCM Body — DID 0x05B1 (3 fields)', name: 'ECU Controlling PAD Lamp', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05B1', groupName: 'BCM Body — DID 0x05B1 (3 fields)', name: 'Vehicle Package', bit: 2, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05B2', groupName: 'BCM Body — DID 0x05B2 (2 fields)', name: 'Brake Type', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05B2', groupName: 'BCM Body — DID 0x05B2 (2 fields)', name: 'Suspension Type', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05D4', groupName: 'BCM Body — DID 0x05D4 (1 field)', name: 'Park Assist Tuning Set', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05D6', groupName: 'BCM Body — DID 0x05D6 (1 field)', name: 'EBL Management', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05D7', groupName: 'BCM Body — DID 0x05D7 (2 fields)', name: 'Rear AC Implementation (HVAC/HVAC_R)', bit: 0, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
  { request: '05D7', groupName: 'BCM Body — DID 0x05D7 (2 fields)', name: 'ICS Management', bit: 1, length: 1, options: [{value:0,label:'No / Off'},{value:1,label:'Yes / On'}] },
];

export const BCM_CONFIG_EXTRA_DIDS = [
  0x05AE,
  0x04C8,
  0x04C9,
  0x04CA,
  0x04CC,
  0x04D0,
  0x04D1,
  0x04D2,
  0x04D3,
  0x04DA,
  0x04DB,
  0x04DC,
  0x04DD,
  0x04DE,
  0x04DF,
  0x04E0,
  0x04E4,
  0x04EE,
  0x04F4,
  0x04F8,
  0x0503,
  0x0504,
  0x0505,
  0x0506,
  0x0507,
  0x0508,
  0x052A,
  0x052B,
  0x052C,
  0x052D,
  0x052E,
  0x052F,
  0x0530,
  0x0534,
  0x0535,
  0x0536,
  0x0537,
  0x0538,
  0x0539,
  0x05AC,
  0x05AD,
  0x05AF,
  0x05B0,
  0x05B1,
  0x05B2,
  0x05D4,
  0x05D6,
  0x05D7,
];
