// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/srt-command-center/AiCopilot.tsx": () => import("../components/mockups/srt-command-center/AiCopilot.tsx"),
  "./components/mockups/srt-command-center/Diagnose.tsx": () => import("../components/mockups/srt-command-center/Diagnose.tsx"),
  "./components/mockups/srt-command-center/ObdPull.tsx": () => import("../components/mockups/srt-command-center/ObdPull.tsx"),
  "./components/mockups/srt-command-center/UdsCommandCenter.tsx": () => import("../components/mockups/srt-command-center/UdsCommandCenter.tsx"),
  "./components/mockups/srt-command-center/VinChecksum.tsx": () => import("../components/mockups/srt-command-center/VinChecksum.tsx")
};
