"""
SRT Lab unlock catalog — universal adapter for the FCA J2534 unlock DLLs.

This module is now driven by ``unlock_catalog.json`` (generated by
``srtlab_unlock_catalog_gen.py``).  The previous hand-maintained
``MODULE_INFO`` and ``NATIVE`` tables are derived from that single source of
truth so adding a new reversed DLL only requires:

  1. Adding the Python port to ``canflash_seedkey.py`` (or
     ``srtlab_canflash_algos.py``'s ``CANFLASH_ALGOS`` registry).
  2. Re-running ``python3 srtlab_unlock_catalog_gen.py``.

For each DLL the catalog provides:
  * Metadata (CAN tx/rx, family, display label, decoded ``ecu_info`` blob).
  * A status of ``reversed`` (Python port exists) or ``dll_only`` (must be
    emulated under Unicorn).
  * The ``python_function`` name to call when status is ``reversed``.

Public API:
    unlock(module_name, seed, arg2=0, prefer_native=True)
    list_modules(category_filter=None)
    native_count(), emulated_count()
    MODULE_INFO   # legacy view: {name: {tx, rx, category, label, status, ...}}
    CATALOG       # parsed unlock_catalog.json (raw)
    CATALOG_PATH  # path to the JSON file

Usage:
    from srtlab_unlock_catalog import unlock, list_modules, MODULE_INFO

    key = unlock('huntsville_bcm', seed=0xDEADBEEF)
    key = unlock('lear_wcm',       seed=0xDEADBEEF)
    key = unlock('cummins_849',    seed=0xDEADBEEF)
"""

import json
import os
import sys
import threading

# Try to import pefile and unicorn — fall back gracefully if not installed
try:
    import pefile
    from unicorn import Uc, UC_ARCH_X86, UC_MODE_32
    from unicorn.x86_const import UC_X86_REG_ESP, UC_X86_REG_EAX
    HAVE_UNICORN = True
except ImportError:
    HAVE_UNICORN = False


# Locate the DLL directory + catalog file (next to this file)
_HERE = os.path.dirname(os.path.abspath(__file__))
DLL_DIR = os.path.join(_HERE, 'canflash_unlocks')
CATALOG_PATH = os.path.join(_HERE, 'unlock_catalog.json')


# ═══════════════════════════════════════════════════════════════════════
# Load the catalog (single source of truth)
# ═══════════════════════════════════════════════════════════════════════

def _load_catalog():
    if not os.path.isfile(CATALOG_PATH):
        return {
            'schema_version': 1,
            'entry_count': 0,
            'reversed_count': 0,
            'dll_only_count': 0,
            'entries': [],
        }
    with open(CATALOG_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)


CATALOG = _load_catalog()


# ═══════════════════════════════════════════════════════════════════════
# Derive Python algorithm functions from the catalog's python_function field
# ═══════════════════════════════════════════════════════════════════════

def _resolve_python_functions():
    """{module_name: callable} for every entry whose status is 'reversed'."""
    fns = {}
    # Prefer srtlab_canflash_algos.CANFLASH_ALGOS for entries that name their
    # function via the *_unlock convention.
    try:
        from srtlab_canflash_algos import CANFLASH_ALGOS
        for k, v in CANFLASH_ALGOS.items():
            fns[k] = v['fn']
    except Exception:  # pragma: no cover - optional dependency
        pass

    # Then pick up any canflash_seedkey.py functions the catalog references.
    try:
        import canflash_seedkey
        for entry in CATALOG.get('entries', []):
            py_fn = entry.get('python_function')
            mod = entry.get('module')
            if not py_fn or not mod or mod in fns:
                continue
            fn = getattr(canflash_seedkey, py_fn, None)
            if callable(fn):
                fns[mod] = fn
    except Exception:  # pragma: no cover
        pass

    return fns


NATIVE = _resolve_python_functions()


# ═══════════════════════════════════════════════════════════════════════
# Legacy MODULE_INFO view — derived from the catalog so consumers that
# accessed info['tx'], info['rx'], info['category'], info['label'] keep
# working.
# ═══════════════════════════════════════════════════════════════════════

def _legacy_view():
    out = {}
    for entry in CATALOG.get('entries', []):
        mod = entry.get('module')
        if not mod:
            continue
        family = entry.get('family') or 'misc'
        ecu = entry.get('ecu_info') or {}
        out[mod] = {
            'category': family,
            'tx': entry.get('tx_can_id'),
            'rx': entry.get('rx_can_id'),
            'label': entry.get('display_name') or mod.replace('_', ' ').title(),
            'status': entry.get('status'),
            'reason': entry.get('reason'),
            'python_function': entry.get('python_function'),
            'ecu_info': ecu,
            'family': family,
            'size_bytes': entry.get('size_bytes'),
            'file': entry.get('file'),
        }
    return out


MODULE_INFO = _legacy_view()


# ═══════════════════════════════════════════════════════════════════════
# Emulator wrapper — caches PE per DLL for performance
# ═══════════════════════════════════════════════════════════════════════

_pe_cache = {}
_pe_lock = threading.Lock()


def _emulate(dll_name, seed, arg2=0):
    if not HAVE_UNICORN:
        raise RuntimeError(
            'Unicorn and pefile required for DLL emulation. '
            'Install: pip install unicorn pefile')

    dll_path = os.path.join(DLL_DIR, dll_name + '.dll')
    if not os.path.isfile(dll_path):
        raise FileNotFoundError(f'DLL not found: {dll_path}')

    with _pe_lock:
        if dll_name not in _pe_cache:
            pe = pefile.PE(dll_path)
            unlock_rva = None
            for s in pe.DIRECTORY_ENTRY_EXPORT.symbols:
                if s.name and s.name.decode() == 'unlock':
                    unlock_rva = s.address
                    break
            if unlock_rva is None:
                raise ValueError(f'No `unlock` export in {dll_name}.dll')
            _pe_cache[dll_name] = (pe, unlock_rva)

    pe, unlock_rva = _pe_cache[dll_name]
    image_base = pe.OPTIONAL_HEADER.ImageBase
    raw = pe.__data__

    mu = Uc(UC_ARCH_X86, UC_MODE_32)
    size = (pe.OPTIONAL_HEADER.SizeOfImage + 0xFFF) & ~0xFFF
    mu.mem_map(image_base, size)
    mu.mem_write(image_base, raw[:pe.OPTIONAL_HEADER.SizeOfHeaders])
    for section in pe.sections:
        va = image_base + section.VirtualAddress
        data = section.get_data()
        if data:
            mu.mem_write(va, data)
    stack_base = 0x200000
    mu.mem_map(stack_base, 0x10000)
    esp = stack_base + 0x8000
    ret_addr = 0x100000
    mu.mem_map(ret_addr & ~0xFFF, 0x1000)
    esp -= 4; mu.mem_write(esp, arg2.to_bytes(4, 'little'))
    esp -= 4; mu.mem_write(esp, seed.to_bytes(4, 'little'))
    esp -= 4; mu.mem_write(esp, ret_addr.to_bytes(4, 'little'))
    mu.reg_write(UC_X86_REG_ESP, esp)
    mu.emu_start(image_base + unlock_rva, ret_addr, timeout=2_000_000)
    return mu.reg_read(UC_X86_REG_EAX)


# ═══════════════════════════════════════════════════════════════════════
# Public API
# ═══════════════════════════════════════════════════════════════════════

def _resolve_module_name(module_name):
    """Case-insensitive lookup against the catalog."""
    if module_name in MODULE_INFO:
        return module_name
    target = module_name.lower()
    for k in MODULE_INFO:
        if k.lower() == target:
            return k
    return None


def unlock(module_name, seed, arg2=0, prefer_native=True):
    """Compute the 4-byte unlock key for the given module and seed.

    Args:
        module_name: DLL basename, e.g. 'huntsville_bcm', 'cummins_849',
                     'alpine_radio', 'lear_wcm'.
        seed: 32-bit seed received from UDS 27 01 positive response.
        arg2: secondary seed argument (used by dcx_ptcm, alpine_rak, alpine_radio,
              and any other 2-arg unlock). Default 0.
        prefer_native: if True (default), use the catalog-resolved Python port
                       when available. Set False to force emulation (useful
                       to verify ports against the DLL).

    Returns:
        4-byte unlock key as a u32.
    """
    resolved = _resolve_module_name(module_name)
    if resolved is None:
        raise KeyError(
            f'Unknown module: {module_name}. Known modules: {sorted(MODULE_INFO)}')
    module_name = resolved

    if prefer_native and module_name in NATIVE:
        fn = NATIVE[module_name]
        try:
            # Some native fns take arg2, some don't
            return fn(seed, arg2)
        except TypeError:
            return fn(seed)

    return _emulate(module_name, seed, arg2)


def list_modules(category_filter=None):
    """Return sorted list of (name, info) pairs, optionally filtered by family/category prefix."""
    out = []
    for name, info in sorted(MODULE_INFO.items()):
        if category_filter is None or info['category'].startswith(category_filter):
            out.append((name, info))
    return out


def native_count():
    """How many modules have catalog-resolved Python implementations."""
    return sum(1 for n in MODULE_INFO if n in NATIVE)


def emulated_count():
    """How many modules fall back to Unicorn DLL emulation."""
    return sum(1 for n in MODULE_INFO if n not in NATIVE)


# ═══════════════════════════════════════════════════════════════════════
# CLI / demo
# ═══════════════════════════════════════════════════════════════════════

def _algo_family_count():
    """Count distinct algorithm-family tags across catalogued entries."""
    return len({
        e.get('algorithm') for e in CATALOG.get('entries', [])
        if e.get('algorithm')
    })


def stats():
    """Runtime dispatcher view of unlock coverage.

    Returns the *live* counts (computed by walking MODULE_INFO and the
    NATIVE callable table at this moment), not just the cached
    reversed_count / dll_only_count fields baked into the JSON. The two
    are kept in sync by test_native_count_matches_catalog_reversed,
    so under normal operation they agree — but the runtime view is the
    authoritative source for ''how many ports actually resolve right now''.
    """
    return {
        'schema_version': CATALOG.get('schema_version', 1),
        'entry_count': len(MODULE_INFO),
        'native_count': native_count(),
        'emulated_count': emulated_count(),
        'algo_family_count': _algo_family_count(),
        'source': 'dispatcher',
    }


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == '--stats':
        # Machine-readable JSON for the SRT Lab UI (consumed via the
        # /api/unlock-coverage/stats Express endpoint).
        print(json.dumps(stats()))
        sys.exit(0)

    print(f'SRT Lab unlock catalog — {len(MODULE_INFO)} FCA modules')
    print(f'  {native_count()} with catalog-resolved Python (verified byte-exact)')
    print(f'  {emulated_count()} via on-demand DLL emulation via Unicorn')
    print()

    if len(sys.argv) > 1 and sys.argv[1] == '--list':
        categories = sorted(set(info['category'] for info in MODULE_INFO.values()))
        for cat in categories:
            print(f'\n{cat}:')
            for name, info in list_modules(cat):
                native = '✓' if name in NATIVE else '  '
                tx = f"tx=0x{info['tx']:03X}" if info['tx'] else 'tx=?'
                rx = f"rx=0x{info['rx']:03X}" if info['rx'] else ''
                print(f"  {native} {name:<22s} {tx:<10s} {rx:<10s}  {info['label']}")
    else:
        # Demo: try unlock on a few modules
        if HAVE_UNICORN:
            SEED = 0xDEADBEEF
            print(f'Demo: unlock(module, seed=0x{SEED:08X}) across categories:\n')
            demo = [
                'cummins_849', 'gpec', 'ngc_engine', 'huntsville_bcm',
                'lear_wcm', 'alpine_radio', 'bosch_orc', 'trw_abs',
                'aisin_tcm', 'motorola_tipm7', 'may_scofield_itm',
            ]
            for name in demo:
                try:
                    k = unlock(name, SEED)
                    native = ' [native]' if name in NATIVE else ' [emulated]'
                    info = MODULE_INFO[name]
                    tx = f"tx=0x{info['tx']:03X}" if info['tx'] else 'tx=?'
                    print(f"  {name:<22s}  {tx}  key=0x{k:08X}{native}")
                except Exception as e:
                    print(f"  {name}: ERROR {e}")
        else:
            print('(install unicorn + pefile to run emulation demos)')

        print(f'\nRun with --list for full module catalog.')
