/* ======================================================================
 * AlfaOBD Mined Catalogs — re-export hub (Task #588)
 * ======================================================================
 *
 * Three committed JSON catalogs generated by scripts/src/mine-alfaobd.mjs
 * from AlfaOBD.exe (v2.5.7.0) and existing attached_assets evidence.
 * See MINING_NOTES.md for full provenance.
 *
 * Import from here, not directly from the JSON files, so callers survive
 * future catalog path changes without a widespread import-site edit.
 */

import udsServiceMap from "./udsServiceMap.generated.json";
import bcmConfigTab from "./bcmConfigTab.generated.json";
import bcmConfigDids from "./bcmConfigDids.generated.json";

export { udsServiceMap, bcmConfigTab, bcmConfigDids };

/** Convenience: the ordered BCM group list from the config tab catalog. */
export function getBcmGroups() {
  return bcmConfigTab.groups.slice().sort((a, b) => a.order - b.order);
}

/** Convenience: look up a DID entry by hex string (e.g. "0xDE00" or "DE00"). */
export function getDid(hexStr) {
  const key = hexStr.toUpperCase().startsWith("0X")
    ? hexStr.toUpperCase()
    : "0X" + hexStr.toUpperCase();
  const normalized = "0x" + key.slice(2);
  return bcmConfigDids.dids[normalized] || null;
}

/** Return all options in bcmConfigTab that reference a given DID. */
export function getOptionsForDid(hexStr) {
  const key = hexStr.toUpperCase().startsWith("0X")
    ? hexStr
    : "0x" + hexStr;
  const normalDid = "0x" + key.toUpperCase().slice(2);
  const group = bcmConfigTab.groups.find(
    (g) => g.did.toUpperCase() === normalDid.toUpperCase()
  );
  return group ? group.options : [];
}

/** Return the BCM UDS service map entry. */
export function getBcmUdsSequence() {
  return udsServiceMap.BCM;
}
